// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAuthorizationModelDocument(args?: GetAuthorizationModelDocumentArgs, opts?: pulumi.InvokeOptions): Promise<GetAuthorizationModelDocumentResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("openfga:index/getAuthorizationModelDocument:getAuthorizationModelDocument", {
        "dsl": args.dsl,
        "json": args.json,
        "modFilePath": args.modFilePath,
        "model": args.model,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAuthorizationModelDocument.
 */
export interface GetAuthorizationModelDocumentArgs {
    dsl?: string;
    json?: string;
    modFilePath?: string;
    model?: inputs.GetAuthorizationModelDocumentModel;
}

/**
 * A collection of values returned by getAuthorizationModelDocument.
 */
export interface GetAuthorizationModelDocumentResult {
    readonly dsl?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly json?: string;
    readonly modFilePath?: string;
    readonly model?: outputs.GetAuthorizationModelDocumentModel;
    readonly result: string;
}
export function getAuthorizationModelDocumentOutput(args?: GetAuthorizationModelDocumentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAuthorizationModelDocumentResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("openfga:index/getAuthorizationModelDocument:getAuthorizationModelDocument", {
        "dsl": args.dsl,
        "json": args.json,
        "modFilePath": args.modFilePath,
        "model": args.model,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getAuthorizationModelDocument.
 */
export interface GetAuthorizationModelDocumentOutputArgs {
    dsl?: pulumi.Input<string>;
    json?: pulumi.Input<string>;
    modFilePath?: pulumi.Input<string>;
    model?: pulumi.Input<inputs.GetAuthorizationModelDocumentModelArgs>;
}
