packages:
  - packages/*
  - docs

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
  - oxc-resolver
  - protobufjs
  - sharp

overrides:
  axios@<1.12.0: '>=1.12.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@<4.1.1: '>=4.1.1'
