// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AmazonSnsIntegration extends pulumi.CustomResource {
    /**
     * Get an existing AmazonSnsIntegration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AmazonSnsIntegrationState, opts?: pulumi.CustomResourceOptions): AmazonSnsIntegration {
        return new AmazonSnsIntegration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'better-uptime:index/amazonSnsIntegration:AmazonSnsIntegration';

    /**
     * Returns true if the given object is an instance of AmazonSnsIntegration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AmazonSnsIntegration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AmazonSnsIntegration.__pulumiType;
    }

    /**
     * When acknowledging an incident, how to extract an alert id, a unique alert identifier which will be used to acknowledge and resolve incidents.
     */
    declare public readonly acknowledgedAlertIdField: pulumi.Output<outputs.AmazonSnsIntegrationAcknowledgedAlertIdField | undefined>;
    /**
     * Should an incident be acknowledged for all notifications, those satisfying all acknowledged_rules, or those satisfying any of them. Valid values are unused, all, or any
     */
    declare public readonly acknowledgedRuleType: pulumi.Output<string>;
    /**
     * An array of rules to match to acknowledge an incident.
     */
    declare public readonly acknowledgedRules: pulumi.Output<outputs.AmazonSnsIntegrationAcknowledgedRule[] | undefined>;
    /**
     * Whether to call when a new incident is created.
     */
    declare public readonly call: pulumi.Output<boolean>;
    /**
     * A field describing how to extract an incident cause, used as a short description shared with the team member on-call.
     */
    declare public readonly causeField: pulumi.Output<outputs.AmazonSnsIntegrationCauseField | undefined>;
    /**
     * The time when this Amazon SNS integration was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Whether to send a critical push notification that ignores the mute switch and Do not Disturb mode when a new incident is created.
     */
    declare public readonly criticalAlert: pulumi.Output<boolean>;
    /**
     * Whether to send an email when a new incident is created.
     */
    declare public readonly email: pulumi.Output<boolean>;
    /**
     * The name of this Amazon SNS integration.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * An array of additional fields, which will be extracted when acknowledging an incident.
     */
    declare public readonly otherAcknowledgedFields: pulumi.Output<outputs.AmazonSnsIntegrationOtherAcknowledgedField[] | undefined>;
    /**
     * An array of additional fields, which will be extracted when resolving an incident.
     */
    declare public readonly otherResolvedFields: pulumi.Output<outputs.AmazonSnsIntegrationOtherResolvedField[] | undefined>;
    /**
     * An array of additional fields, which will be extracted when starting an incident.
     */
    declare public readonly otherStartedFields: pulumi.Output<outputs.AmazonSnsIntegrationOtherStartedField[] | undefined>;
    /**
     * Set to true to pause monitoring - we won't notify you about downtime. Set to false to resume monitoring.
     */
    declare public readonly paused: pulumi.Output<boolean>;
    /**
     * ID of the escalation policy associated with the Amazon SNS integration.
     */
    declare public readonly policyId: pulumi.Output<string>;
    /**
     * Whether to send a push notification when a new incident is created.
     */
    declare public readonly push: pulumi.Output<boolean>;
    /**
     * How long the integration must be up to automatically mark an incident as resolved after being down.
     */
    declare public readonly recoveryPeriod: pulumi.Output<number>;
    /**
     * When resolving an incident, how to extract an alert id, a unique alert identifier which will be used to acknowledge and resolve incidents.
     */
    declare public readonly resolvedAlertIdField: pulumi.Output<outputs.AmazonSnsIntegrationResolvedAlertIdField | undefined>;
    /**
     * Should an incident be resolved for all notifications, those satisfying all resolved_rules, or those satisfying any of them. Valid values are unused, all, or any
     */
    declare public readonly resolvedRuleType: pulumi.Output<string>;
    /**
     * An array of rules to match to resolved an incident.
     */
    declare public readonly resolvedRules: pulumi.Output<outputs.AmazonSnsIntegrationResolvedRule[] | undefined>;
    /**
     * Sample Amazon SNS message. Used only to make the configuration easier.
     */
    declare public /*out*/ readonly sampleBody: pulumi.Output<string>;
    /**
     * Sample request HTTP headers of the notification (separated by a newline). Used only to make the configuration easier.
     */
    declare public /*out*/ readonly sampleHeaders: pulumi.Output<string>;
    /**
     * Sample query string of the notification (without the leading ?). Used only to make the configuration easier.
     */
    declare public /*out*/ readonly sampleQueryString: pulumi.Output<string>;
    /**
     * Whether to send an SMS when a new incident is created.
     */
    declare public readonly sms: pulumi.Output<boolean>;
    /**
     * When starting an incident, how to extract an alert id, a unique alert identifier which will be used to acknowledge and resolve incidents.
     */
    declare public readonly startedAlertIdField: pulumi.Output<outputs.AmazonSnsIntegrationStartedAlertIdField | undefined>;
    /**
     * Should an incident be started for all notifications, those satisfying all started_rules, or those satisfying any of them. Valid values are unused, all, or any
     */
    declare public readonly startedRuleType: pulumi.Output<string>;
    /**
     * An array of rules to match to start a new incident.
     */
    declare public readonly startedRules: pulumi.Output<outputs.AmazonSnsIntegrationStartedRule[] | undefined>;
    /**
     * Whether the Amazon SNS subscription has been confirmed: active once AWS has confirmed it, awaiting until then. Set by Better Stack when AWS confirms it, so it is read-only.
     */
    declare public /*out*/ readonly subscriptionState: pulumi.Output<string>;
    /**
     * Used to specify the team the resource should be created in when using global tokens. You can't update this value later.
     */
    declare public readonly teamName: pulumi.Output<string | undefined>;
    /**
     * How long to wait before escalating the incident alert to the team. Leave blank to disable escalating to the entire team.
     */
    declare public readonly teamWait: pulumi.Output<number>;
    /**
     * An optional field describing how to extract a customized incident title. Defaults to the Amazon SNS envelope's Subject. It can be changed but not removed through Terraform.
     */
    declare public readonly titleField: pulumi.Output<outputs.AmazonSnsIntegrationTitleField | undefined>;
    /**
     * The ARN of the Amazon SNS topic this integration is subscribed to. Set by Better Stack when AWS confirms the subscription, so it is read-only.
     */
    declare public /*out*/ readonly topicArn: pulumi.Output<string>;
    /**
     * The time when this Amazon SNS integration was updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * The URL to subscribe the Amazon SNS topic to, using the HTTPS protocol with raw message delivery disabled.
     */
    declare public /*out*/ readonly url: pulumi.Output<string>;

    /**
     * Create a AmazonSnsIntegration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AmazonSnsIntegrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AmazonSnsIntegrationArgs | AmazonSnsIntegrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AmazonSnsIntegrationState | undefined;
            resourceInputs["acknowledgedAlertIdField"] = state?.acknowledgedAlertIdField;
            resourceInputs["acknowledgedRuleType"] = state?.acknowledgedRuleType;
            resourceInputs["acknowledgedRules"] = state?.acknowledgedRules;
            resourceInputs["call"] = state?.call;
            resourceInputs["causeField"] = state?.causeField;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["criticalAlert"] = state?.criticalAlert;
            resourceInputs["email"] = state?.email;
            resourceInputs["name"] = state?.name;
            resourceInputs["otherAcknowledgedFields"] = state?.otherAcknowledgedFields;
            resourceInputs["otherResolvedFields"] = state?.otherResolvedFields;
            resourceInputs["otherStartedFields"] = state?.otherStartedFields;
            resourceInputs["paused"] = state?.paused;
            resourceInputs["policyId"] = state?.policyId;
            resourceInputs["push"] = state?.push;
            resourceInputs["recoveryPeriod"] = state?.recoveryPeriod;
            resourceInputs["resolvedAlertIdField"] = state?.resolvedAlertIdField;
            resourceInputs["resolvedRuleType"] = state?.resolvedRuleType;
            resourceInputs["resolvedRules"] = state?.resolvedRules;
            resourceInputs["sampleBody"] = state?.sampleBody;
            resourceInputs["sampleHeaders"] = state?.sampleHeaders;
            resourceInputs["sampleQueryString"] = state?.sampleQueryString;
            resourceInputs["sms"] = state?.sms;
            resourceInputs["startedAlertIdField"] = state?.startedAlertIdField;
            resourceInputs["startedRuleType"] = state?.startedRuleType;
            resourceInputs["startedRules"] = state?.startedRules;
            resourceInputs["subscriptionState"] = state?.subscriptionState;
            resourceInputs["teamName"] = state?.teamName;
            resourceInputs["teamWait"] = state?.teamWait;
            resourceInputs["titleField"] = state?.titleField;
            resourceInputs["topicArn"] = state?.topicArn;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as AmazonSnsIntegrationArgs | undefined;
            if (args?.acknowledgedRuleType === undefined && !opts.urn) {
                throw new Error("Missing required property 'acknowledgedRuleType'");
            }
            if (args?.resolvedRuleType === undefined && !opts.urn) {
                throw new Error("Missing required property 'resolvedRuleType'");
            }
            if (args?.startedRuleType === undefined && !opts.urn) {
                throw new Error("Missing required property 'startedRuleType'");
            }
            resourceInputs["acknowledgedAlertIdField"] = args?.acknowledgedAlertIdField;
            resourceInputs["acknowledgedRuleType"] = args?.acknowledgedRuleType;
            resourceInputs["acknowledgedRules"] = args?.acknowledgedRules;
            resourceInputs["call"] = args?.call;
            resourceInputs["causeField"] = args?.causeField;
            resourceInputs["criticalAlert"] = args?.criticalAlert;
            resourceInputs["email"] = args?.email;
            resourceInputs["name"] = args?.name;
            resourceInputs["otherAcknowledgedFields"] = args?.otherAcknowledgedFields;
            resourceInputs["otherResolvedFields"] = args?.otherResolvedFields;
            resourceInputs["otherStartedFields"] = args?.otherStartedFields;
            resourceInputs["paused"] = args?.paused;
            resourceInputs["policyId"] = args?.policyId;
            resourceInputs["push"] = args?.push;
            resourceInputs["recoveryPeriod"] = args?.recoveryPeriod;
            resourceInputs["resolvedAlertIdField"] = args?.resolvedAlertIdField;
            resourceInputs["resolvedRuleType"] = args?.resolvedRuleType;
            resourceInputs["resolvedRules"] = args?.resolvedRules;
            resourceInputs["sms"] = args?.sms;
            resourceInputs["startedAlertIdField"] = args?.startedAlertIdField;
            resourceInputs["startedRuleType"] = args?.startedRuleType;
            resourceInputs["startedRules"] = args?.startedRules;
            resourceInputs["teamName"] = args?.teamName;
            resourceInputs["teamWait"] = args?.teamWait;
            resourceInputs["titleField"] = args?.titleField;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["sampleBody"] = undefined /*out*/;
            resourceInputs["sampleHeaders"] = undefined /*out*/;
            resourceInputs["sampleQueryString"] = undefined /*out*/;
            resourceInputs["subscriptionState"] = undefined /*out*/;
            resourceInputs["topicArn"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AmazonSnsIntegration.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AmazonSnsIntegration resources.
 */
export interface AmazonSnsIntegrationState {
    /**
     * When acknowledging an incident, how to extract an alert id, a unique alert identifier which will be used to acknowledge and resolve incidents.
     */
    acknowledgedAlertIdField?: pulumi.Input<inputs.AmazonSnsIntegrationAcknowledgedAlertIdField | undefined>;
    /**
     * Should an incident be acknowledged for all notifications, those satisfying all acknowledged_rules, or those satisfying any of them. Valid values are unused, all, or any
     */
    acknowledgedRuleType?: pulumi.Input<string | undefined>;
    /**
     * An array of rules to match to acknowledge an incident.
     */
    acknowledgedRules?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationAcknowledgedRule>[] | undefined>;
    /**
     * Whether to call when a new incident is created.
     */
    call?: pulumi.Input<boolean | undefined>;
    /**
     * A field describing how to extract an incident cause, used as a short description shared with the team member on-call.
     */
    causeField?: pulumi.Input<inputs.AmazonSnsIntegrationCauseField | undefined>;
    /**
     * The time when this Amazon SNS integration was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Whether to send a critical push notification that ignores the mute switch and Do not Disturb mode when a new incident is created.
     */
    criticalAlert?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to send an email when a new incident is created.
     */
    email?: pulumi.Input<boolean | undefined>;
    /**
     * The name of this Amazon SNS integration.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * An array of additional fields, which will be extracted when acknowledging an incident.
     */
    otherAcknowledgedFields?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationOtherAcknowledgedField>[] | undefined>;
    /**
     * An array of additional fields, which will be extracted when resolving an incident.
     */
    otherResolvedFields?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationOtherResolvedField>[] | undefined>;
    /**
     * An array of additional fields, which will be extracted when starting an incident.
     */
    otherStartedFields?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationOtherStartedField>[] | undefined>;
    /**
     * Set to true to pause monitoring - we won't notify you about downtime. Set to false to resume monitoring.
     */
    paused?: pulumi.Input<boolean | undefined>;
    /**
     * ID of the escalation policy associated with the Amazon SNS integration.
     */
    policyId?: pulumi.Input<string | undefined>;
    /**
     * Whether to send a push notification when a new incident is created.
     */
    push?: pulumi.Input<boolean | undefined>;
    /**
     * How long the integration must be up to automatically mark an incident as resolved after being down.
     */
    recoveryPeriod?: pulumi.Input<number | undefined>;
    /**
     * When resolving an incident, how to extract an alert id, a unique alert identifier which will be used to acknowledge and resolve incidents.
     */
    resolvedAlertIdField?: pulumi.Input<inputs.AmazonSnsIntegrationResolvedAlertIdField | undefined>;
    /**
     * Should an incident be resolved for all notifications, those satisfying all resolved_rules, or those satisfying any of them. Valid values are unused, all, or any
     */
    resolvedRuleType?: pulumi.Input<string | undefined>;
    /**
     * An array of rules to match to resolved an incident.
     */
    resolvedRules?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationResolvedRule>[] | undefined>;
    /**
     * Sample Amazon SNS message. Used only to make the configuration easier.
     */
    sampleBody?: pulumi.Input<string | undefined>;
    /**
     * Sample request HTTP headers of the notification (separated by a newline). Used only to make the configuration easier.
     */
    sampleHeaders?: pulumi.Input<string | undefined>;
    /**
     * Sample query string of the notification (without the leading ?). Used only to make the configuration easier.
     */
    sampleQueryString?: pulumi.Input<string | undefined>;
    /**
     * Whether to send an SMS when a new incident is created.
     */
    sms?: pulumi.Input<boolean | undefined>;
    /**
     * When starting an incident, how to extract an alert id, a unique alert identifier which will be used to acknowledge and resolve incidents.
     */
    startedAlertIdField?: pulumi.Input<inputs.AmazonSnsIntegrationStartedAlertIdField | undefined>;
    /**
     * Should an incident be started for all notifications, those satisfying all started_rules, or those satisfying any of them. Valid values are unused, all, or any
     */
    startedRuleType?: pulumi.Input<string | undefined>;
    /**
     * An array of rules to match to start a new incident.
     */
    startedRules?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationStartedRule>[] | undefined>;
    /**
     * Whether the Amazon SNS subscription has been confirmed: active once AWS has confirmed it, awaiting until then. Set by Better Stack when AWS confirms it, so it is read-only.
     */
    subscriptionState?: pulumi.Input<string | undefined>;
    /**
     * Used to specify the team the resource should be created in when using global tokens. You can't update this value later.
     */
    teamName?: pulumi.Input<string | undefined>;
    /**
     * How long to wait before escalating the incident alert to the team. Leave blank to disable escalating to the entire team.
     */
    teamWait?: pulumi.Input<number | undefined>;
    /**
     * An optional field describing how to extract a customized incident title. Defaults to the Amazon SNS envelope's Subject. It can be changed but not removed through Terraform.
     */
    titleField?: pulumi.Input<inputs.AmazonSnsIntegrationTitleField | undefined>;
    /**
     * The ARN of the Amazon SNS topic this integration is subscribed to. Set by Better Stack when AWS confirms the subscription, so it is read-only.
     */
    topicArn?: pulumi.Input<string | undefined>;
    /**
     * The time when this Amazon SNS integration was updated.
     */
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * The URL to subscribe the Amazon SNS topic to, using the HTTPS protocol with raw message delivery disabled.
     */
    url?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a AmazonSnsIntegration resource.
 */
export interface AmazonSnsIntegrationArgs {
    /**
     * When acknowledging an incident, how to extract an alert id, a unique alert identifier which will be used to acknowledge and resolve incidents.
     */
    acknowledgedAlertIdField?: pulumi.Input<inputs.AmazonSnsIntegrationAcknowledgedAlertIdField | undefined>;
    /**
     * Should an incident be acknowledged for all notifications, those satisfying all acknowledged_rules, or those satisfying any of them. Valid values are unused, all, or any
     */
    acknowledgedRuleType: pulumi.Input<string>;
    /**
     * An array of rules to match to acknowledge an incident.
     */
    acknowledgedRules?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationAcknowledgedRule>[] | undefined>;
    /**
     * Whether to call when a new incident is created.
     */
    call?: pulumi.Input<boolean | undefined>;
    /**
     * A field describing how to extract an incident cause, used as a short description shared with the team member on-call.
     */
    causeField?: pulumi.Input<inputs.AmazonSnsIntegrationCauseField | undefined>;
    /**
     * Whether to send a critical push notification that ignores the mute switch and Do not Disturb mode when a new incident is created.
     */
    criticalAlert?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to send an email when a new incident is created.
     */
    email?: pulumi.Input<boolean | undefined>;
    /**
     * The name of this Amazon SNS integration.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * An array of additional fields, which will be extracted when acknowledging an incident.
     */
    otherAcknowledgedFields?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationOtherAcknowledgedField>[] | undefined>;
    /**
     * An array of additional fields, which will be extracted when resolving an incident.
     */
    otherResolvedFields?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationOtherResolvedField>[] | undefined>;
    /**
     * An array of additional fields, which will be extracted when starting an incident.
     */
    otherStartedFields?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationOtherStartedField>[] | undefined>;
    /**
     * Set to true to pause monitoring - we won't notify you about downtime. Set to false to resume monitoring.
     */
    paused?: pulumi.Input<boolean | undefined>;
    /**
     * ID of the escalation policy associated with the Amazon SNS integration.
     */
    policyId?: pulumi.Input<string | undefined>;
    /**
     * Whether to send a push notification when a new incident is created.
     */
    push?: pulumi.Input<boolean | undefined>;
    /**
     * How long the integration must be up to automatically mark an incident as resolved after being down.
     */
    recoveryPeriod?: pulumi.Input<number | undefined>;
    /**
     * When resolving an incident, how to extract an alert id, a unique alert identifier which will be used to acknowledge and resolve incidents.
     */
    resolvedAlertIdField?: pulumi.Input<inputs.AmazonSnsIntegrationResolvedAlertIdField | undefined>;
    /**
     * Should an incident be resolved for all notifications, those satisfying all resolved_rules, or those satisfying any of them. Valid values are unused, all, or any
     */
    resolvedRuleType: pulumi.Input<string>;
    /**
     * An array of rules to match to resolved an incident.
     */
    resolvedRules?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationResolvedRule>[] | undefined>;
    /**
     * Whether to send an SMS when a new incident is created.
     */
    sms?: pulumi.Input<boolean | undefined>;
    /**
     * When starting an incident, how to extract an alert id, a unique alert identifier which will be used to acknowledge and resolve incidents.
     */
    startedAlertIdField?: pulumi.Input<inputs.AmazonSnsIntegrationStartedAlertIdField | undefined>;
    /**
     * Should an incident be started for all notifications, those satisfying all started_rules, or those satisfying any of them. Valid values are unused, all, or any
     */
    startedRuleType: pulumi.Input<string>;
    /**
     * An array of rules to match to start a new incident.
     */
    startedRules?: pulumi.Input<pulumi.Input<inputs.AmazonSnsIntegrationStartedRule>[] | undefined>;
    /**
     * Used to specify the team the resource should be created in when using global tokens. You can't update this value later.
     */
    teamName?: pulumi.Input<string | undefined>;
    /**
     * How long to wait before escalating the incident alert to the team. Leave blank to disable escalating to the entire team.
     */
    teamWait?: pulumi.Input<number | undefined>;
    /**
     * An optional field describing how to extract a customized incident title. Defaults to the Amazon SNS envelope's Subject. It can be changed but not removed through Terraform.
     */
    titleField?: pulumi.Input<inputs.AmazonSnsIntegrationTitleField | undefined>;
}
