// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AlertScheduleRestriction {
    /**
     * Blocked time windows, half-open `[start, end)`. Windows must not overlap or touch, except that one may end at `00:00` where another starts. A window may wrap midnight (<span pulumi-lang-nodejs="`end`" pulumi-lang-dotnet="`End`" pulumi-lang-go="`end`" pulumi-lang-python="`end`" pulumi-lang-yaml="`end`" pulumi-lang-java="`end`" pulumi-lang-hcl="`end`">`end`</span> before <span pulumi-lang-nodejs="`start`" pulumi-lang-dotnet="`Start`" pulumi-lang-go="`start`" pulumi-lang-python="`start`" pulumi-lang-yaml="`start`" pulumi-lang-java="`start`" pulumi-lang-hcl="`start`">`start`</span>), but only as the sole window, and two windows meeting at midnight are only allowed alongside a third. PostHog enforces its own limits on window length and count and reports them on apply. Remove <span pulumi-lang-nodejs="`scheduleRestriction`" pulumi-lang-dotnet="`ScheduleRestriction`" pulumi-lang-go="`scheduleRestriction`" pulumi-lang-python="`schedule_restriction`" pulumi-lang-yaml="`scheduleRestriction`" pulumi-lang-java="`scheduleRestriction`" pulumi-lang-hcl="`schedule_restriction`">`scheduleRestriction`</span> to disable quiet hours.
     */
    blockedWindows: pulumi.Input<pulumi.Input<inputs.AlertScheduleRestrictionBlockedWindow>[]>;
}

export interface AlertScheduleRestrictionBlockedWindow {
    /**
     * End time `HH:MM` (24-hour, project timezone). Exclusive.
     */
    end: pulumi.Input<string>;
    /**
     * Start time `HH:MM` (24-hour, project timezone). Inclusive.
     */
    start: pulumi.Input<string>;
}

export interface DashboardLayoutTile {
    /**
     * Background color of the tile. Valid values are defined by the PostHog API; see [InsightColor in types.ts](https://github.com/PostHog/posthog/blob/master/frontend/src/types.ts#L2154) for the current list.
     */
    color?: pulumi.Input<string | undefined>;
    /**
     * ID of the insight to display. Exactly one of<span pulumi-lang-nodejs=" insightId " pulumi-lang-dotnet=" InsightId " pulumi-lang-go=" insightId " pulumi-lang-python=" insight_id " pulumi-lang-yaml=" insightId " pulumi-lang-java=" insightId " pulumi-lang-hcl=" insight_id "> insightId </span>or<span pulumi-lang-nodejs=" textBody " pulumi-lang-dotnet=" TextBody " pulumi-lang-go=" textBody " pulumi-lang-python=" text_body " pulumi-lang-yaml=" textBody " pulumi-lang-java=" textBody " pulumi-lang-hcl=" text_body "> textBody </span>must be set.
     */
    insightId?: pulumi.Input<number | undefined>;
    /**
     * JSON object with breakpoint keys <span pulumi-lang-nodejs="`sm`" pulumi-lang-dotnet="`Sm`" pulumi-lang-go="`sm`" pulumi-lang-python="`sm`" pulumi-lang-yaml="`sm`" pulumi-lang-java="`sm`" pulumi-lang-hcl="`sm`">`sm`</span> and/or <span pulumi-lang-nodejs="`xs`" pulumi-lang-dotnet="`Xs`" pulumi-lang-go="`xs`" pulumi-lang-python="`xs`" pulumi-lang-yaml="`xs`" pulumi-lang-java="`xs`" pulumi-lang-hcl="`xs`">`xs`</span>, each containing position properties: <span pulumi-lang-nodejs="`x`" pulumi-lang-dotnet="`X`" pulumi-lang-go="`x`" pulumi-lang-python="`x`" pulumi-lang-yaml="`x`" pulumi-lang-java="`x`" pulumi-lang-hcl="`x`">`x`</span>, <span pulumi-lang-nodejs="`y`" pulumi-lang-dotnet="`Y`" pulumi-lang-go="`y`" pulumi-lang-python="`y`" pulumi-lang-yaml="`y`" pulumi-lang-java="`y`" pulumi-lang-hcl="`y`">`y`</span>, <span pulumi-lang-nodejs="`w`" pulumi-lang-dotnet="`W`" pulumi-lang-go="`w`" pulumi-lang-python="`w`" pulumi-lang-yaml="`w`" pulumi-lang-java="`w`" pulumi-lang-hcl="`w`">`w`</span>, <span pulumi-lang-nodejs="`h`" pulumi-lang-dotnet="`H`" pulumi-lang-go="`h`" pulumi-lang-python="`h`" pulumi-lang-yaml="`h`" pulumi-lang-java="`h`" pulumi-lang-hcl="`h`">`h`</span> (required), and optionally `minW`, `minH` (e.g. `{"sm":{"x":0,"y":0,"w":6,"h":5},"xs":{"x":0,"y":0,"w":1,"h":5}}`). Semantic JSON equality is used to suppress phantom diffs.
     */
    layoutsJson?: pulumi.Input<string | undefined>;
    /**
     * Whether to show the insight description on the tile. Omit the field to clear it back to the PostHog API default (<span pulumi-lang-nodejs="`null`" pulumi-lang-dotnet="`Null`" pulumi-lang-go="`null`" pulumi-lang-python="`null`" pulumi-lang-yaml="`null`" pulumi-lang-java="`null`" pulumi-lang-hcl="`null`">`null`</span>).
     */
    showDescription?: pulumi.Input<boolean | undefined>;
    /**
     * Markdown body for a text tile (max 4000 characters). Exactly one of<span pulumi-lang-nodejs=" insightId " pulumi-lang-dotnet=" InsightId " pulumi-lang-go=" insightId " pulumi-lang-python=" insight_id " pulumi-lang-yaml=" insightId " pulumi-lang-java=" insightId " pulumi-lang-hcl=" insight_id "> insightId </span>or<span pulumi-lang-nodejs=" textBody " pulumi-lang-dotnet=" TextBody " pulumi-lang-go=" textBody " pulumi-lang-python=" text_body " pulumi-lang-yaml=" textBody " pulumi-lang-java=" textBody " pulumi-lang-hcl=" text_body "> textBody </span>must be set.
     */
    textBody?: pulumi.Input<string | undefined>;
    /**
     * Server-assigned tile ID. Populated after the first apply.
     */
    tileId?: pulumi.Input<number | undefined>;
}

export interface ExperimentStatus {
    /**
     * Desired lifecycle state — one of <span pulumi-lang-nodejs="`draft`" pulumi-lang-dotnet="`Draft`" pulumi-lang-go="`draft`" pulumi-lang-python="`draft`" pulumi-lang-yaml="`draft`" pulumi-lang-java="`draft`" pulumi-lang-hcl="`draft`">`draft`</span>, <span pulumi-lang-nodejs="`running`" pulumi-lang-dotnet="`Running`" pulumi-lang-go="`running`" pulumi-lang-python="`running`" pulumi-lang-yaml="`running`" pulumi-lang-java="`running`" pulumi-lang-hcl="`running`">`running`</span>, <span pulumi-lang-nodejs="`paused`" pulumi-lang-dotnet="`Paused`" pulumi-lang-go="`paused`" pulumi-lang-python="`paused`" pulumi-lang-yaml="`paused`" pulumi-lang-java="`paused`" pulumi-lang-hcl="`paused`">`paused`</span>, or <span pulumi-lang-nodejs="`stopped`" pulumi-lang-dotnet="`Stopped`" pulumi-lang-go="`stopped`" pulumi-lang-python="`stopped`" pulumi-lang-yaml="`stopped`" pulumi-lang-java="`stopped`" pulumi-lang-hcl="`stopped`">`stopped`</span> (required; use <span pulumi-lang-nodejs="`draft`" pulumi-lang-dotnet="`Draft`" pulumi-lang-go="`draft`" pulumi-lang-python="`draft`" pulumi-lang-yaml="`draft`" pulumi-lang-java="`draft`" pulumi-lang-hcl="`draft`">`draft`</span> for a not-yet-launched experiment). The lifecycle is forward-only.
     */
    state?: pulumi.Input<string | undefined>;
    /**
     * Metadata applied when stopping the experiment (read only when `state = "stopped"`, ignored otherwise).
     */
    stopped?: pulumi.Input<inputs.ExperimentStatusStopped | undefined>;
}

export interface ExperimentStatusStopped {
    /**
     * Conclusion recorded when the experiment is stopped — one of <span pulumi-lang-nodejs="`won`" pulumi-lang-dotnet="`Won`" pulumi-lang-go="`won`" pulumi-lang-python="`won`" pulumi-lang-yaml="`won`" pulumi-lang-java="`won`" pulumi-lang-hcl="`won`">`won`</span>, <span pulumi-lang-nodejs="`lost`" pulumi-lang-dotnet="`Lost`" pulumi-lang-go="`lost`" pulumi-lang-python="`lost`" pulumi-lang-yaml="`lost`" pulumi-lang-java="`lost`" pulumi-lang-hcl="`lost`">`lost`</span>, <span pulumi-lang-nodejs="`inconclusive`" pulumi-lang-dotnet="`Inconclusive`" pulumi-lang-go="`inconclusive`" pulumi-lang-python="`inconclusive`" pulumi-lang-yaml="`inconclusive`" pulumi-lang-java="`inconclusive`" pulumi-lang-hcl="`inconclusive`">`inconclusive`</span>, <span pulumi-lang-nodejs="`stoppedEarly`" pulumi-lang-dotnet="`StoppedEarly`" pulumi-lang-go="`stoppedEarly`" pulumi-lang-python="`stopped_early`" pulumi-lang-yaml="`stoppedEarly`" pulumi-lang-java="`stoppedEarly`" pulumi-lang-hcl="`stopped_early`">`stoppedEarly`</span>, <span pulumi-lang-nodejs="`invalid`" pulumi-lang-dotnet="`Invalid`" pulumi-lang-go="`invalid`" pulumi-lang-python="`invalid`" pulumi-lang-yaml="`invalid`" pulumi-lang-java="`invalid`" pulumi-lang-hcl="`invalid`">`invalid`</span>. Fully managed: applied at stop time and editable afterwards (an edit on an already-stopped experiment is PATCHed and read back).
     */
    conclusion?: pulumi.Input<string | undefined>;
    /**
     * Free-text note recorded alongside the conclusion. Fully managed (sent on stop/update and read back).
     */
    conclusionComment?: pulumi.Input<string | undefined>;
    /**
     * When shipping, prepend a catch-all release condition (roll out to everyone) instead of only flipping the variant distribution. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>. Config-only.
     */
    releaseToEveryone?: pulumi.Input<boolean | undefined>;
    /**
     * Key of the winning variant to ship. Rewrites the linked flag's distribution so this variant gets 100% and ends the experiment. If the flag is managed by a <span pulumi-lang-nodejs="`posthog.FeatureFlag`" pulumi-lang-dotnet="`posthog.FeatureFlag`" pulumi-lang-go="`FeatureFlag`" pulumi-lang-python="`FeatureFlag`" pulumi-lang-yaml="`posthog.FeatureFlag`" pulumi-lang-java="`posthog.FeatureFlag`" pulumi-lang-hcl="`posthog_feature_flag`">`posthog.FeatureFlag`</span> resource, set `lifecycle {<span pulumi-lang-nodejs=" ignoreChanges " pulumi-lang-dotnet=" IgnoreChanges " pulumi-lang-go=" ignoreChanges " pulumi-lang-python=" ignore_changes " pulumi-lang-yaml=" ignoreChanges " pulumi-lang-java=" ignoreChanges " pulumi-lang-hcl=" ignore_changes "> ignoreChanges </span>= [filters] }` on it so it does not revert the shipped distribution. Config-only; re-ships only when this value changes; clearing it does not un-ship.
     */
    shipVariant?: pulumi.Input<string | undefined>;
}

export interface LogsAlertBlockedWindow {
    /**
     * End time as `HH:MM` (24-hour, project timezone). Exclusive.
     */
    end: pulumi.Input<string>;
    /**
     * Start time as `HH:MM` (24-hour, project timezone). Inclusive.
     */
    start: pulumi.Input<string>;
}

export interface ProjectSettingsSessionRecordingNetworkPayloadCaptureConfig {
    /**
     * Whether to record the bodies of network requests in session replay.
     */
    recordBody: pulumi.Input<boolean>;
    /**
     * Whether to record the headers of network requests in session replay.
     */
    recordHeaders: pulumi.Input<boolean>;
}
