// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AddonConfig extends pulumi.CustomResource {
    /**
     * Get an existing AddonConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AddonConfigState, opts?: pulumi.CustomResourceOptions): AddonConfig {
        return new AddonConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/addonConfig:AddonConfig';

    /**
     * Returns true if the given object is an instance of AddonConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AddonConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AddonConfig.__pulumiType;
    }

    declare public readonly addonConfigId: pulumi.Output<string>;
    /**
     * Catalog identifier of the addon whose stored configuration this resource owns, for example `portal-template`.
     */
    declare public readonly addonId: pulumi.Output<string>;
    /**
     * Configuration entries of the addon. The set is authoritative: an entry removed from the configuration is deleted from the addon.
     */
    declare public readonly entries: pulumi.Output<outputs.AddonConfigEntry[]>;

    /**
     * Create a AddonConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AddonConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AddonConfigArgs | AddonConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AddonConfigState | undefined;
            resourceInputs["addonConfigId"] = state?.addonConfigId;
            resourceInputs["addonId"] = state?.addonId;
            resourceInputs["entries"] = state?.entries;
        } else {
            const args = argsOrState as AddonConfigArgs | undefined;
            if (args?.addonId === undefined && !opts.urn) {
                throw new Error("Missing required property 'addonId'");
            }
            if (args?.entries === undefined && !opts.urn) {
                throw new Error("Missing required property 'entries'");
            }
            resourceInputs["addonConfigId"] = args?.addonConfigId;
            resourceInputs["addonId"] = args?.addonId;
            resourceInputs["entries"] = args?.entries;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AddonConfig.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AddonConfig resources.
 */
export interface AddonConfigState {
    addonConfigId?: pulumi.Input<string | undefined>;
    /**
     * Catalog identifier of the addon whose stored configuration this resource owns, for example `portal-template`.
     */
    addonId?: pulumi.Input<string | undefined>;
    /**
     * Configuration entries of the addon. The set is authoritative: an entry removed from the configuration is deleted from the addon.
     */
    entries?: pulumi.Input<pulumi.Input<inputs.AddonConfigEntry>[] | undefined>;
}

/**
 * The set of arguments for constructing a AddonConfig resource.
 */
export interface AddonConfigArgs {
    addonConfigId?: pulumi.Input<string | undefined>;
    /**
     * Catalog identifier of the addon whose stored configuration this resource owns, for example `portal-template`.
     */
    addonId: pulumi.Input<string>;
    /**
     * Configuration entries of the addon. The set is authoritative: an entry removed from the configuration is deleted from the addon.
     */
    entries: pulumi.Input<pulumi.Input<inputs.AddonConfigEntry>[]>;
}
