// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CustomTemplate extends pulumi.CustomResource {
    /**
     * Get an existing CustomTemplate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomTemplateState, opts?: pulumi.CustomResourceOptions): CustomTemplate {
        return new CustomTemplate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/customTemplate:CustomTemplate';

    /**
     * Returns true if the given object is an instance of CustomTemplate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomTemplate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomTemplate.__pulumiType;
    }

    /**
     * Path within the Git repository to the Compose or manifest file (defaults to `docker-compose.yml`).
     */
    declare public readonly composeFilePath: pulumi.Output<string | undefined>;
    declare public readonly customTemplateId: pulumi.Output<string>;
    /**
     * Short description of the custom template displayed in the Portainer UI.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Whether this template is exposed as an Edge template.
     */
    declare public readonly edgeTemplate: pulumi.Output<boolean | undefined>;
    /**
     * Inline template body (Compose YAML, Kubernetes manifest, or Swarm stack file). Mutually exclusive with <span pulumi-lang-nodejs="`filePath`" pulumi-lang-dotnet="`FilePath`" pulumi-lang-go="`filePath`" pulumi-lang-python="`file_path`" pulumi-lang-yaml="`filePath`" pulumi-lang-java="`filePath`" pulumi-lang-hcl="`file_path`">`filePath`</span> and the repository fields.
     */
    declare public readonly fileContent: pulumi.Output<string | undefined>;
    /**
     * Path on the local filesystem to a file containing the template body. Mutually exclusive with <span pulumi-lang-nodejs="`fileContent`" pulumi-lang-dotnet="`FileContent`" pulumi-lang-go="`fileContent`" pulumi-lang-python="`file_content`" pulumi-lang-yaml="`fileContent`" pulumi-lang-java="`fileContent`" pulumi-lang-hcl="`file_content`">`fileContent`</span> and the repository fields.
     */
    declare public readonly filePath: pulumi.Output<string | undefined>;
    /**
     * Whether the Kubernetes manifest is provided in Compose format (only relevant for `type = 3`).
     */
    declare public readonly isComposeFormat: pulumi.Output<boolean | undefined>;
    /**
     * URL of the logo image displayed next to the template in the Portainer UI.
     */
    declare public readonly logo: pulumi.Output<string | undefined>;
    /**
     * Additional note or instructions associated with the custom template.
     */
    declare public readonly note: pulumi.Output<string>;
    /**
     * Target platform for the template: 1 = Linux, 2 = Windows.
     */
    declare public readonly platform: pulumi.Output<number>;
    /**
     * Enable authentication for the Git repository (default: false).
     */
    declare public readonly repositoryAuthentication: pulumi.Output<boolean | undefined>;
    /**
     * Sensitive password or personal access token used to authenticate against the Git repository.
     */
    declare public readonly repositoryPassword: pulumi.Output<string | undefined>;
    /**
     * Git reference (branch, tag, or commit) to check out (defaults to `refs/heads/main`).
     */
    declare public readonly repositoryReference: pulumi.Output<string | undefined>;
    /**
     * URL of the Git repository hosting the template manifest.
     */
    declare public readonly repositoryUrl: pulumi.Output<string | undefined>;
    /**
     * Username used to authenticate against the Git repository.
     */
    declare public readonly repositoryUsername: pulumi.Output<string | undefined>;
    /**
     * Title of the Portainer custom template.
     */
    declare public readonly title: pulumi.Output<string>;
    /**
     * Whether to skip TLS verification when cloning the Git repository.
     */
    declare public readonly tlsskipVerify: pulumi.Output<boolean | undefined>;
    /**
     * Template type: 1 = Swarm stack, 2 = Compose stack, 3 = Kubernetes manifest.
     */
    declare public readonly type: pulumi.Output<number>;
    /**
     * List of template variable definitions (name, label, description, defaultValue) used for parameterized templates.
     */
    declare public readonly variables: pulumi.Output<{[key: string]: string}[] | undefined>;

    /**
     * Create a CustomTemplate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomTemplateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomTemplateArgs | CustomTemplateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomTemplateState | undefined;
            resourceInputs["composeFilePath"] = state?.composeFilePath;
            resourceInputs["customTemplateId"] = state?.customTemplateId;
            resourceInputs["description"] = state?.description;
            resourceInputs["edgeTemplate"] = state?.edgeTemplate;
            resourceInputs["fileContent"] = state?.fileContent;
            resourceInputs["filePath"] = state?.filePath;
            resourceInputs["isComposeFormat"] = state?.isComposeFormat;
            resourceInputs["logo"] = state?.logo;
            resourceInputs["note"] = state?.note;
            resourceInputs["platform"] = state?.platform;
            resourceInputs["repositoryAuthentication"] = state?.repositoryAuthentication;
            resourceInputs["repositoryPassword"] = state?.repositoryPassword;
            resourceInputs["repositoryReference"] = state?.repositoryReference;
            resourceInputs["repositoryUrl"] = state?.repositoryUrl;
            resourceInputs["repositoryUsername"] = state?.repositoryUsername;
            resourceInputs["title"] = state?.title;
            resourceInputs["tlsskipVerify"] = state?.tlsskipVerify;
            resourceInputs["type"] = state?.type;
            resourceInputs["variables"] = state?.variables;
        } else {
            const args = argsOrState as CustomTemplateArgs | undefined;
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if (args?.note === undefined && !opts.urn) {
                throw new Error("Missing required property 'note'");
            }
            if (args?.platform === undefined && !opts.urn) {
                throw new Error("Missing required property 'platform'");
            }
            if (args?.title === undefined && !opts.urn) {
                throw new Error("Missing required property 'title'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["composeFilePath"] = args?.composeFilePath;
            resourceInputs["customTemplateId"] = args?.customTemplateId;
            resourceInputs["description"] = args?.description;
            resourceInputs["edgeTemplate"] = args?.edgeTemplate;
            resourceInputs["fileContent"] = args?.fileContent;
            resourceInputs["filePath"] = args?.filePath;
            resourceInputs["isComposeFormat"] = args?.isComposeFormat;
            resourceInputs["logo"] = args?.logo;
            resourceInputs["note"] = args?.note;
            resourceInputs["platform"] = args?.platform;
            resourceInputs["repositoryAuthentication"] = args?.repositoryAuthentication;
            resourceInputs["repositoryPassword"] = args?.repositoryPassword ? pulumi.secret(args.repositoryPassword) : undefined;
            resourceInputs["repositoryReference"] = args?.repositoryReference;
            resourceInputs["repositoryUrl"] = args?.repositoryUrl;
            resourceInputs["repositoryUsername"] = args?.repositoryUsername;
            resourceInputs["title"] = args?.title;
            resourceInputs["tlsskipVerify"] = args?.tlsskipVerify;
            resourceInputs["type"] = args?.type;
            resourceInputs["variables"] = args?.variables;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["repositoryPassword"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(CustomTemplate.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering CustomTemplate resources.
 */
export interface CustomTemplateState {
    /**
     * Path within the Git repository to the Compose or manifest file (defaults to `docker-compose.yml`).
     */
    composeFilePath?: pulumi.Input<string | undefined>;
    customTemplateId?: pulumi.Input<string | undefined>;
    /**
     * Short description of the custom template displayed in the Portainer UI.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether this template is exposed as an Edge template.
     */
    edgeTemplate?: pulumi.Input<boolean | undefined>;
    /**
     * Inline template body (Compose YAML, Kubernetes manifest, or Swarm stack file). Mutually exclusive with <span pulumi-lang-nodejs="`filePath`" pulumi-lang-dotnet="`FilePath`" pulumi-lang-go="`filePath`" pulumi-lang-python="`file_path`" pulumi-lang-yaml="`filePath`" pulumi-lang-java="`filePath`" pulumi-lang-hcl="`file_path`">`filePath`</span> and the repository fields.
     */
    fileContent?: pulumi.Input<string | undefined>;
    /**
     * Path on the local filesystem to a file containing the template body. Mutually exclusive with <span pulumi-lang-nodejs="`fileContent`" pulumi-lang-dotnet="`FileContent`" pulumi-lang-go="`fileContent`" pulumi-lang-python="`file_content`" pulumi-lang-yaml="`fileContent`" pulumi-lang-java="`fileContent`" pulumi-lang-hcl="`file_content`">`fileContent`</span> and the repository fields.
     */
    filePath?: pulumi.Input<string | undefined>;
    /**
     * Whether the Kubernetes manifest is provided in Compose format (only relevant for `type = 3`).
     */
    isComposeFormat?: pulumi.Input<boolean | undefined>;
    /**
     * URL of the logo image displayed next to the template in the Portainer UI.
     */
    logo?: pulumi.Input<string | undefined>;
    /**
     * Additional note or instructions associated with the custom template.
     */
    note?: pulumi.Input<string | undefined>;
    /**
     * Target platform for the template: 1 = Linux, 2 = Windows.
     */
    platform?: pulumi.Input<number | undefined>;
    /**
     * Enable authentication for the Git repository (default: false).
     */
    repositoryAuthentication?: pulumi.Input<boolean | undefined>;
    /**
     * Sensitive password or personal access token used to authenticate against the Git repository.
     */
    repositoryPassword?: pulumi.Input<string | undefined>;
    /**
     * Git reference (branch, tag, or commit) to check out (defaults to `refs/heads/main`).
     */
    repositoryReference?: pulumi.Input<string | undefined>;
    /**
     * URL of the Git repository hosting the template manifest.
     */
    repositoryUrl?: pulumi.Input<string | undefined>;
    /**
     * Username used to authenticate against the Git repository.
     */
    repositoryUsername?: pulumi.Input<string | undefined>;
    /**
     * Title of the Portainer custom template.
     */
    title?: pulumi.Input<string | undefined>;
    /**
     * Whether to skip TLS verification when cloning the Git repository.
     */
    tlsskipVerify?: pulumi.Input<boolean | undefined>;
    /**
     * Template type: 1 = Swarm stack, 2 = Compose stack, 3 = Kubernetes manifest.
     */
    type?: pulumi.Input<number | undefined>;
    /**
     * List of template variable definitions (name, label, description, defaultValue) used for parameterized templates.
     */
    variables?: pulumi.Input<pulumi.Input<{[key: string]: pulumi.Input<string>}>[] | undefined>;
}

/**
 * The set of arguments for constructing a CustomTemplate resource.
 */
export interface CustomTemplateArgs {
    /**
     * Path within the Git repository to the Compose or manifest file (defaults to `docker-compose.yml`).
     */
    composeFilePath?: pulumi.Input<string | undefined>;
    customTemplateId?: pulumi.Input<string | undefined>;
    /**
     * Short description of the custom template displayed in the Portainer UI.
     */
    description: pulumi.Input<string>;
    /**
     * Whether this template is exposed as an Edge template.
     */
    edgeTemplate?: pulumi.Input<boolean | undefined>;
    /**
     * Inline template body (Compose YAML, Kubernetes manifest, or Swarm stack file). Mutually exclusive with <span pulumi-lang-nodejs="`filePath`" pulumi-lang-dotnet="`FilePath`" pulumi-lang-go="`filePath`" pulumi-lang-python="`file_path`" pulumi-lang-yaml="`filePath`" pulumi-lang-java="`filePath`" pulumi-lang-hcl="`file_path`">`filePath`</span> and the repository fields.
     */
    fileContent?: pulumi.Input<string | undefined>;
    /**
     * Path on the local filesystem to a file containing the template body. Mutually exclusive with <span pulumi-lang-nodejs="`fileContent`" pulumi-lang-dotnet="`FileContent`" pulumi-lang-go="`fileContent`" pulumi-lang-python="`file_content`" pulumi-lang-yaml="`fileContent`" pulumi-lang-java="`fileContent`" pulumi-lang-hcl="`file_content`">`fileContent`</span> and the repository fields.
     */
    filePath?: pulumi.Input<string | undefined>;
    /**
     * Whether the Kubernetes manifest is provided in Compose format (only relevant for `type = 3`).
     */
    isComposeFormat?: pulumi.Input<boolean | undefined>;
    /**
     * URL of the logo image displayed next to the template in the Portainer UI.
     */
    logo?: pulumi.Input<string | undefined>;
    /**
     * Additional note or instructions associated with the custom template.
     */
    note: pulumi.Input<string>;
    /**
     * Target platform for the template: 1 = Linux, 2 = Windows.
     */
    platform: pulumi.Input<number>;
    /**
     * Enable authentication for the Git repository (default: false).
     */
    repositoryAuthentication?: pulumi.Input<boolean | undefined>;
    /**
     * Sensitive password or personal access token used to authenticate against the Git repository.
     */
    repositoryPassword?: pulumi.Input<string | undefined>;
    /**
     * Git reference (branch, tag, or commit) to check out (defaults to `refs/heads/main`).
     */
    repositoryReference?: pulumi.Input<string | undefined>;
    /**
     * URL of the Git repository hosting the template manifest.
     */
    repositoryUrl?: pulumi.Input<string | undefined>;
    /**
     * Username used to authenticate against the Git repository.
     */
    repositoryUsername?: pulumi.Input<string | undefined>;
    /**
     * Title of the Portainer custom template.
     */
    title: pulumi.Input<string>;
    /**
     * Whether to skip TLS verification when cloning the Git repository.
     */
    tlsskipVerify?: pulumi.Input<boolean | undefined>;
    /**
     * Template type: 1 = Swarm stack, 2 = Compose stack, 3 = Kubernetes manifest.
     */
    type: pulumi.Input<number>;
    /**
     * List of template variable definitions (name, label, description, defaultValue) used for parameterized templates.
     */
    variables?: pulumi.Input<pulumi.Input<{[key: string]: pulumi.Input<string>}>[] | undefined>;
}
