// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DockerImage extends pulumi.CustomResource {
    /**
     * Get an existing DockerImage resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DockerImageState, opts?: pulumi.CustomResourceOptions): DockerImage {
        return new DockerImage(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/dockerImage:DockerImage';

    /**
     * Returns true if the given object is an instance of DockerImage.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DockerImage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DockerImage.__pulumiType;
    }

    declare public readonly dockerImageId: pulumi.Output<string>;
    declare public readonly endpointId: pulumi.Output<number>;
    declare public readonly image: pulumi.Output<string>;
    declare public readonly registryAuth: pulumi.Output<string | undefined>;

    /**
     * Create a DockerImage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DockerImageArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DockerImageArgs | DockerImageState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DockerImageState | undefined;
            resourceInputs["dockerImageId"] = state?.dockerImageId;
            resourceInputs["endpointId"] = state?.endpointId;
            resourceInputs["image"] = state?.image;
            resourceInputs["registryAuth"] = state?.registryAuth;
        } else {
            const args = argsOrState as DockerImageArgs | undefined;
            if (args?.endpointId === undefined && !opts.urn) {
                throw new Error("Missing required property 'endpointId'");
            }
            if (args?.image === undefined && !opts.urn) {
                throw new Error("Missing required property 'image'");
            }
            resourceInputs["dockerImageId"] = args?.dockerImageId;
            resourceInputs["endpointId"] = args?.endpointId;
            resourceInputs["image"] = args?.image;
            resourceInputs["registryAuth"] = args?.registryAuth ? pulumi.secret(args.registryAuth) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["registryAuth"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(DockerImage.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DockerImage resources.
 */
export interface DockerImageState {
    dockerImageId?: pulumi.Input<string>;
    endpointId?: pulumi.Input<number>;
    image?: pulumi.Input<string>;
    registryAuth?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DockerImage resource.
 */
export interface DockerImageArgs {
    dockerImageId?: pulumi.Input<string>;
    endpointId: pulumi.Input<number>;
    image: pulumi.Input<string>;
    registryAuth?: pulumi.Input<string>;
}
