// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EndpointServiceUpdate extends pulumi.CustomResource {
    /**
     * Get an existing EndpointServiceUpdate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EndpointServiceUpdateState, opts?: pulumi.CustomResourceOptions): EndpointServiceUpdate {
        return new EndpointServiceUpdate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/endpointServiceUpdate:EndpointServiceUpdate';

    /**
     * Returns true if the given object is an instance of EndpointServiceUpdate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EndpointServiceUpdate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EndpointServiceUpdate.__pulumiType;
    }

    declare public readonly endpointId: pulumi.Output<number>;
    declare public readonly endpointServiceUpdateId: pulumi.Output<string>;
    declare public readonly pullImage: pulumi.Output<boolean | undefined>;
    declare public readonly serviceName: pulumi.Output<string>;

    /**
     * Create a EndpointServiceUpdate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EndpointServiceUpdateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EndpointServiceUpdateArgs | EndpointServiceUpdateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EndpointServiceUpdateState | undefined;
            resourceInputs["endpointId"] = state?.endpointId;
            resourceInputs["endpointServiceUpdateId"] = state?.endpointServiceUpdateId;
            resourceInputs["pullImage"] = state?.pullImage;
            resourceInputs["serviceName"] = state?.serviceName;
        } else {
            const args = argsOrState as EndpointServiceUpdateArgs | undefined;
            if (args?.endpointId === undefined && !opts.urn) {
                throw new Error("Missing required property 'endpointId'");
            }
            if (args?.serviceName === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceName'");
            }
            resourceInputs["endpointId"] = args?.endpointId;
            resourceInputs["endpointServiceUpdateId"] = args?.endpointServiceUpdateId;
            resourceInputs["pullImage"] = args?.pullImage;
            resourceInputs["serviceName"] = args?.serviceName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EndpointServiceUpdate.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EndpointServiceUpdate resources.
 */
export interface EndpointServiceUpdateState {
    endpointId?: pulumi.Input<number>;
    endpointServiceUpdateId?: pulumi.Input<string>;
    pullImage?: pulumi.Input<boolean>;
    serviceName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a EndpointServiceUpdate resource.
 */
export interface EndpointServiceUpdateArgs {
    endpointId: pulumi.Input<number>;
    endpointServiceUpdateId?: pulumi.Input<string>;
    pullImage?: pulumi.Input<boolean>;
    serviceName: pulumi.Input<string>;
}
