// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EndpointGroupMembership extends pulumi.CustomResource {
    /**
     * Get an existing EndpointGroupMembership resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EndpointGroupMembershipState, opts?: pulumi.CustomResourceOptions): EndpointGroupMembership {
        return new EndpointGroupMembership(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/endpointGroupMembership:EndpointGroupMembership';

    /**
     * Returns true if the given object is an instance of EndpointGroupMembership.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EndpointGroupMembership {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EndpointGroupMembership.__pulumiType;
    }

    /**
     * Identifier of the environment group the environment is added to.
     */
    declare public readonly endpointGroupId: pulumi.Output<number>;
    declare public readonly endpointGroupMembershipId: pulumi.Output<string>;
    /**
     * Identifier of the environment to place in the group.
     */
    declare public readonly endpointId: pulumi.Output<number>;

    /**
     * Create a EndpointGroupMembership resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EndpointGroupMembershipArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EndpointGroupMembershipArgs | EndpointGroupMembershipState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EndpointGroupMembershipState | undefined;
            resourceInputs["endpointGroupId"] = state?.endpointGroupId;
            resourceInputs["endpointGroupMembershipId"] = state?.endpointGroupMembershipId;
            resourceInputs["endpointId"] = state?.endpointId;
        } else {
            const args = argsOrState as EndpointGroupMembershipArgs | undefined;
            if (args?.endpointGroupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'endpointGroupId'");
            }
            if (args?.endpointId === undefined && !opts.urn) {
                throw new Error("Missing required property 'endpointId'");
            }
            resourceInputs["endpointGroupId"] = args?.endpointGroupId;
            resourceInputs["endpointGroupMembershipId"] = args?.endpointGroupMembershipId;
            resourceInputs["endpointId"] = args?.endpointId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EndpointGroupMembership.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EndpointGroupMembership resources.
 */
export interface EndpointGroupMembershipState {
    /**
     * Identifier of the environment group the environment is added to.
     */
    endpointGroupId?: pulumi.Input<number | undefined>;
    endpointGroupMembershipId?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the environment to place in the group.
     */
    endpointId?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a EndpointGroupMembership resource.
 */
export interface EndpointGroupMembershipArgs {
    /**
     * Identifier of the environment group the environment is added to.
     */
    endpointGroupId: pulumi.Input<number>;
    endpointGroupMembershipId?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the environment to place in the group.
     */
    endpointId: pulumi.Input<number>;
}
