// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDockerSnapshot(args: GetDockerSnapshotArgs, opts?: pulumi.InvokeOptions): Promise<GetDockerSnapshotResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getDockerSnapshot:getDockerSnapshot", {
        "endpointId": args.endpointId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDockerSnapshot.
 */
export interface GetDockerSnapshotArgs {
    endpointId: number;
    id?: string;
}

/**
 * A collection of values returned by getDockerSnapshot.
 */
export interface GetDockerSnapshotResult {
    readonly endpointId: number;
    readonly id: string;
    readonly snapshot: string;
}
export function getDockerSnapshotOutput(args: GetDockerSnapshotOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDockerSnapshotResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getDockerSnapshot:getDockerSnapshot", {
        "endpointId": args.endpointId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDockerSnapshot.
 */
export interface GetDockerSnapshotOutputArgs {
    endpointId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
}
