// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDockerSnapshotContainer(args: GetDockerSnapshotContainerArgs, opts?: pulumi.InvokeOptions): Promise<GetDockerSnapshotContainerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getDockerSnapshotContainer:getDockerSnapshotContainer", {
        "containerId": args.containerId,
        "endpointId": args.endpointId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDockerSnapshotContainer.
 */
export interface GetDockerSnapshotContainerArgs {
    containerId: string;
    endpointId: number;
    id?: string;
}

/**
 * A collection of values returned by getDockerSnapshotContainer.
 */
export interface GetDockerSnapshotContainerResult {
    readonly command: string;
    readonly containerId: string;
    readonly created: number;
    readonly details: string;
    readonly endpointId: number;
    readonly id: string;
    readonly image: string;
    readonly imageId: string;
    readonly labels: {[key: string]: string};
    readonly names: string[];
    readonly state: string;
    readonly status: string;
}
export function getDockerSnapshotContainerOutput(args: GetDockerSnapshotContainerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDockerSnapshotContainerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getDockerSnapshotContainer:getDockerSnapshotContainer", {
        "containerId": args.containerId,
        "endpointId": args.endpointId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDockerSnapshotContainer.
 */
export interface GetDockerSnapshotContainerOutputArgs {
    containerId: pulumi.Input<string>;
    endpointId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
}
