// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getEndpointsSummary(args?: GetEndpointsSummaryArgs, opts?: pulumi.InvokeOptions): Promise<GetEndpointsSummaryResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getEndpointsSummary:getEndpointsSummary", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEndpointsSummary.
 */
export interface GetEndpointsSummaryArgs {
    id?: string;
}

/**
 * A collection of values returned by getEndpointsSummary.
 */
export interface GetEndpointsSummaryResult {
    readonly azure: number;
    readonly byGroups: outputs.GetEndpointsSummaryByGroup[];
    readonly docker: number;
    readonly down: number;
    readonly heartbeat: number;
    readonly id: string;
    readonly kubernetes: number;
    readonly outdated: number;
    readonly podman: number;
    readonly total: number;
    readonly unassigned: number;
    readonly up: number;
}
export function getEndpointsSummaryOutput(args?: GetEndpointsSummaryOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEndpointsSummaryResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getEndpointsSummary:getEndpointsSummary", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEndpointsSummary.
 */
export interface GetEndpointsSummaryOutputArgs {
    id?: pulumi.Input<string | undefined>;
}
