// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getEdgeJobTasks(args: GetEdgeJobTasksArgs, opts?: pulumi.InvokeOptions): Promise<GetEdgeJobTasksResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getEdgeJobTasks:getEdgeJobTasks", {
        "edgeJobId": args.edgeJobId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEdgeJobTasks.
 */
export interface GetEdgeJobTasksArgs {
    edgeJobId: number;
    id?: string;
}

/**
 * A collection of values returned by getEdgeJobTasks.
 */
export interface GetEdgeJobTasksResult {
    readonly edgeJobId: number;
    readonly id: string;
    readonly tasks: outputs.GetEdgeJobTasksTask[];
}
export function getEdgeJobTasksOutput(args: GetEdgeJobTasksOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEdgeJobTasksResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getEdgeJobTasks:getEdgeJobTasks", {
        "edgeJobId": args.edgeJobId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getEdgeJobTasks.
 */
export interface GetEdgeJobTasksOutputArgs {
    edgeJobId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
}
