// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getGitopsSourceConnection(args?: GetGitopsSourceConnectionArgs, opts?: pulumi.InvokeOptions): Promise<GetGitopsSourceConnectionResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getGitopsSourceConnection:getGitopsSourceConnection", {
        "failOnError": args.failOnError,
        "id": args.id,
        "password": args.password,
        "sourceId": args.sourceId,
        "tlsSkipVerify": args.tlsSkipVerify,
        "url": args.url,
        "username": args.username,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGitopsSourceConnection.
 */
export interface GetGitopsSourceConnectionArgs {
    failOnError?: boolean;
    id?: string;
    password?: string;
    sourceId?: number;
    tlsSkipVerify?: boolean;
    url?: string;
    username?: string;
}

/**
 * A collection of values returned by getGitopsSourceConnection.
 */
export interface GetGitopsSourceConnectionResult {
    readonly error: string;
    readonly failOnError?: boolean;
    readonly id: string;
    readonly password?: string;
    readonly sourceId?: number;
    readonly success: boolean;
    readonly tlsSkipVerify?: boolean;
    readonly url?: string;
    readonly username?: string;
}
export function getGitopsSourceConnectionOutput(args?: GetGitopsSourceConnectionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGitopsSourceConnectionResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getGitopsSourceConnection:getGitopsSourceConnection", {
        "failOnError": args.failOnError,
        "id": args.id,
        "password": args.password,
        "sourceId": args.sourceId,
        "tlsSkipVerify": args.tlsSkipVerify,
        "url": args.url,
        "username": args.username,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGitopsSourceConnection.
 */
export interface GetGitopsSourceConnectionOutputArgs {
    failOnError?: pulumi.Input<boolean | undefined>;
    id?: pulumi.Input<string | undefined>;
    password?: pulumi.Input<string | undefined>;
    sourceId?: pulumi.Input<number | undefined>;
    tlsSkipVerify?: pulumi.Input<boolean | undefined>;
    url?: pulumi.Input<string | undefined>;
    username?: pulumi.Input<string | undefined>;
}
