// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getGitopsRepoFile(args: GetGitopsRepoFileArgs, opts?: pulumi.InvokeOptions): Promise<GetGitopsRepoFileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getGitopsRepoFile:getGitopsRepoFile", {
        "gitCredentialId": args.gitCredentialId,
        "id": args.id,
        "password": args.password,
        "reference": args.reference,
        "repositoryUrl": args.repositoryUrl,
        "targetFile": args.targetFile,
        "tlsSkipVerify": args.tlsSkipVerify,
        "username": args.username,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGitopsRepoFile.
 */
export interface GetGitopsRepoFileArgs {
    gitCredentialId?: number;
    id?: string;
    password?: string;
    reference?: string;
    repositoryUrl: string;
    targetFile?: string;
    tlsSkipVerify?: boolean;
    username?: string;
}

/**
 * A collection of values returned by getGitopsRepoFile.
 */
export interface GetGitopsRepoFileResult {
    readonly fileContent: string;
    readonly gitCredentialId?: number;
    readonly id: string;
    readonly password?: string;
    readonly reference?: string;
    readonly repositoryUrl: string;
    readonly targetFile?: string;
    readonly tlsSkipVerify?: boolean;
    readonly username?: string;
}
export function getGitopsRepoFileOutput(args: GetGitopsRepoFileOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGitopsRepoFileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getGitopsRepoFile:getGitopsRepoFile", {
        "gitCredentialId": args.gitCredentialId,
        "id": args.id,
        "password": args.password,
        "reference": args.reference,
        "repositoryUrl": args.repositoryUrl,
        "targetFile": args.targetFile,
        "tlsSkipVerify": args.tlsSkipVerify,
        "username": args.username,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGitopsRepoFile.
 */
export interface GetGitopsRepoFileOutputArgs {
    gitCredentialId?: pulumi.Input<number>;
    id?: pulumi.Input<string>;
    password?: pulumi.Input<string>;
    reference?: pulumi.Input<string>;
    repositoryUrl: pulumi.Input<string>;
    targetFile?: pulumi.Input<string>;
    tlsSkipVerify?: pulumi.Input<boolean>;
    username?: pulumi.Input<string>;
}
