// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getHelmGitDryrun(args: GetHelmGitDryrunArgs, opts?: pulumi.InvokeOptions): Promise<GetHelmGitDryrunResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getHelmGitDryrun:getHelmGitDryrun", {
        "chartPath": args.chartPath,
        "endpointId": args.endpointId,
        "id": args.id,
        "namespace": args.namespace,
        "referenceName": args.referenceName,
        "releaseName": args.releaseName,
        "repositoryAuthentication": args.repositoryAuthentication,
        "repositoryGitCredentialId": args.repositoryGitCredentialId,
        "repositoryPassword": args.repositoryPassword,
        "repositoryUrl": args.repositoryUrl,
        "repositoryUsername": args.repositoryUsername,
        "tlsSkipVerify": args.tlsSkipVerify,
        "valuesFiles": args.valuesFiles,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getHelmGitDryrun.
 */
export interface GetHelmGitDryrunArgs {
    chartPath?: string;
    endpointId: number;
    id?: string;
    namespace?: string;
    referenceName?: string;
    releaseName?: string;
    repositoryAuthentication?: boolean;
    repositoryGitCredentialId?: number;
    repositoryPassword?: string;
    repositoryUrl: string;
    repositoryUsername?: string;
    tlsSkipVerify?: boolean;
    valuesFiles?: string[];
}

/**
 * A collection of values returned by getHelmGitDryrun.
 */
export interface GetHelmGitDryrunResult {
    readonly chartPath?: string;
    readonly endpointId: number;
    readonly id: string;
    readonly manifest: string;
    readonly namespace?: string;
    readonly referenceName?: string;
    readonly releaseName?: string;
    readonly releaseVersion: number;
    readonly repositoryAuthentication?: boolean;
    readonly repositoryGitCredentialId?: number;
    readonly repositoryPassword?: string;
    readonly repositoryUrl: string;
    readonly repositoryUsername?: string;
    readonly tlsSkipVerify?: boolean;
    readonly valuesFiles?: string[];
}
export function getHelmGitDryrunOutput(args: GetHelmGitDryrunOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetHelmGitDryrunResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getHelmGitDryrun:getHelmGitDryrun", {
        "chartPath": args.chartPath,
        "endpointId": args.endpointId,
        "id": args.id,
        "namespace": args.namespace,
        "referenceName": args.referenceName,
        "releaseName": args.releaseName,
        "repositoryAuthentication": args.repositoryAuthentication,
        "repositoryGitCredentialId": args.repositoryGitCredentialId,
        "repositoryPassword": args.repositoryPassword,
        "repositoryUrl": args.repositoryUrl,
        "repositoryUsername": args.repositoryUsername,
        "tlsSkipVerify": args.tlsSkipVerify,
        "valuesFiles": args.valuesFiles,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getHelmGitDryrun.
 */
export interface GetHelmGitDryrunOutputArgs {
    chartPath?: pulumi.Input<string>;
    endpointId: pulumi.Input<number>;
    id?: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
    referenceName?: pulumi.Input<string>;
    releaseName?: pulumi.Input<string>;
    repositoryAuthentication?: pulumi.Input<boolean>;
    repositoryGitCredentialId?: pulumi.Input<number>;
    repositoryPassword?: pulumi.Input<string>;
    repositoryUrl: pulumi.Input<string>;
    repositoryUsername?: pulumi.Input<string>;
    tlsSkipVerify?: pulumi.Input<boolean>;
    valuesFiles?: pulumi.Input<pulumi.Input<string>[]>;
}
