// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getImageStatus(args: GetImageStatusArgs, opts?: pulumi.InvokeOptions): Promise<GetImageStatusResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getImageStatus:getImageStatus", {
        "endpointId": args.endpointId,
        "id": args.id,
        "kind": args.kind,
        "refresh": args.refresh,
        "resourceId": args.resourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getImageStatus.
 */
export interface GetImageStatusArgs {
    endpointId?: number;
    id?: string;
    kind: string;
    refresh?: boolean;
    resourceId: string;
}

/**
 * A collection of values returned by getImageStatus.
 */
export interface GetImageStatusResult {
    readonly endpointId?: number;
    readonly id: string;
    readonly kind: string;
    readonly message: string;
    readonly refresh?: boolean;
    readonly resourceId: string;
    readonly status: string;
}
export function getImageStatusOutput(args: GetImageStatusOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetImageStatusResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getImageStatus:getImageStatus", {
        "endpointId": args.endpointId,
        "id": args.id,
        "kind": args.kind,
        "refresh": args.refresh,
        "resourceId": args.resourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getImageStatus.
 */
export interface GetImageStatusOutputArgs {
    endpointId?: pulumi.Input<number | undefined>;
    id?: pulumi.Input<string | undefined>;
    kind: pulumi.Input<string>;
    refresh?: pulumi.Input<boolean | undefined>;
    resourceId: pulumi.Input<string>;
}
