// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getKubernetesEndpoints(args: GetKubernetesEndpointsArgs, opts?: pulumi.InvokeOptions): Promise<GetKubernetesEndpointsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getKubernetesEndpoints:getKubernetesEndpoints", {
        "endpointId": args.endpointId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKubernetesEndpoints.
 */
export interface GetKubernetesEndpointsArgs {
    endpointId: number;
    id?: string;
}

/**
 * A collection of values returned by getKubernetesEndpoints.
 */
export interface GetKubernetesEndpointsResult {
    readonly endpointId: number;
    readonly endpoints: outputs.GetKubernetesEndpointsEndpoint[];
    readonly id: string;
}
export function getKubernetesEndpointsOutput(args: GetKubernetesEndpointsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKubernetesEndpointsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getKubernetesEndpoints:getKubernetesEndpoints", {
        "endpointId": args.endpointId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKubernetesEndpoints.
 */
export interface GetKubernetesEndpointsOutputArgs {
    endpointId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
}
