// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getKubernetesStorageClass(args: GetKubernetesStorageClassArgs, opts?: pulumi.InvokeOptions): Promise<GetKubernetesStorageClassResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getKubernetesStorageClass:getKubernetesStorageClass", {
        "endpointId": args.endpointId,
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKubernetesStorageClass.
 */
export interface GetKubernetesStorageClassArgs {
    endpointId: number;
    id?: string;
    name: string;
}

/**
 * A collection of values returned by getKubernetesStorageClass.
 */
export interface GetKubernetesStorageClassResult {
    readonly allowVolumeExpansion: boolean;
    readonly annotations: {[key: string]: string};
    readonly creationDate: string;
    readonly endpointId: number;
    readonly id: string;
    readonly isDefault: boolean;
    readonly labels: {[key: string]: string};
    readonly mountOptions: string[];
    readonly name: string;
    readonly parameters: {[key: string]: string};
    readonly provisionerName: string;
    readonly reclaimPolicy: string;
}
export function getKubernetesStorageClassOutput(args: GetKubernetesStorageClassOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKubernetesStorageClassResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getKubernetesStorageClass:getKubernetesStorageClass", {
        "endpointId": args.endpointId,
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKubernetesStorageClass.
 */
export interface GetKubernetesStorageClassOutputArgs {
    endpointId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
    name: pulumi.Input<string>;
}
