// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getKubernetesServiceAccount(args: GetKubernetesServiceAccountArgs, opts?: pulumi.InvokeOptions): Promise<GetKubernetesServiceAccountResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getKubernetesServiceAccount:getKubernetesServiceAccount", {
        "endpointId": args.endpointId,
        "id": args.id,
        "name": args.name,
        "namespace": args.namespace,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKubernetesServiceAccount.
 */
export interface GetKubernetesServiceAccountArgs {
    endpointId: number;
    id?: string;
    name: string;
    namespace: string;
}

/**
 * A collection of values returned by getKubernetesServiceAccount.
 */
export interface GetKubernetesServiceAccountResult {
    readonly annotations: {[key: string]: string};
    readonly automountServiceAccountToken: boolean;
    readonly creationDate: string;
    readonly endpointId: number;
    readonly id: string;
    readonly imagePullSecrets: string[];
    readonly isSystem: boolean;
    readonly labels: {[key: string]: string};
    readonly name: string;
    readonly namespace: string;
    readonly uid: string;
}
export function getKubernetesServiceAccountOutput(args: GetKubernetesServiceAccountOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKubernetesServiceAccountResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getKubernetesServiceAccount:getKubernetesServiceAccount", {
        "endpointId": args.endpointId,
        "id": args.id,
        "name": args.name,
        "namespace": args.namespace,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKubernetesServiceAccount.
 */
export interface GetKubernetesServiceAccountOutputArgs {
    endpointId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
    name: pulumi.Input<string>;
    namespace: pulumi.Input<string>;
}
