// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getKubernetesApplicationResources(args: GetKubernetesApplicationResourcesArgs, opts?: pulumi.InvokeOptions): Promise<GetKubernetesApplicationResourcesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getKubernetesApplicationResources:getKubernetesApplicationResources", {
        "environmentId": args.environmentId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKubernetesApplicationResources.
 */
export interface GetKubernetesApplicationResourcesArgs {
    environmentId: number;
    id?: string;
}

/**
 * A collection of values returned by getKubernetesApplicationResources.
 */
export interface GetKubernetesApplicationResourcesResult {
    readonly cpuLimit: number;
    readonly cpuRequest: number;
    readonly environmentId: number;
    readonly id: string;
    readonly memoryLimit: number;
    readonly memoryRequest: number;
}
export function getKubernetesApplicationResourcesOutput(args: GetKubernetesApplicationResourcesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKubernetesApplicationResourcesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getKubernetesApplicationResources:getKubernetesApplicationResources", {
        "environmentId": args.environmentId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getKubernetesApplicationResources.
 */
export interface GetKubernetesApplicationResourcesOutputArgs {
    environmentId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
}
