// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getLdapCheck(args: GetLdapCheckArgs, opts?: pulumi.InvokeOptions): Promise<GetLdapCheckResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getLdapCheck:getLdapCheck", {
        "anonymousMode": args.anonymousMode,
        "failOnError": args.failOnError,
        "id": args.id,
        "password": args.password,
        "readerDn": args.readerDn,
        "startTls": args.startTls,
        "tlsSkipVerify": args.tlsSkipVerify,
        "url": args.url,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getLdapCheck.
 */
export interface GetLdapCheckArgs {
    anonymousMode?: boolean;
    failOnError?: boolean;
    id?: string;
    password?: string;
    readerDn?: string;
    startTls?: boolean;
    tlsSkipVerify?: boolean;
    url: string;
}

/**
 * A collection of values returned by getLdapCheck.
 */
export interface GetLdapCheckResult {
    readonly anonymousMode?: boolean;
    readonly error: string;
    readonly failOnError?: boolean;
    readonly id: string;
    readonly password?: string;
    readonly readerDn?: string;
    readonly startTls?: boolean;
    readonly success: boolean;
    readonly tlsSkipVerify?: boolean;
    readonly url: string;
}
export function getLdapCheckOutput(args: GetLdapCheckOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLdapCheckResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getLdapCheck:getLdapCheck", {
        "anonymousMode": args.anonymousMode,
        "failOnError": args.failOnError,
        "id": args.id,
        "password": args.password,
        "readerDn": args.readerDn,
        "startTls": args.startTls,
        "tlsSkipVerify": args.tlsSkipVerify,
        "url": args.url,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getLdapCheck.
 */
export interface GetLdapCheckOutputArgs {
    anonymousMode?: pulumi.Input<boolean | undefined>;
    failOnError?: pulumi.Input<boolean | undefined>;
    id?: pulumi.Input<string | undefined>;
    password?: pulumi.Input<string | undefined>;
    readerDn?: pulumi.Input<string | undefined>;
    startTls?: pulumi.Input<boolean | undefined>;
    tlsSkipVerify?: pulumi.Input<boolean | undefined>;
    url: pulumi.Input<string>;
}
