// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getLdapAdminGroups(args: GetLdapAdminGroupsArgs, opts?: pulumi.InvokeOptions): Promise<GetLdapAdminGroupsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getLdapAdminGroups:getLdapAdminGroups", {
        "adminGroupSearches": args.adminGroupSearches,
        "anonymousMode": args.anonymousMode,
        "id": args.id,
        "password": args.password,
        "readerDn": args.readerDn,
        "startTls": args.startTls,
        "tlsSkipVerify": args.tlsSkipVerify,
        "url": args.url,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getLdapAdminGroups.
 */
export interface GetLdapAdminGroupsArgs {
    adminGroupSearches?: inputs.GetLdapAdminGroupsAdminGroupSearch[];
    anonymousMode?: boolean;
    id?: string;
    password?: string;
    readerDn?: string;
    startTls?: boolean;
    tlsSkipVerify?: boolean;
    url: string;
}

/**
 * A collection of values returned by getLdapAdminGroups.
 */
export interface GetLdapAdminGroupsResult {
    readonly adminGroupSearches?: outputs.GetLdapAdminGroupsAdminGroupSearch[];
    readonly anonymousMode?: boolean;
    readonly groupNames: string[];
    readonly id: string;
    readonly password?: string;
    readonly readerDn?: string;
    readonly startTls?: boolean;
    readonly tlsSkipVerify?: boolean;
    readonly url: string;
}
export function getLdapAdminGroupsOutput(args: GetLdapAdminGroupsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLdapAdminGroupsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getLdapAdminGroups:getLdapAdminGroups", {
        "adminGroupSearches": args.adminGroupSearches,
        "anonymousMode": args.anonymousMode,
        "id": args.id,
        "password": args.password,
        "readerDn": args.readerDn,
        "startTls": args.startTls,
        "tlsSkipVerify": args.tlsSkipVerify,
        "url": args.url,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getLdapAdminGroups.
 */
export interface GetLdapAdminGroupsOutputArgs {
    adminGroupSearches?: pulumi.Input<pulumi.Input<inputs.GetLdapAdminGroupsAdminGroupSearchArgs>[] | undefined>;
    anonymousMode?: pulumi.Input<boolean | undefined>;
    id?: pulumi.Input<string | undefined>;
    password?: pulumi.Input<string | undefined>;
    readerDn?: pulumi.Input<string | undefined>;
    startTls?: pulumi.Input<boolean | undefined>;
    tlsSkipVerify?: pulumi.Input<boolean | undefined>;
    url: pulumi.Input<string>;
}
