// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getMotd(args?: GetMotdArgs, opts?: pulumi.InvokeOptions): Promise<GetMotdResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getMotd:getMotd", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getMotd.
 */
export interface GetMotdArgs {
    id?: string;
}

/**
 * A collection of values returned by getMotd.
 */
export interface GetMotdResult {
    readonly hash: string;
    readonly id: string;
    readonly message: string;
    readonly style: string;
    readonly title: string;
}
export function getMotdOutput(args?: GetMotdOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMotdResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getMotd:getMotd", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getMotd.
 */
export interface GetMotdOutputArgs {
    id?: pulumi.Input<string | undefined>;
}
