// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOmniUpgradeStatus(args: GetOmniUpgradeStatusArgs, opts?: pulumi.InvokeOptions): Promise<GetOmniUpgradeStatusResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getOmniUpgradeStatus:getOmniUpgradeStatus", {
        "cluster": args.cluster,
        "component": args.component,
        "credentialId": args.credentialId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOmniUpgradeStatus.
 */
export interface GetOmniUpgradeStatusArgs {
    cluster: string;
    component: string;
    credentialId: number;
    id?: string;
}

/**
 * A collection of values returned by getOmniUpgradeStatus.
 */
export interface GetOmniUpgradeStatusResult {
    readonly availableVersions: string[];
    readonly cluster: string;
    readonly component: string;
    readonly credentialId: number;
    readonly currentVersion: string;
    readonly error: string;
    readonly id: string;
    readonly lastVersion: string;
    readonly phase: number;
    readonly status: string;
    readonly step: string;
}
export function getOmniUpgradeStatusOutput(args: GetOmniUpgradeStatusOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOmniUpgradeStatusResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getOmniUpgradeStatus:getOmniUpgradeStatus", {
        "cluster": args.cluster,
        "component": args.component,
        "credentialId": args.credentialId,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOmniUpgradeStatus.
 */
export interface GetOmniUpgradeStatusOutputArgs {
    cluster: pulumi.Input<string>;
    component: pulumi.Input<string>;
    credentialId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
}
