// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getOmniMachine(args: GetOmniMachineArgs, opts?: pulumi.InvokeOptions): Promise<GetOmniMachineResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getOmniMachine:getOmniMachine", {
        "credentialId": args.credentialId,
        "id": args.id,
        "machineName": args.machineName,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOmniMachine.
 */
export interface GetOmniMachineArgs {
    credentialId: number;
    id?: string;
    machineName: string;
}

/**
 * A collection of values returned by getOmniMachine.
 */
export interface GetOmniMachineResult {
    readonly addresses: string[];
    readonly architecture: string;
    readonly blockDevices: outputs.GetOmniMachineBlockDevice[];
    readonly cluster: string;
    readonly connected: boolean;
    readonly credentialId: number;
    readonly defaultGateways: string[];
    readonly domainName: string;
    readonly hostname: string;
    readonly id: string;
    readonly instanceId: string;
    readonly instanceType: string;
    readonly labels: {[key: string]: string};
    readonly lastError: string;
    readonly machineName: string;
    readonly maintenance: boolean;
    readonly managementAddress: string;
    readonly memoryModules: outputs.GetOmniMachineMemoryModule[];
    readonly networkLinks: outputs.GetOmniMachineNetworkLink[];
    readonly platform: string;
    readonly powerState: string;
    readonly processors: outputs.GetOmniMachineProcessor[];
    readonly region: string;
    readonly role: string;
    readonly talosVersion: string;
    readonly zone: string;
}
export function getOmniMachineOutput(args: GetOmniMachineOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOmniMachineResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getOmniMachine:getOmniMachine", {
        "credentialId": args.credentialId,
        "id": args.id,
        "machineName": args.machineName,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getOmniMachine.
 */
export interface GetOmniMachineOutputArgs {
    credentialId: pulumi.Input<number>;
    id?: pulumi.Input<string | undefined>;
    machineName: pulumi.Input<string>;
}
