// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRegistryAccess(args: GetRegistryAccessArgs, opts?: pulumi.InvokeOptions): Promise<GetRegistryAccessResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("portainer:index/getRegistryAccess:getRegistryAccess", {
        "endpointId": args.endpointId,
        "id": args.id,
        "registryId": args.registryId,
        "teamId": args.teamId,
        "userId": args.userId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRegistryAccess.
 */
export interface GetRegistryAccessArgs {
    endpointId: number;
    id?: string;
    registryId: number;
    teamId?: number;
    userId?: number;
}

/**
 * A collection of values returned by getRegistryAccess.
 */
export interface GetRegistryAccessResult {
    readonly endpointId: number;
    readonly id: string;
    readonly registryId: number;
    readonly roleId: number;
    readonly teamId?: number;
    readonly userId?: number;
}
export function getRegistryAccessOutput(args: GetRegistryAccessOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRegistryAccessResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("portainer:index/getRegistryAccess:getRegistryAccess", {
        "endpointId": args.endpointId,
        "id": args.id,
        "registryId": args.registryId,
        "teamId": args.teamId,
        "userId": args.userId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRegistryAccess.
 */
export interface GetRegistryAccessOutputArgs {
    endpointId: pulumi.Input<number>;
    id?: pulumi.Input<string>;
    registryId: pulumi.Input<number>;
    teamId?: pulumi.Input<number>;
    userId?: pulumi.Input<number>;
}
