// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class KubernetesDeploymentRollback extends pulumi.CustomResource {
    /**
     * Get an existing KubernetesDeploymentRollback resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: KubernetesDeploymentRollbackState, opts?: pulumi.CustomResourceOptions): KubernetesDeploymentRollback {
        return new KubernetesDeploymentRollback(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/kubernetesDeploymentRollback:KubernetesDeploymentRollback';

    /**
     * Returns true if the given object is an instance of KubernetesDeploymentRollback.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KubernetesDeploymentRollback {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KubernetesDeploymentRollback.__pulumiType;
    }

    /**
     * Name of the deployment to roll back.
     */
    declare public readonly deploymentName: pulumi.Output<string>;
    /**
     * Identifier of the Portainer Kubernetes environment the deployment belongs to.
     */
    declare public readonly environmentId: pulumi.Output<number>;
    declare public readonly kubernetesDeploymentRollbackId: pulumi.Output<string>;
    /**
     * Namespace the deployment lives in.
     */
    declare public readonly namespace: pulumi.Output<string>;
    /**
     * Rollout revision to roll back to. <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> (the default) rolls back to the previous revision, matching `kubectl rollout undo`. Use the <span pulumi-lang-nodejs="`portainer.getKubernetesReplicasets`" pulumi-lang-dotnet="`portainer.getKubernetesReplicasets`" pulumi-lang-go="`getKubernetesReplicasets`" pulumi-lang-python="`get_kubernetes_replicasets`" pulumi-lang-yaml="`portainer.getKubernetesReplicasets`" pulumi-lang-java="`portainer.getKubernetesReplicasets`" pulumi-lang-hcl="`data.portainer_kubernetes_replicasets`">`portainer.getKubernetesReplicasets`</span> data source to discover the available revisions.
     */
    declare public readonly revision: pulumi.Output<number | undefined>;
    /**
     * Desired replica count of the deployment after the rollback.
     */
    declare public /*out*/ readonly rolledBackToReplicas: pulumi.Output<number>;

    /**
     * Create a KubernetesDeploymentRollback resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: KubernetesDeploymentRollbackArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: KubernetesDeploymentRollbackArgs | KubernetesDeploymentRollbackState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as KubernetesDeploymentRollbackState | undefined;
            resourceInputs["deploymentName"] = state?.deploymentName;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["kubernetesDeploymentRollbackId"] = state?.kubernetesDeploymentRollbackId;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["revision"] = state?.revision;
            resourceInputs["rolledBackToReplicas"] = state?.rolledBackToReplicas;
        } else {
            const args = argsOrState as KubernetesDeploymentRollbackArgs | undefined;
            if (args?.deploymentName === undefined && !opts.urn) {
                throw new Error("Missing required property 'deploymentName'");
            }
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.namespace === undefined && !opts.urn) {
                throw new Error("Missing required property 'namespace'");
            }
            resourceInputs["deploymentName"] = args?.deploymentName;
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["kubernetesDeploymentRollbackId"] = args?.kubernetesDeploymentRollbackId;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["revision"] = args?.revision;
            resourceInputs["rolledBackToReplicas"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(KubernetesDeploymentRollback.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering KubernetesDeploymentRollback resources.
 */
export interface KubernetesDeploymentRollbackState {
    /**
     * Name of the deployment to roll back.
     */
    deploymentName?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the Portainer Kubernetes environment the deployment belongs to.
     */
    environmentId?: pulumi.Input<number | undefined>;
    kubernetesDeploymentRollbackId?: pulumi.Input<string | undefined>;
    /**
     * Namespace the deployment lives in.
     */
    namespace?: pulumi.Input<string | undefined>;
    /**
     * Rollout revision to roll back to. <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> (the default) rolls back to the previous revision, matching `kubectl rollout undo`. Use the <span pulumi-lang-nodejs="`portainer.getKubernetesReplicasets`" pulumi-lang-dotnet="`portainer.getKubernetesReplicasets`" pulumi-lang-go="`getKubernetesReplicasets`" pulumi-lang-python="`get_kubernetes_replicasets`" pulumi-lang-yaml="`portainer.getKubernetesReplicasets`" pulumi-lang-java="`portainer.getKubernetesReplicasets`" pulumi-lang-hcl="`data.portainer_kubernetes_replicasets`">`portainer.getKubernetesReplicasets`</span> data source to discover the available revisions.
     */
    revision?: pulumi.Input<number | undefined>;
    /**
     * Desired replica count of the deployment after the rollback.
     */
    rolledBackToReplicas?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a KubernetesDeploymentRollback resource.
 */
export interface KubernetesDeploymentRollbackArgs {
    /**
     * Name of the deployment to roll back.
     */
    deploymentName: pulumi.Input<string>;
    /**
     * Identifier of the Portainer Kubernetes environment the deployment belongs to.
     */
    environmentId: pulumi.Input<number>;
    kubernetesDeploymentRollbackId?: pulumi.Input<string | undefined>;
    /**
     * Namespace the deployment lives in.
     */
    namespace: pulumi.Input<string>;
    /**
     * Rollout revision to roll back to. <span pulumi-lang-nodejs="`0`" pulumi-lang-dotnet="`0`" pulumi-lang-go="`0`" pulumi-lang-python="`0`" pulumi-lang-yaml="`0`" pulumi-lang-java="`0`" pulumi-lang-hcl="`0`">`0`</span> (the default) rolls back to the previous revision, matching `kubectl rollout undo`. Use the <span pulumi-lang-nodejs="`portainer.getKubernetesReplicasets`" pulumi-lang-dotnet="`portainer.getKubernetesReplicasets`" pulumi-lang-go="`getKubernetesReplicasets`" pulumi-lang-python="`get_kubernetes_replicasets`" pulumi-lang-yaml="`portainer.getKubernetesReplicasets`" pulumi-lang-java="`portainer.getKubernetesReplicasets`" pulumi-lang-hcl="`data.portainer_kubernetes_replicasets`">`portainer.getKubernetesReplicasets`</span> data source to discover the available revisions.
     */
    revision?: pulumi.Input<number | undefined>;
}
