// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class KubernetesIngresscontrollers extends pulumi.CustomResource {
    /**
     * Get an existing KubernetesIngresscontrollers resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: KubernetesIngresscontrollersState, opts?: pulumi.CustomResourceOptions): KubernetesIngresscontrollers {
        return new KubernetesIngresscontrollers(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/kubernetesIngresscontrollers:KubernetesIngresscontrollers';

    /**
     * Returns true if the given object is an instance of KubernetesIngresscontrollers.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KubernetesIngresscontrollers {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KubernetesIngresscontrollers.__pulumiType;
    }

    declare public readonly controllers: pulumi.Output<outputs.KubernetesIngresscontrollersController[]>;
    declare public readonly environmentId: pulumi.Output<number>;
    declare public readonly kubernetesIngresscontrollersId: pulumi.Output<string>;

    /**
     * Create a KubernetesIngresscontrollers resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: KubernetesIngresscontrollersArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: KubernetesIngresscontrollersArgs | KubernetesIngresscontrollersState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as KubernetesIngresscontrollersState | undefined;
            resourceInputs["controllers"] = state?.controllers;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["kubernetesIngresscontrollersId"] = state?.kubernetesIngresscontrollersId;
        } else {
            const args = argsOrState as KubernetesIngresscontrollersArgs | undefined;
            if (args?.controllers === undefined && !opts.urn) {
                throw new Error("Missing required property 'controllers'");
            }
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            resourceInputs["controllers"] = args?.controllers;
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["kubernetesIngresscontrollersId"] = args?.kubernetesIngresscontrollersId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(KubernetesIngresscontrollers.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering KubernetesIngresscontrollers resources.
 */
export interface KubernetesIngresscontrollersState {
    controllers?: pulumi.Input<pulumi.Input<inputs.KubernetesIngresscontrollersController>[]>;
    environmentId?: pulumi.Input<number>;
    kubernetesIngresscontrollersId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a KubernetesIngresscontrollers resource.
 */
export interface KubernetesIngresscontrollersArgs {
    controllers: pulumi.Input<pulumi.Input<inputs.KubernetesIngresscontrollersController>[]>;
    environmentId: pulumi.Input<number>;
    kubernetesIngresscontrollersId?: pulumi.Input<string>;
}
