// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class KubernetesNamespaceSystem extends pulumi.CustomResource {
    /**
     * Get an existing KubernetesNamespaceSystem resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: KubernetesNamespaceSystemState, opts?: pulumi.CustomResourceOptions): KubernetesNamespaceSystem {
        return new KubernetesNamespaceSystem(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/kubernetesNamespaceSystem:KubernetesNamespaceSystem';

    /**
     * Returns true if the given object is an instance of KubernetesNamespaceSystem.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KubernetesNamespaceSystem {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KubernetesNamespaceSystem.__pulumiType;
    }

    declare public readonly environmentId: pulumi.Output<number>;
    declare public readonly kubernetesNamespaceSystemId: pulumi.Output<string>;
    declare public readonly namespace: pulumi.Output<string>;
    declare public readonly system: pulumi.Output<boolean>;

    /**
     * Create a KubernetesNamespaceSystem resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: KubernetesNamespaceSystemArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: KubernetesNamespaceSystemArgs | KubernetesNamespaceSystemState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as KubernetesNamespaceSystemState | undefined;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["kubernetesNamespaceSystemId"] = state?.kubernetesNamespaceSystemId;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["system"] = state?.system;
        } else {
            const args = argsOrState as KubernetesNamespaceSystemArgs | undefined;
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.namespace === undefined && !opts.urn) {
                throw new Error("Missing required property 'namespace'");
            }
            if (args?.system === undefined && !opts.urn) {
                throw new Error("Missing required property 'system'");
            }
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["kubernetesNamespaceSystemId"] = args?.kubernetesNamespaceSystemId;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["system"] = args?.system;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(KubernetesNamespaceSystem.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering KubernetesNamespaceSystem resources.
 */
export interface KubernetesNamespaceSystemState {
    environmentId?: pulumi.Input<number>;
    kubernetesNamespaceSystemId?: pulumi.Input<string>;
    namespace?: pulumi.Input<string>;
    system?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a KubernetesNamespaceSystem resource.
 */
export interface KubernetesNamespaceSystemArgs {
    environmentId: pulumi.Input<number>;
    kubernetesNamespaceSystemId?: pulumi.Input<string>;
    namespace: pulumi.Input<string>;
    system: pulumi.Input<boolean>;
}
