// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class OmniCluster extends pulumi.CustomResource {
    /**
     * Get an existing OmniCluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OmniClusterState, opts?: pulumi.CustomResourceOptions): OmniCluster {
        return new OmniCluster(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/omniCluster:OmniCluster';

    /**
     * Returns true if the given object is an instance of OmniCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OmniCluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OmniCluster.__pulumiType;
    }

    /**
     * Whether Omni reports the cluster as available.
     */
    declare public /*out*/ readonly available: pulumi.Output<boolean>;
    /**
     * Whether Omni backs the cluster's etcd up on a schedule.
     */
    declare public /*out*/ readonly backupEnabled: pulumi.Output<boolean>;
    /**
     * Interval between the scheduled etcd backups.
     */
    declare public /*out*/ readonly backupInterval: pulumi.Output<string>;
    /**
     * Raw Omni cluster template, as an alternative to describing the cluster with the blocks below. Only read when the cluster is created.
     */
    declare public readonly clusterConfig: pulumi.Output<string | undefined>;
    /**
     * Talos configuration patches to apply to the cluster as a whole.
     */
    declare public readonly clusterPatches: pulumi.Output<outputs.OmniClusterClusterPatch[] | undefined>;
    /**
     * The cluster's control plane.
     */
    declare public readonly controlPlane: pulumi.Output<outputs.OmniClusterControlPlane | undefined>;
    /**
     * Whether the control plane has come up.
     */
    declare public /*out*/ readonly controlPlaneReady: pulumi.Output<boolean>;
    /**
     * Identifier of the Portainer cloud credential holding the Omni endpoint and service account key.
     */
    declare public readonly credentialId: pulumi.Output<number>;
    /**
     * Whether disk encryption is enabled on the cluster.
     */
    declare public /*out*/ readonly diskEncryption: pulumi.Output<boolean>;
    /**
     * Whether the cluster uses Omni's embedded discovery service.
     */
    declare public /*out*/ readonly embeddedDiscoveryService: pulumi.Output<boolean>;
    /**
     * Identifier of the Portainer environment created for the cluster.
     */
    declare public /*out*/ readonly endpointId: pulumi.Output<number>;
    /**
     * Omni resource kind of the cluster. Leave unset unless Omni asks for a specific one.
     */
    declare public readonly kind: pulumi.Output<string | undefined>;
    /**
     * Whether the cluster's Kubernetes API is answering.
     */
    declare public /*out*/ readonly kubernetesApiReady: pulumi.Output<boolean>;
    /**
     * Kubernetes version to run. Leave unset to let Omni pick, and read the result back from this attribute.
     */
    declare public readonly kubernetesVersion: pulumi.Output<string>;
    /**
     * Labels to set on the Omni cluster resource.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Machines currently connected to Omni.
     */
    declare public /*out*/ readonly machinesConnected: pulumi.Output<number>;
    /**
     * Machines Omni considers healthy.
     */
    declare public /*out*/ readonly machinesHealthy: pulumi.Output<number>;
    /**
     * Machines the cluster asked for.
     */
    declare public /*out*/ readonly machinesRequested: pulumi.Output<number>;
    /**
     * Machines Omni counts in the cluster.
     */
    declare public /*out*/ readonly machinesTotal: pulumi.Output<number>;
    /**
     * Name of the cluster. Omni cannot rename a cluster, so changing it replaces the resource.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly omniClusterId: pulumi.Output<string>;
    /**
     * Provisioning phase Omni reports for the cluster.
     */
    declare public /*out*/ readonly phase: pulumi.Output<number>;
    /**
     * URL the provisioned nodes reach Portainer on. Leave unset to use the instance's configured URL.
     */
    declare public readonly portainerUrl: pulumi.Output<string | undefined>;
    /**
     * Whether Omni reports the cluster as ready.
     */
    declare public /*out*/ readonly ready: pulumi.Output<boolean>;
    /**
     * Talos version to run. Use the <span pulumi-lang-nodejs="`portainer.getOmniTalosVersions`" pulumi-lang-dotnet="`portainer.getOmniTalosVersions`" pulumi-lang-go="`getOmniTalosVersions`" pulumi-lang-python="`get_omni_talos_versions`" pulumi-lang-yaml="`portainer.getOmniTalosVersions`" pulumi-lang-java="`portainer.getOmniTalosVersions`" pulumi-lang-hcl="`data.portainer_omni_talos_versions`">`portainer.getOmniTalosVersions`</span> data source to see what the credential supports.
     */
    declare public readonly talosVersion: pulumi.Output<string>;
    /**
     * Address the provisioned nodes reach Portainer's tunnel server on.
     */
    declare public readonly tunnelServerAddress: pulumi.Output<string | undefined>;
    /**
     * Whether to validate the cluster configuration with Portainer before provisioning it. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly validateBeforeCreate: pulumi.Output<boolean | undefined>;
    /**
     * The cluster's worker pool.
     */
    declare public readonly worker: pulumi.Output<outputs.OmniClusterWorker | undefined>;
    /**
     * Whether Omni's workload proxy is enabled for the cluster.
     */
    declare public /*out*/ readonly workloadProxyEnabled: pulumi.Output<boolean>;

    /**
     * Create a OmniCluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OmniClusterArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OmniClusterArgs | OmniClusterState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OmniClusterState | undefined;
            resourceInputs["available"] = state?.available;
            resourceInputs["backupEnabled"] = state?.backupEnabled;
            resourceInputs["backupInterval"] = state?.backupInterval;
            resourceInputs["clusterConfig"] = state?.clusterConfig;
            resourceInputs["clusterPatches"] = state?.clusterPatches;
            resourceInputs["controlPlane"] = state?.controlPlane;
            resourceInputs["controlPlaneReady"] = state?.controlPlaneReady;
            resourceInputs["credentialId"] = state?.credentialId;
            resourceInputs["diskEncryption"] = state?.diskEncryption;
            resourceInputs["embeddedDiscoveryService"] = state?.embeddedDiscoveryService;
            resourceInputs["endpointId"] = state?.endpointId;
            resourceInputs["kind"] = state?.kind;
            resourceInputs["kubernetesApiReady"] = state?.kubernetesApiReady;
            resourceInputs["kubernetesVersion"] = state?.kubernetesVersion;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["machinesConnected"] = state?.machinesConnected;
            resourceInputs["machinesHealthy"] = state?.machinesHealthy;
            resourceInputs["machinesRequested"] = state?.machinesRequested;
            resourceInputs["machinesTotal"] = state?.machinesTotal;
            resourceInputs["name"] = state?.name;
            resourceInputs["omniClusterId"] = state?.omniClusterId;
            resourceInputs["phase"] = state?.phase;
            resourceInputs["portainerUrl"] = state?.portainerUrl;
            resourceInputs["ready"] = state?.ready;
            resourceInputs["talosVersion"] = state?.talosVersion;
            resourceInputs["tunnelServerAddress"] = state?.tunnelServerAddress;
            resourceInputs["validateBeforeCreate"] = state?.validateBeforeCreate;
            resourceInputs["worker"] = state?.worker;
            resourceInputs["workloadProxyEnabled"] = state?.workloadProxyEnabled;
        } else {
            const args = argsOrState as OmniClusterArgs | undefined;
            if (args?.credentialId === undefined && !opts.urn) {
                throw new Error("Missing required property 'credentialId'");
            }
            resourceInputs["clusterConfig"] = args?.clusterConfig;
            resourceInputs["clusterPatches"] = args?.clusterPatches;
            resourceInputs["controlPlane"] = args?.controlPlane;
            resourceInputs["credentialId"] = args?.credentialId;
            resourceInputs["kind"] = args?.kind;
            resourceInputs["kubernetesVersion"] = args?.kubernetesVersion;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["omniClusterId"] = args?.omniClusterId;
            resourceInputs["portainerUrl"] = args?.portainerUrl;
            resourceInputs["talosVersion"] = args?.talosVersion;
            resourceInputs["tunnelServerAddress"] = args?.tunnelServerAddress;
            resourceInputs["validateBeforeCreate"] = args?.validateBeforeCreate;
            resourceInputs["worker"] = args?.worker;
            resourceInputs["available"] = undefined /*out*/;
            resourceInputs["backupEnabled"] = undefined /*out*/;
            resourceInputs["backupInterval"] = undefined /*out*/;
            resourceInputs["controlPlaneReady"] = undefined /*out*/;
            resourceInputs["diskEncryption"] = undefined /*out*/;
            resourceInputs["embeddedDiscoveryService"] = undefined /*out*/;
            resourceInputs["endpointId"] = undefined /*out*/;
            resourceInputs["kubernetesApiReady"] = undefined /*out*/;
            resourceInputs["machinesConnected"] = undefined /*out*/;
            resourceInputs["machinesHealthy"] = undefined /*out*/;
            resourceInputs["machinesRequested"] = undefined /*out*/;
            resourceInputs["machinesTotal"] = undefined /*out*/;
            resourceInputs["phase"] = undefined /*out*/;
            resourceInputs["ready"] = undefined /*out*/;
            resourceInputs["workloadProxyEnabled"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OmniCluster.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OmniCluster resources.
 */
export interface OmniClusterState {
    /**
     * Whether Omni reports the cluster as available.
     */
    available?: pulumi.Input<boolean | undefined>;
    /**
     * Whether Omni backs the cluster's etcd up on a schedule.
     */
    backupEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Interval between the scheduled etcd backups.
     */
    backupInterval?: pulumi.Input<string | undefined>;
    /**
     * Raw Omni cluster template, as an alternative to describing the cluster with the blocks below. Only read when the cluster is created.
     */
    clusterConfig?: pulumi.Input<string | undefined>;
    /**
     * Talos configuration patches to apply to the cluster as a whole.
     */
    clusterPatches?: pulumi.Input<pulumi.Input<inputs.OmniClusterClusterPatch>[] | undefined>;
    /**
     * The cluster's control plane.
     */
    controlPlane?: pulumi.Input<inputs.OmniClusterControlPlane | undefined>;
    /**
     * Whether the control plane has come up.
     */
    controlPlaneReady?: pulumi.Input<boolean | undefined>;
    /**
     * Identifier of the Portainer cloud credential holding the Omni endpoint and service account key.
     */
    credentialId?: pulumi.Input<number | undefined>;
    /**
     * Whether disk encryption is enabled on the cluster.
     */
    diskEncryption?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the cluster uses Omni's embedded discovery service.
     */
    embeddedDiscoveryService?: pulumi.Input<boolean | undefined>;
    /**
     * Identifier of the Portainer environment created for the cluster.
     */
    endpointId?: pulumi.Input<number | undefined>;
    /**
     * Omni resource kind of the cluster. Leave unset unless Omni asks for a specific one.
     */
    kind?: pulumi.Input<string | undefined>;
    /**
     * Whether the cluster's Kubernetes API is answering.
     */
    kubernetesApiReady?: pulumi.Input<boolean | undefined>;
    /**
     * Kubernetes version to run. Leave unset to let Omni pick, and read the result back from this attribute.
     */
    kubernetesVersion?: pulumi.Input<string | undefined>;
    /**
     * Labels to set on the Omni cluster resource.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Machines currently connected to Omni.
     */
    machinesConnected?: pulumi.Input<number | undefined>;
    /**
     * Machines Omni considers healthy.
     */
    machinesHealthy?: pulumi.Input<number | undefined>;
    /**
     * Machines the cluster asked for.
     */
    machinesRequested?: pulumi.Input<number | undefined>;
    /**
     * Machines Omni counts in the cluster.
     */
    machinesTotal?: pulumi.Input<number | undefined>;
    /**
     * Name of the cluster. Omni cannot rename a cluster, so changing it replaces the resource.
     */
    name?: pulumi.Input<string | undefined>;
    omniClusterId?: pulumi.Input<string | undefined>;
    /**
     * Provisioning phase Omni reports for the cluster.
     */
    phase?: pulumi.Input<number | undefined>;
    /**
     * URL the provisioned nodes reach Portainer on. Leave unset to use the instance's configured URL.
     */
    portainerUrl?: pulumi.Input<string | undefined>;
    /**
     * Whether Omni reports the cluster as ready.
     */
    ready?: pulumi.Input<boolean | undefined>;
    /**
     * Talos version to run. Use the <span pulumi-lang-nodejs="`portainer.getOmniTalosVersions`" pulumi-lang-dotnet="`portainer.getOmniTalosVersions`" pulumi-lang-go="`getOmniTalosVersions`" pulumi-lang-python="`get_omni_talos_versions`" pulumi-lang-yaml="`portainer.getOmniTalosVersions`" pulumi-lang-java="`portainer.getOmniTalosVersions`" pulumi-lang-hcl="`data.portainer_omni_talos_versions`">`portainer.getOmniTalosVersions`</span> data source to see what the credential supports.
     */
    talosVersion?: pulumi.Input<string | undefined>;
    /**
     * Address the provisioned nodes reach Portainer's tunnel server on.
     */
    tunnelServerAddress?: pulumi.Input<string | undefined>;
    /**
     * Whether to validate the cluster configuration with Portainer before provisioning it. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    validateBeforeCreate?: pulumi.Input<boolean | undefined>;
    /**
     * The cluster's worker pool.
     */
    worker?: pulumi.Input<inputs.OmniClusterWorker | undefined>;
    /**
     * Whether Omni's workload proxy is enabled for the cluster.
     */
    workloadProxyEnabled?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a OmniCluster resource.
 */
export interface OmniClusterArgs {
    /**
     * Raw Omni cluster template, as an alternative to describing the cluster with the blocks below. Only read when the cluster is created.
     */
    clusterConfig?: pulumi.Input<string | undefined>;
    /**
     * Talos configuration patches to apply to the cluster as a whole.
     */
    clusterPatches?: pulumi.Input<pulumi.Input<inputs.OmniClusterClusterPatch>[] | undefined>;
    /**
     * The cluster's control plane.
     */
    controlPlane?: pulumi.Input<inputs.OmniClusterControlPlane | undefined>;
    /**
     * Identifier of the Portainer cloud credential holding the Omni endpoint and service account key.
     */
    credentialId: pulumi.Input<number>;
    /**
     * Omni resource kind of the cluster. Leave unset unless Omni asks for a specific one.
     */
    kind?: pulumi.Input<string | undefined>;
    /**
     * Kubernetes version to run. Leave unset to let Omni pick, and read the result back from this attribute.
     */
    kubernetesVersion?: pulumi.Input<string | undefined>;
    /**
     * Labels to set on the Omni cluster resource.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Name of the cluster. Omni cannot rename a cluster, so changing it replaces the resource.
     */
    name?: pulumi.Input<string | undefined>;
    omniClusterId?: pulumi.Input<string | undefined>;
    /**
     * URL the provisioned nodes reach Portainer on. Leave unset to use the instance's configured URL.
     */
    portainerUrl?: pulumi.Input<string | undefined>;
    /**
     * Talos version to run. Use the <span pulumi-lang-nodejs="`portainer.getOmniTalosVersions`" pulumi-lang-dotnet="`portainer.getOmniTalosVersions`" pulumi-lang-go="`getOmniTalosVersions`" pulumi-lang-python="`get_omni_talos_versions`" pulumi-lang-yaml="`portainer.getOmniTalosVersions`" pulumi-lang-java="`portainer.getOmniTalosVersions`" pulumi-lang-hcl="`data.portainer_omni_talos_versions`">`portainer.getOmniTalosVersions`</span> data source to see what the credential supports.
     */
    talosVersion?: pulumi.Input<string | undefined>;
    /**
     * Address the provisioned nodes reach Portainer's tunnel server on.
     */
    tunnelServerAddress?: pulumi.Input<string | undefined>;
    /**
     * Whether to validate the cluster configuration with Portainer before provisioning it. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    validateBeforeCreate?: pulumi.Input<boolean | undefined>;
    /**
     * The cluster's worker pool.
     */
    worker?: pulumi.Input<inputs.OmniClusterWorker | undefined>;
}
