// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OmniNodeReboot extends pulumi.CustomResource {
    /**
     * Get an existing OmniNodeReboot resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OmniNodeRebootState, opts?: pulumi.CustomResourceOptions): OmniNodeReboot {
        return new OmniNodeReboot(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/omniNodeReboot:OmniNodeReboot';

    /**
     * Returns true if the given object is an instance of OmniNodeReboot.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OmniNodeReboot {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OmniNodeReboot.__pulumiType;
    }

    /**
     * Name of the cluster the node belongs to.
     */
    declare public readonly cluster: pulumi.Output<string>;
    /**
     * Identifier of the Portainer cloud credential holding the Omni endpoint and service account key.
     */
    declare public readonly credentialId: pulumi.Output<number>;
    /**
     * Name of the node to reboot.
     */
    declare public readonly node: pulumi.Output<string>;
    declare public readonly omniNodeRebootId: pulumi.Output<string>;
    /**
     * Arbitrary values that force another reboot when they change. A reboot is a one-shot action, so without a trigger the resource runs once and then stays put.
     */
    declare public readonly triggers: pulumi.Output<{[key: string]: string} | undefined>;

    /**
     * Create a OmniNodeReboot resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OmniNodeRebootArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OmniNodeRebootArgs | OmniNodeRebootState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OmniNodeRebootState | undefined;
            resourceInputs["cluster"] = state?.cluster;
            resourceInputs["credentialId"] = state?.credentialId;
            resourceInputs["node"] = state?.node;
            resourceInputs["omniNodeRebootId"] = state?.omniNodeRebootId;
            resourceInputs["triggers"] = state?.triggers;
        } else {
            const args = argsOrState as OmniNodeRebootArgs | undefined;
            if (args?.cluster === undefined && !opts.urn) {
                throw new Error("Missing required property 'cluster'");
            }
            if (args?.credentialId === undefined && !opts.urn) {
                throw new Error("Missing required property 'credentialId'");
            }
            if (args?.node === undefined && !opts.urn) {
                throw new Error("Missing required property 'node'");
            }
            resourceInputs["cluster"] = args?.cluster;
            resourceInputs["credentialId"] = args?.credentialId;
            resourceInputs["node"] = args?.node;
            resourceInputs["omniNodeRebootId"] = args?.omniNodeRebootId;
            resourceInputs["triggers"] = args?.triggers;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OmniNodeReboot.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OmniNodeReboot resources.
 */
export interface OmniNodeRebootState {
    /**
     * Name of the cluster the node belongs to.
     */
    cluster?: pulumi.Input<string | undefined>;
    /**
     * Identifier of the Portainer cloud credential holding the Omni endpoint and service account key.
     */
    credentialId?: pulumi.Input<number | undefined>;
    /**
     * Name of the node to reboot.
     */
    node?: pulumi.Input<string | undefined>;
    omniNodeRebootId?: pulumi.Input<string | undefined>;
    /**
     * Arbitrary values that force another reboot when they change. A reboot is a one-shot action, so without a trigger the resource runs once and then stays put.
     */
    triggers?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
}

/**
 * The set of arguments for constructing a OmniNodeReboot resource.
 */
export interface OmniNodeRebootArgs {
    /**
     * Name of the cluster the node belongs to.
     */
    cluster: pulumi.Input<string>;
    /**
     * Identifier of the Portainer cloud credential holding the Omni endpoint and service account key.
     */
    credentialId: pulumi.Input<number>;
    /**
     * Name of the node to reboot.
     */
    node: pulumi.Input<string>;
    omniNodeRebootId?: pulumi.Input<string | undefined>;
    /**
     * Arbitrary values that force another reboot when they change. A reboot is a one-shot action, so without a trigger the resource runs once and then stays put.
     */
    triggers?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
}
