// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Policy extends pulumi.CustomResource {
    /**
     * Get an existing Policy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyState, opts?: pulumi.CustomResourceOptions): Policy {
        return new Policy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/policy:Policy';

    /**
     * Returns true if the given object is an instance of Policy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Policy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Policy.__pulumiType;
    }

    /**
     * Whether to allow environments to override this policy.
     */
    declare public readonly allowOverride: pulumi.Output<boolean | undefined>;
    /**
     * Timestamp when the policy was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Policy data as a JSON string. Structure depends on policy_type.
     */
    declare public readonly data: pulumi.Output<string | undefined>;
    /**
     * List of environment group IDs to which the policy applies.
     */
    declare public readonly environmentGroups: pulumi.Output<number[] | undefined>;
    /**
     * Environment type for the policy (kubernetes, docker, podman, swarm).
     */
    declare public readonly environmentType: pulumi.Output<string>;
    /**
     * Name of the policy.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly policyId: pulumi.Output<string>;
    /**
     * Policy type (e.g. rbac-k8s, security-docker).
     */
    declare public readonly policyType: pulumi.Output<string>;
    /**
     * Timestamp when the policy was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a Policy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyArgs | PolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyState | undefined;
            resourceInputs["allowOverride"] = state?.allowOverride;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["data"] = state?.data;
            resourceInputs["environmentGroups"] = state?.environmentGroups;
            resourceInputs["environmentType"] = state?.environmentType;
            resourceInputs["name"] = state?.name;
            resourceInputs["policyId"] = state?.policyId;
            resourceInputs["policyType"] = state?.policyType;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as PolicyArgs | undefined;
            if (args?.environmentType === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentType'");
            }
            if (args?.policyType === undefined && !opts.urn) {
                throw new Error("Missing required property 'policyType'");
            }
            resourceInputs["allowOverride"] = args?.allowOverride;
            resourceInputs["data"] = args?.data;
            resourceInputs["environmentGroups"] = args?.environmentGroups;
            resourceInputs["environmentType"] = args?.environmentType;
            resourceInputs["name"] = args?.name;
            resourceInputs["policyId"] = args?.policyId;
            resourceInputs["policyType"] = args?.policyType;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Policy.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Policy resources.
 */
export interface PolicyState {
    /**
     * Whether to allow environments to override this policy.
     */
    allowOverride?: pulumi.Input<boolean>;
    /**
     * Timestamp when the policy was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Policy data as a JSON string. Structure depends on policy_type.
     */
    data?: pulumi.Input<string>;
    /**
     * List of environment group IDs to which the policy applies.
     */
    environmentGroups?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Environment type for the policy (kubernetes, docker, podman, swarm).
     */
    environmentType?: pulumi.Input<string>;
    /**
     * Name of the policy.
     */
    name?: pulumi.Input<string>;
    policyId?: pulumi.Input<string>;
    /**
     * Policy type (e.g. rbac-k8s, security-docker).
     */
    policyType?: pulumi.Input<string>;
    /**
     * Timestamp when the policy was last updated.
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Policy resource.
 */
export interface PolicyArgs {
    /**
     * Whether to allow environments to override this policy.
     */
    allowOverride?: pulumi.Input<boolean>;
    /**
     * Policy data as a JSON string. Structure depends on policy_type.
     */
    data?: pulumi.Input<string>;
    /**
     * List of environment group IDs to which the policy applies.
     */
    environmentGroups?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Environment type for the policy (kubernetes, docker, podman, swarm).
     */
    environmentType: pulumi.Input<string>;
    /**
     * Name of the policy.
     */
    name?: pulumi.Input<string>;
    policyId?: pulumi.Input<string>;
    /**
     * Policy type (e.g. rbac-k8s, security-docker).
     */
    policyType: pulumi.Input<string>;
}
