// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class UserGitCredential extends pulumi.CustomResource {
    /**
     * Get an existing UserGitCredential resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserGitCredentialState, opts?: pulumi.CustomResourceOptions): UserGitCredential {
        return new UserGitCredential(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/userGitCredential:UserGitCredential';

    /**
     * Returns true if the given object is an instance of UserGitCredential.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UserGitCredential {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UserGitCredential.__pulumiType;
    }

    /**
     * Authorization type: 0 = Basic, 1 = Token
     */
    declare public readonly authorizationType: pulumi.Output<number | undefined>;
    /**
     * ID of the git credential
     */
    declare public /*out*/ readonly credentialId: pulumi.Output<number>;
    /**
     * Name of the git credential
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Password or token for git authentication
     */
    declare public readonly password: pulumi.Output<string>;
    declare public readonly userGitCredentialId: pulumi.Output<string>;
    /**
     * ID of the user who owns this git credential
     */
    declare public readonly userId: pulumi.Output<number>;
    /**
     * Username for git authentication
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a UserGitCredential resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserGitCredentialArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserGitCredentialArgs | UserGitCredentialState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserGitCredentialState | undefined;
            resourceInputs["authorizationType"] = state?.authorizationType;
            resourceInputs["credentialId"] = state?.credentialId;
            resourceInputs["name"] = state?.name;
            resourceInputs["password"] = state?.password;
            resourceInputs["userGitCredentialId"] = state?.userGitCredentialId;
            resourceInputs["userId"] = state?.userId;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as UserGitCredentialArgs | undefined;
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            if (args?.userId === undefined && !opts.urn) {
                throw new Error("Missing required property 'userId'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["authorizationType"] = args?.authorizationType;
            resourceInputs["name"] = args?.name;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["userGitCredentialId"] = args?.userGitCredentialId;
            resourceInputs["userId"] = args?.userId;
            resourceInputs["username"] = args?.username;
            resourceInputs["credentialId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(UserGitCredential.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering UserGitCredential resources.
 */
export interface UserGitCredentialState {
    /**
     * Authorization type: 0 = Basic, 1 = Token
     */
    authorizationType?: pulumi.Input<number>;
    /**
     * ID of the git credential
     */
    credentialId?: pulumi.Input<number>;
    /**
     * Name of the git credential
     */
    name?: pulumi.Input<string>;
    /**
     * Password or token for git authentication
     */
    password?: pulumi.Input<string>;
    userGitCredentialId?: pulumi.Input<string>;
    /**
     * ID of the user who owns this git credential
     */
    userId?: pulumi.Input<number>;
    /**
     * Username for git authentication
     */
    username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a UserGitCredential resource.
 */
export interface UserGitCredentialArgs {
    /**
     * Authorization type: 0 = Basic, 1 = Token
     */
    authorizationType?: pulumi.Input<number>;
    /**
     * Name of the git credential
     */
    name?: pulumi.Input<string>;
    /**
     * Password or token for git authentication
     */
    password: pulumi.Input<string>;
    userGitCredentialId?: pulumi.Input<string>;
    /**
     * ID of the user who owns this git credential
     */
    userId: pulumi.Input<number>;
    /**
     * Username for git authentication
     */
    username: pulumi.Input<string>;
}
