// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Webhook extends pulumi.CustomResource {
    /**
     * Get an existing Webhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WebhookState, opts?: pulumi.CustomResourceOptions): Webhook {
        return new Webhook(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'portainer:index/webhook:Webhook';

    /**
     * Returns true if the given object is an instance of Webhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Webhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Webhook.__pulumiType;
    }

    /**
     * Identifier of the Portainer environment (endpoint) the webhook is bound to. Changing this value forces resource recreation.
     */
    declare public readonly endpointId: pulumi.Output<number>;
    /**
     * Identifier of the Portainer registry associated with this webhook. Used when the webhook triggers actions on images from that registry.
     */
    declare public readonly registryId: pulumi.Output<number | undefined>;
    /**
     * Identifier of the target resource (e.g. service ID) the webhook will act upon. Changing this value forces resource recreation.
     */
    declare public readonly resourceId: pulumi.Output<string>;
    /**
     * Webhook token generated by Portainer. Appended to the webhook URL to authenticate trigger calls.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    declare public readonly webhookId: pulumi.Output<string>;
    /**
     * Type of webhook in Portainer (e.g. 1 = service webhook, 2 = container webhook). Changing this value forces resource recreation.
     */
    declare public readonly webhookType: pulumi.Output<number>;

    /**
     * Create a Webhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WebhookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WebhookArgs | WebhookState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WebhookState | undefined;
            resourceInputs["endpointId"] = state?.endpointId;
            resourceInputs["registryId"] = state?.registryId;
            resourceInputs["resourceId"] = state?.resourceId;
            resourceInputs["token"] = state?.token;
            resourceInputs["webhookId"] = state?.webhookId;
            resourceInputs["webhookType"] = state?.webhookType;
        } else {
            const args = argsOrState as WebhookArgs | undefined;
            if (args?.endpointId === undefined && !opts.urn) {
                throw new Error("Missing required property 'endpointId'");
            }
            if (args?.resourceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceId'");
            }
            if (args?.webhookType === undefined && !opts.urn) {
                throw new Error("Missing required property 'webhookType'");
            }
            resourceInputs["endpointId"] = args?.endpointId;
            resourceInputs["registryId"] = args?.registryId;
            resourceInputs["resourceId"] = args?.resourceId;
            resourceInputs["webhookId"] = args?.webhookId;
            resourceInputs["webhookType"] = args?.webhookType;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Webhook.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Webhook resources.
 */
export interface WebhookState {
    /**
     * Identifier of the Portainer environment (endpoint) the webhook is bound to. Changing this value forces resource recreation.
     */
    endpointId?: pulumi.Input<number | undefined>;
    /**
     * Identifier of the Portainer registry associated with this webhook. Used when the webhook triggers actions on images from that registry.
     */
    registryId?: pulumi.Input<number | undefined>;
    /**
     * Identifier of the target resource (e.g. service ID) the webhook will act upon. Changing this value forces resource recreation.
     */
    resourceId?: pulumi.Input<string | undefined>;
    /**
     * Webhook token generated by Portainer. Appended to the webhook URL to authenticate trigger calls.
     */
    token?: pulumi.Input<string | undefined>;
    webhookId?: pulumi.Input<string | undefined>;
    /**
     * Type of webhook in Portainer (e.g. 1 = service webhook, 2 = container webhook). Changing this value forces resource recreation.
     */
    webhookType?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a Webhook resource.
 */
export interface WebhookArgs {
    /**
     * Identifier of the Portainer environment (endpoint) the webhook is bound to. Changing this value forces resource recreation.
     */
    endpointId: pulumi.Input<number>;
    /**
     * Identifier of the Portainer registry associated with this webhook. Used when the webhook triggers actions on images from that registry.
     */
    registryId?: pulumi.Input<number | undefined>;
    /**
     * Identifier of the target resource (e.g. service ID) the webhook will act upon. Changing this value forces resource recreation.
     */
    resourceId: pulumi.Input<string>;
    webhookId?: pulumi.Input<string | undefined>;
    /**
     * Type of webhook in Portainer (e.g. 1 = service webhook, 2 = container webhook). Changing this value forces resource recreation.
     */
    webhookType: pulumi.Input<number>;
}
