// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Action extends pulumi.CustomResource {
    /**
     * Get an existing Action resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ActionState, opts?: pulumi.CustomResourceOptions): Action {
        return new Action(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'posthog:index/action:Action';

    /**
     * Returns true if the given object is an instance of Action.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Action {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Action.__pulumiType;
    }

    /**
     * Action ID
     */
    declare public /*out*/ readonly actionId: pulumi.Output<number>;
    /**
     * Timestamp when the action was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    declare public readonly deleted: pulumi.Output<boolean>;
    /**
     * Action description
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Action name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Whether to post to Slack when the action is triggered
     */
    declare public readonly postToSlack: pulumi.Output<boolean>;
    /**
     * Project ID (environment) for this resource. Overrides the provider-level project_id.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Slack message format string
     */
    declare public readonly slackMessageFormat: pulumi.Output<string>;
    /**
     * JSON-encoded array of action step objects. See the [ActionStep schema](https://posthog.com/docs/api/actions) for available fields.
     */
    declare public readonly stepsJson: pulumi.Output<string>;
    /**
     * Set of tags for the action
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;

    /**
     * Create a Action resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ActionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ActionArgs | ActionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ActionState | undefined;
            resourceInputs["actionId"] = state?.actionId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["deleted"] = state?.deleted;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["postToSlack"] = state?.postToSlack;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["slackMessageFormat"] = state?.slackMessageFormat;
            resourceInputs["stepsJson"] = state?.stepsJson;
            resourceInputs["tags"] = state?.tags;
        } else {
            const args = argsOrState as ActionArgs | undefined;
            resourceInputs["deleted"] = args?.deleted;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["postToSlack"] = args?.postToSlack;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["slackMessageFormat"] = args?.slackMessageFormat;
            resourceInputs["stepsJson"] = args?.stepsJson;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["actionId"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Action.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Action resources.
 */
export interface ActionState {
    /**
     * Action ID
     */
    actionId?: pulumi.Input<number>;
    /**
     * Timestamp when the action was created.
     */
    createdAt?: pulumi.Input<string>;
    deleted?: pulumi.Input<boolean>;
    /**
     * Action description
     */
    description?: pulumi.Input<string>;
    /**
     * Action name
     */
    name?: pulumi.Input<string>;
    /**
     * Whether to post to Slack when the action is triggered
     */
    postToSlack?: pulumi.Input<boolean>;
    /**
     * Project ID (environment) for this resource. Overrides the provider-level project_id.
     */
    projectId?: pulumi.Input<string>;
    /**
     * Slack message format string
     */
    slackMessageFormat?: pulumi.Input<string>;
    /**
     * JSON-encoded array of action step objects. See the [ActionStep schema](https://posthog.com/docs/api/actions) for available fields.
     */
    stepsJson?: pulumi.Input<string>;
    /**
     * Set of tags for the action
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a Action resource.
 */
export interface ActionArgs {
    deleted?: pulumi.Input<boolean>;
    /**
     * Action description
     */
    description?: pulumi.Input<string>;
    /**
     * Action name
     */
    name?: pulumi.Input<string>;
    /**
     * Whether to post to Slack when the action is triggered
     */
    postToSlack?: pulumi.Input<boolean>;
    /**
     * Project ID (environment) for this resource. Overrides the provider-level project_id.
     */
    projectId?: pulumi.Input<string>;
    /**
     * Slack message format string
     */
    slackMessageFormat?: pulumi.Input<string>;
    /**
     * JSON-encoded array of action step objects. See the [ActionStep schema](https://posthog.com/docs/api/actions) for available fields.
     */
    stepsJson?: pulumi.Input<string>;
    /**
     * Set of tags for the action
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}
