// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ExternalDataSource extends pulumi.CustomResource {
    /**
     * Get an existing ExternalDataSource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ExternalDataSourceState, opts?: pulumi.CustomResourceOptions): ExternalDataSource {
        return new ExternalDataSource(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'posthog:index/externalDataSource:ExternalDataSource';

    /**
     * Returns true if the given object is an instance of ExternalDataSource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ExternalDataSource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ExternalDataSource.__pulumiType;
    }

    /**
     * Timestamp when the source was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * JSON-encoded connection configuration for the source. Shape depends on <span pulumi-lang-nodejs="`sourceType`" pulumi-lang-dotnet="`SourceType`" pulumi-lang-go="`sourceType`" pulumi-lang-python="`source_type`" pulumi-lang-yaml="`sourceType`" pulumi-lang-java="`sourceType`" pulumi-lang-hcl="`source_type`">`sourceType`</span>. For example Postgres expects `{host, port, database, user, password, schema}`; Stripe expects `{stripe_account_id, stripe_secret_key}`. PostHog redacts secret values when reading, so the plan value is preserved in state. On import, redacted secrets will appear in state until the next apply with real values.
     */
    declare public readonly jobInputsJson: pulumi.Output<string>;
    /**
     * Timestamp of the most recent sync run.
     */
    declare public /*out*/ readonly lastRunAt: pulumi.Output<string>;
    /**
     * Optional prefix for synced table names (e.g. `stripe_prod_`). Useful when connecting multiple sources of the same type. The PostHog update endpoint silently ignores prefix changes for non-direct-postgres sources, so this resource treats it as RequiresReplace.
     */
    declare public readonly prefix: pulumi.Output<string | undefined>;
    /**
     * Project ID (environment) for this resource. Overrides the provider-level project_id.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * List of table names to sync from the source (e.g. `["users", "orders"]`). PostHog discovers available tables from the source; these must match discovered table names. The source-level update endpoint cannot edit the schema list, so changes force destroy+recreate.
     */
    declare public readonly schemas: pulumi.Output<string[]>;
    /**
     * Source type recognised by the PostHog data warehouse (e.g. `Stripe`, `Postgres`, `Snowflake`, `BigQuery`, `Hubspot`). PostHog defines the set of accepted values and may add new types over time; see the PostHog data warehouse docs for the current list. Cannot be changed after creation.
     */
    declare public readonly sourceType: pulumi.Output<string>;
    /**
     * Current status reported by PostHog (e.g. `Running`, `Completed`, `Error`).
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Sync cadence reported by PostHog. Defaults to 6 hours (5 minutes for CDC schemas) and is not configurable on this resource — the create endpoint does not accept a sync frequency. Reports the value of the first schema; sources with mixed schedules will see this flap. Modify per-schema cadence via the PostHog UI or schemas API.
     */
    declare public /*out*/ readonly syncFrequency: pulumi.Output<string>;

    /**
     * Create a ExternalDataSource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ExternalDataSourceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ExternalDataSourceArgs | ExternalDataSourceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ExternalDataSourceState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["jobInputsJson"] = state?.jobInputsJson;
            resourceInputs["lastRunAt"] = state?.lastRunAt;
            resourceInputs["prefix"] = state?.prefix;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["schemas"] = state?.schemas;
            resourceInputs["sourceType"] = state?.sourceType;
            resourceInputs["status"] = state?.status;
            resourceInputs["syncFrequency"] = state?.syncFrequency;
        } else {
            const args = argsOrState as ExternalDataSourceArgs | undefined;
            if (args?.jobInputsJson === undefined && !opts.urn) {
                throw new Error("Missing required property 'jobInputsJson'");
            }
            if (args?.schemas === undefined && !opts.urn) {
                throw new Error("Missing required property 'schemas'");
            }
            if (args?.sourceType === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourceType'");
            }
            resourceInputs["jobInputsJson"] = args?.jobInputsJson ? pulumi.secret(args.jobInputsJson) : undefined;
            resourceInputs["prefix"] = args?.prefix;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["schemas"] = args?.schemas;
            resourceInputs["sourceType"] = args?.sourceType;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["lastRunAt"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["syncFrequency"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["jobInputsJson"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ExternalDataSource.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ExternalDataSource resources.
 */
export interface ExternalDataSourceState {
    /**
     * Timestamp when the source was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * JSON-encoded connection configuration for the source. Shape depends on <span pulumi-lang-nodejs="`sourceType`" pulumi-lang-dotnet="`SourceType`" pulumi-lang-go="`sourceType`" pulumi-lang-python="`source_type`" pulumi-lang-yaml="`sourceType`" pulumi-lang-java="`sourceType`" pulumi-lang-hcl="`source_type`">`sourceType`</span>. For example Postgres expects `{host, port, database, user, password, schema}`; Stripe expects `{stripe_account_id, stripe_secret_key}`. PostHog redacts secret values when reading, so the plan value is preserved in state. On import, redacted secrets will appear in state until the next apply with real values.
     */
    jobInputsJson?: pulumi.Input<string | undefined>;
    /**
     * Timestamp of the most recent sync run.
     */
    lastRunAt?: pulumi.Input<string | undefined>;
    /**
     * Optional prefix for synced table names (e.g. `stripe_prod_`). Useful when connecting multiple sources of the same type. The PostHog update endpoint silently ignores prefix changes for non-direct-postgres sources, so this resource treats it as RequiresReplace.
     */
    prefix?: pulumi.Input<string | undefined>;
    /**
     * Project ID (environment) for this resource. Overrides the provider-level project_id.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * List of table names to sync from the source (e.g. `["users", "orders"]`). PostHog discovers available tables from the source; these must match discovered table names. The source-level update endpoint cannot edit the schema list, so changes force destroy+recreate.
     */
    schemas?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Source type recognised by the PostHog data warehouse (e.g. `Stripe`, `Postgres`, `Snowflake`, `BigQuery`, `Hubspot`). PostHog defines the set of accepted values and may add new types over time; see the PostHog data warehouse docs for the current list. Cannot be changed after creation.
     */
    sourceType?: pulumi.Input<string | undefined>;
    /**
     * Current status reported by PostHog (e.g. `Running`, `Completed`, `Error`).
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * Sync cadence reported by PostHog. Defaults to 6 hours (5 minutes for CDC schemas) and is not configurable on this resource — the create endpoint does not accept a sync frequency. Reports the value of the first schema; sources with mixed schedules will see this flap. Modify per-schema cadence via the PostHog UI or schemas API.
     */
    syncFrequency?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ExternalDataSource resource.
 */
export interface ExternalDataSourceArgs {
    /**
     * JSON-encoded connection configuration for the source. Shape depends on <span pulumi-lang-nodejs="`sourceType`" pulumi-lang-dotnet="`SourceType`" pulumi-lang-go="`sourceType`" pulumi-lang-python="`source_type`" pulumi-lang-yaml="`sourceType`" pulumi-lang-java="`sourceType`" pulumi-lang-hcl="`source_type`">`sourceType`</span>. For example Postgres expects `{host, port, database, user, password, schema}`; Stripe expects `{stripe_account_id, stripe_secret_key}`. PostHog redacts secret values when reading, so the plan value is preserved in state. On import, redacted secrets will appear in state until the next apply with real values.
     */
    jobInputsJson: pulumi.Input<string>;
    /**
     * Optional prefix for synced table names (e.g. `stripe_prod_`). Useful when connecting multiple sources of the same type. The PostHog update endpoint silently ignores prefix changes for non-direct-postgres sources, so this resource treats it as RequiresReplace.
     */
    prefix?: pulumi.Input<string | undefined>;
    /**
     * Project ID (environment) for this resource. Overrides the provider-level project_id.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * List of table names to sync from the source (e.g. `["users", "orders"]`). PostHog discovers available tables from the source; these must match discovered table names. The source-level update endpoint cannot edit the schema list, so changes force destroy+recreate.
     */
    schemas: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Source type recognised by the PostHog data warehouse (e.g. `Stripe`, `Postgres`, `Snowflake`, `BigQuery`, `Hubspot`). PostHog defines the set of accepted values and may add new types over time; see the PostHog data warehouse docs for the current list. Cannot be changed after creation.
     */
    sourceType: pulumi.Input<string>;
}
