// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRole(args: GetRoleArgs, opts?: pulumi.InvokeOptions): Promise<GetRoleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("posthog:index/getRole:getRole", {
        "name": args.name,
        "organizationId": args.organizationId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRole.
 */
export interface GetRoleArgs {
    name: string;
    organizationId?: string;
}

/**
 * A collection of values returned by getRole.
 */
export interface GetRoleResult {
    readonly createdAt: string;
    readonly createdBy: string;
    readonly id: string;
    readonly name: string;
    readonly organizationId: string;
}
export function getRoleOutput(args: GetRoleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRoleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("posthog:index/getRole:getRole", {
        "name": args.name,
        "organizationId": args.organizationId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRole.
 */
export interface GetRoleOutputArgs {
    name: pulumi.Input<string>;
    organizationId?: pulumi.Input<string>;
}
