// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AlertArgs, AlertState } from "./alert";
export type Alert = import("./alert").Alert;
export const Alert: typeof import("./alert").Alert = null as any;
utilities.lazyLoad(exports, ["Alert"], () => require("./alert"));

export { DashboardArgs, DashboardState } from "./dashboard";
export type Dashboard = import("./dashboard").Dashboard;
export const Dashboard: typeof import("./dashboard").Dashboard = null as any;
utilities.lazyLoad(exports, ["Dashboard"], () => require("./dashboard"));

export { FeatureFlagArgs, FeatureFlagState } from "./featureFlag";
export type FeatureFlag = import("./featureFlag").FeatureFlag;
export const FeatureFlag: typeof import("./featureFlag").FeatureFlag = null as any;
utilities.lazyLoad(exports, ["FeatureFlag"], () => require("./featureFlag"));

export { HogFunctionArgs, HogFunctionState } from "./hogFunction";
export type HogFunction = import("./hogFunction").HogFunction;
export const HogFunction: typeof import("./hogFunction").HogFunction = null as any;
utilities.lazyLoad(exports, ["HogFunction"], () => require("./hogFunction"));

export { InsightArgs, InsightState } from "./insight";
export type Insight = import("./insight").Insight;
export const Insight: typeof import("./insight").Insight = null as any;
utilities.lazyLoad(exports, ["Insight"], () => require("./insight"));

export * from "./provider";
import { Provider } from "./provider";


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "posthog:index/alert:Alert":
                return new Alert(name, <any>undefined, { urn })
            case "posthog:index/dashboard:Dashboard":
                return new Dashboard(name, <any>undefined, { urn })
            case "posthog:index/featureFlag:FeatureFlag":
                return new FeatureFlag(name, <any>undefined, { urn })
            case "posthog:index/hogFunction:HogFunction":
                return new HogFunction(name, <any>undefined, { urn })
            case "posthog:index/insight:Insight":
                return new Insight(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("posthog", "index/alert", _module)
pulumi.runtime.registerResourceModule("posthog", "index/dashboard", _module)
pulumi.runtime.registerResourceModule("posthog", "index/featureFlag", _module)
pulumi.runtime.registerResourceModule("posthog", "index/hogFunction", _module)
pulumi.runtime.registerResourceModule("posthog", "index/insight", _module)
pulumi.runtime.registerResourcePackage("posthog", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:posthog") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
