// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RoleMembership extends pulumi.CustomResource {
    /**
     * Get an existing RoleMembership resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RoleMembershipState, opts?: pulumi.CustomResourceOptions): RoleMembership {
        return new RoleMembership(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'posthog:index/roleMembership:RoleMembership';

    /**
     * Returns true if the given object is an instance of RoleMembership.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RoleMembership {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RoleMembership.__pulumiType;
    }

    /**
     * Timestamp when the user joined the role.
     */
    declare public /*out*/ readonly joinedAt: pulumi.Output<string>;
    /**
     * Organization ID for this resource. Overrides the provider-level organization_id.
     */
    declare public readonly organizationId: pulumi.Output<string>;
    /**
     * The UUID of the role.
     */
    declare public readonly roleId: pulumi.Output<string>;
    /**
     * The email address of the user.
     */
    declare public /*out*/ readonly userEmail: pulumi.Output<string>;
    /**
     * The UUID of the user to add to the role.
     */
    declare public readonly userUuid: pulumi.Output<string>;

    /**
     * Create a RoleMembership resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RoleMembershipArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RoleMembershipArgs | RoleMembershipState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RoleMembershipState | undefined;
            resourceInputs["joinedAt"] = state?.joinedAt;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["roleId"] = state?.roleId;
            resourceInputs["userEmail"] = state?.userEmail;
            resourceInputs["userUuid"] = state?.userUuid;
        } else {
            const args = argsOrState as RoleMembershipArgs | undefined;
            if (args?.roleId === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleId'");
            }
            if (args?.userUuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'userUuid'");
            }
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["roleId"] = args?.roleId;
            resourceInputs["userUuid"] = args?.userUuid;
            resourceInputs["joinedAt"] = undefined /*out*/;
            resourceInputs["userEmail"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RoleMembership.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RoleMembership resources.
 */
export interface RoleMembershipState {
    /**
     * Timestamp when the user joined the role.
     */
    joinedAt?: pulumi.Input<string>;
    /**
     * Organization ID for this resource. Overrides the provider-level organization_id.
     */
    organizationId?: pulumi.Input<string>;
    /**
     * The UUID of the role.
     */
    roleId?: pulumi.Input<string>;
    /**
     * The email address of the user.
     */
    userEmail?: pulumi.Input<string>;
    /**
     * The UUID of the user to add to the role.
     */
    userUuid?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RoleMembership resource.
 */
export interface RoleMembershipArgs {
    /**
     * Organization ID for this resource. Overrides the provider-level organization_id.
     */
    organizationId?: pulumi.Input<string>;
    /**
     * The UUID of the role.
     */
    roleId: pulumi.Input<string>;
    /**
     * The UUID of the user to add to the role.
     */
    userUuid: pulumi.Input<string>;
}
