// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NotificationService extends pulumi.CustomResource {
    /**
     * Get an existing NotificationService resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NotificationServiceState, opts?: pulumi.CustomResourceOptions): NotificationService {
        return new NotificationService(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'buildkite:index/notificationService:NotificationService';

    /**
     * Returns true if the given object is an instance of NotificationService.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NotificationService {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NotificationService.__pulumiType;
    }

    /**
     * Settings for the <span pulumi-lang-nodejs="`awsEventBridge`" pulumi-lang-dotnet="`AwsEventBridge`" pulumi-lang-go="`awsEventBridge`" pulumi-lang-python="`aws_event_bridge`" pulumi-lang-yaml="`awsEventBridge`" pulumi-lang-java="`awsEventBridge`" pulumi-lang-hcl="`aws_event_bridge`">`awsEventBridge`</span> provider.
     */
    declare public readonly awsEventBridge: pulumi.Output<outputs.NotificationServiceAwsEventBridge | undefined>;
    /**
     * A branch pattern restricting which builds produce notifications. Not supported for <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> or <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services.
     */
    declare public readonly branchConfiguration: pulumi.Output<string | undefined>;
    /**
     * The time when the notification service was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Settings for the <span pulumi-lang-nodejs="`datadogPipelineVisibility`" pulumi-lang-dotnet="`DatadogPipelineVisibility`" pulumi-lang-go="`datadogPipelineVisibility`" pulumi-lang-python="`datadog_pipeline_visibility`" pulumi-lang-yaml="`datadogPipelineVisibility`" pulumi-lang-java="`datadogPipelineVisibility`" pulumi-lang-hcl="`datadog_pipeline_visibility`">`datadogPipelineVisibility`</span> provider.
     */
    declare public readonly datadogPipelineVisibility: pulumi.Output<outputs.NotificationServiceDatadogPipelineVisibility | undefined>;
    /**
     * A description of the notification service.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Whether the notification service is enabled. Defaults to true.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * The GraphQL ID of the notification service, when its provider has a GraphQL node type.
     */
    declare public /*out*/ readonly graphqlId: pulumi.Output<string>;
    /**
     * Settings for the <span pulumi-lang-nodejs="`openTelemetryTracing`" pulumi-lang-dotnet="`OpenTelemetryTracing`" pulumi-lang-go="`openTelemetryTracing`" pulumi-lang-python="`open_telemetry_tracing`" pulumi-lang-yaml="`openTelemetryTracing`" pulumi-lang-java="`openTelemetryTracing`" pulumi-lang-hcl="`open_telemetry_tracing`">`openTelemetryTracing`</span> provider.
     */
    declare public readonly openTelemetryTracing: pulumi.Output<outputs.NotificationServiceOpenTelemetryTracing | undefined>;
    /**
     * The notification provider type. OAuth-managed <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> and <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services can be imported but cannot be created with this resource. Legacy <span pulumi-lang-nodejs="`slack`" pulumi-lang-dotnet="`Slack`" pulumi-lang-go="`slack`" pulumi-lang-python="`slack`" pulumi-lang-yaml="`slack`" pulumi-lang-java="`slack`" pulumi-lang-hcl="`slack`">`slack`</span> services are not supported.
     */
    declare public readonly providerType: pulumi.Output<string>;
    /**
     * Which resources the service applies to. Defaults to <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>. Only <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span> is supported for <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> and <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services.
     */
    declare public readonly scope: pulumi.Output<string>;
    /**
     * The project, team, or cluster UUIDs selected by a `some_*` scope. Not supported for <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> or <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services.
     */
    declare public readonly scopeUuids: pulumi.Output<string[] | undefined>;
    /**
     * Settings for the <span pulumi-lang-nodejs="`webhook`" pulumi-lang-dotnet="`Webhook`" pulumi-lang-go="`webhook`" pulumi-lang-python="`webhook`" pulumi-lang-yaml="`webhook`" pulumi-lang-java="`webhook`" pulumi-lang-hcl="`webhook`">`webhook`</span> provider.
     */
    declare public readonly webhook: pulumi.Output<outputs.NotificationServiceWebhook | undefined>;

    /**
     * Create a NotificationService resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NotificationServiceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NotificationServiceArgs | NotificationServiceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NotificationServiceState | undefined;
            resourceInputs["awsEventBridge"] = state?.awsEventBridge;
            resourceInputs["branchConfiguration"] = state?.branchConfiguration;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["datadogPipelineVisibility"] = state?.datadogPipelineVisibility;
            resourceInputs["description"] = state?.description;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["graphqlId"] = state?.graphqlId;
            resourceInputs["openTelemetryTracing"] = state?.openTelemetryTracing;
            resourceInputs["providerType"] = state?.providerType;
            resourceInputs["scope"] = state?.scope;
            resourceInputs["scopeUuids"] = state?.scopeUuids;
            resourceInputs["webhook"] = state?.webhook;
        } else {
            const args = argsOrState as NotificationServiceArgs | undefined;
            if (args?.providerType === undefined && !opts.urn) {
                throw new Error("Missing required property 'providerType'");
            }
            resourceInputs["awsEventBridge"] = args?.awsEventBridge;
            resourceInputs["branchConfiguration"] = args?.branchConfiguration;
            resourceInputs["datadogPipelineVisibility"] = args?.datadogPipelineVisibility;
            resourceInputs["description"] = args?.description;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["openTelemetryTracing"] = args?.openTelemetryTracing;
            resourceInputs["providerType"] = args?.providerType;
            resourceInputs["scope"] = args?.scope;
            resourceInputs["scopeUuids"] = args?.scopeUuids;
            resourceInputs["webhook"] = args?.webhook;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["graphqlId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NotificationService.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering NotificationService resources.
 */
export interface NotificationServiceState {
    /**
     * Settings for the <span pulumi-lang-nodejs="`awsEventBridge`" pulumi-lang-dotnet="`AwsEventBridge`" pulumi-lang-go="`awsEventBridge`" pulumi-lang-python="`aws_event_bridge`" pulumi-lang-yaml="`awsEventBridge`" pulumi-lang-java="`awsEventBridge`" pulumi-lang-hcl="`aws_event_bridge`">`awsEventBridge`</span> provider.
     */
    awsEventBridge?: pulumi.Input<inputs.NotificationServiceAwsEventBridge | undefined>;
    /**
     * A branch pattern restricting which builds produce notifications. Not supported for <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> or <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services.
     */
    branchConfiguration?: pulumi.Input<string | undefined>;
    /**
     * The time when the notification service was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Settings for the <span pulumi-lang-nodejs="`datadogPipelineVisibility`" pulumi-lang-dotnet="`DatadogPipelineVisibility`" pulumi-lang-go="`datadogPipelineVisibility`" pulumi-lang-python="`datadog_pipeline_visibility`" pulumi-lang-yaml="`datadogPipelineVisibility`" pulumi-lang-java="`datadogPipelineVisibility`" pulumi-lang-hcl="`datadog_pipeline_visibility`">`datadogPipelineVisibility`</span> provider.
     */
    datadogPipelineVisibility?: pulumi.Input<inputs.NotificationServiceDatadogPipelineVisibility | undefined>;
    /**
     * A description of the notification service.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the notification service is enabled. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The GraphQL ID of the notification service, when its provider has a GraphQL node type.
     */
    graphqlId?: pulumi.Input<string | undefined>;
    /**
     * Settings for the <span pulumi-lang-nodejs="`openTelemetryTracing`" pulumi-lang-dotnet="`OpenTelemetryTracing`" pulumi-lang-go="`openTelemetryTracing`" pulumi-lang-python="`open_telemetry_tracing`" pulumi-lang-yaml="`openTelemetryTracing`" pulumi-lang-java="`openTelemetryTracing`" pulumi-lang-hcl="`open_telemetry_tracing`">`openTelemetryTracing`</span> provider.
     */
    openTelemetryTracing?: pulumi.Input<inputs.NotificationServiceOpenTelemetryTracing | undefined>;
    /**
     * The notification provider type. OAuth-managed <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> and <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services can be imported but cannot be created with this resource. Legacy <span pulumi-lang-nodejs="`slack`" pulumi-lang-dotnet="`Slack`" pulumi-lang-go="`slack`" pulumi-lang-python="`slack`" pulumi-lang-yaml="`slack`" pulumi-lang-java="`slack`" pulumi-lang-hcl="`slack`">`slack`</span> services are not supported.
     */
    providerType?: pulumi.Input<string | undefined>;
    /**
     * Which resources the service applies to. Defaults to <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>. Only <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span> is supported for <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> and <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services.
     */
    scope?: pulumi.Input<string | undefined>;
    /**
     * The project, team, or cluster UUIDs selected by a `some_*` scope. Not supported for <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> or <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services.
     */
    scopeUuids?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Settings for the <span pulumi-lang-nodejs="`webhook`" pulumi-lang-dotnet="`Webhook`" pulumi-lang-go="`webhook`" pulumi-lang-python="`webhook`" pulumi-lang-yaml="`webhook`" pulumi-lang-java="`webhook`" pulumi-lang-hcl="`webhook`">`webhook`</span> provider.
     */
    webhook?: pulumi.Input<inputs.NotificationServiceWebhook | undefined>;
}

/**
 * The set of arguments for constructing a NotificationService resource.
 */
export interface NotificationServiceArgs {
    /**
     * Settings for the <span pulumi-lang-nodejs="`awsEventBridge`" pulumi-lang-dotnet="`AwsEventBridge`" pulumi-lang-go="`awsEventBridge`" pulumi-lang-python="`aws_event_bridge`" pulumi-lang-yaml="`awsEventBridge`" pulumi-lang-java="`awsEventBridge`" pulumi-lang-hcl="`aws_event_bridge`">`awsEventBridge`</span> provider.
     */
    awsEventBridge?: pulumi.Input<inputs.NotificationServiceAwsEventBridge | undefined>;
    /**
     * A branch pattern restricting which builds produce notifications. Not supported for <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> or <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services.
     */
    branchConfiguration?: pulumi.Input<string | undefined>;
    /**
     * Settings for the <span pulumi-lang-nodejs="`datadogPipelineVisibility`" pulumi-lang-dotnet="`DatadogPipelineVisibility`" pulumi-lang-go="`datadogPipelineVisibility`" pulumi-lang-python="`datadog_pipeline_visibility`" pulumi-lang-yaml="`datadogPipelineVisibility`" pulumi-lang-java="`datadogPipelineVisibility`" pulumi-lang-hcl="`datadog_pipeline_visibility`">`datadogPipelineVisibility`</span> provider.
     */
    datadogPipelineVisibility?: pulumi.Input<inputs.NotificationServiceDatadogPipelineVisibility | undefined>;
    /**
     * A description of the notification service.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Whether the notification service is enabled. Defaults to true.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Settings for the <span pulumi-lang-nodejs="`openTelemetryTracing`" pulumi-lang-dotnet="`OpenTelemetryTracing`" pulumi-lang-go="`openTelemetryTracing`" pulumi-lang-python="`open_telemetry_tracing`" pulumi-lang-yaml="`openTelemetryTracing`" pulumi-lang-java="`openTelemetryTracing`" pulumi-lang-hcl="`open_telemetry_tracing`">`openTelemetryTracing`</span> provider.
     */
    openTelemetryTracing?: pulumi.Input<inputs.NotificationServiceOpenTelemetryTracing | undefined>;
    /**
     * The notification provider type. OAuth-managed <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> and <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services can be imported but cannot be created with this resource. Legacy <span pulumi-lang-nodejs="`slack`" pulumi-lang-dotnet="`Slack`" pulumi-lang-go="`slack`" pulumi-lang-python="`slack`" pulumi-lang-yaml="`slack`" pulumi-lang-java="`slack`" pulumi-lang-hcl="`slack`">`slack`</span> services are not supported.
     */
    providerType: pulumi.Input<string>;
    /**
     * Which resources the service applies to. Defaults to <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span>. Only <span pulumi-lang-nodejs="`all`" pulumi-lang-dotnet="`All`" pulumi-lang-go="`all`" pulumi-lang-python="`all`" pulumi-lang-yaml="`all`" pulumi-lang-java="`all`" pulumi-lang-hcl="`all`">`all`</span> is supported for <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> and <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services.
     */
    scope?: pulumi.Input<string | undefined>;
    /**
     * The project, team, or cluster UUIDs selected by a `some_*` scope. Not supported for <span pulumi-lang-nodejs="`linear`" pulumi-lang-dotnet="`Linear`" pulumi-lang-go="`linear`" pulumi-lang-python="`linear`" pulumi-lang-yaml="`linear`" pulumi-lang-java="`linear`" pulumi-lang-hcl="`linear`">`linear`</span> or <span pulumi-lang-nodejs="`slackWorkspace`" pulumi-lang-dotnet="`SlackWorkspace`" pulumi-lang-go="`slackWorkspace`" pulumi-lang-python="`slack_workspace`" pulumi-lang-yaml="`slackWorkspace`" pulumi-lang-java="`slackWorkspace`" pulumi-lang-hcl="`slack_workspace`">`slackWorkspace`</span> services.
     */
    scopeUuids?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Settings for the <span pulumi-lang-nodejs="`webhook`" pulumi-lang-dotnet="`Webhook`" pulumi-lang-go="`webhook`" pulumi-lang-python="`webhook`" pulumi-lang-yaml="`webhook`" pulumi-lang-java="`webhook`" pulumi-lang-hcl="`webhook`">`webhook`</span> provider.
     */
    webhook?: pulumi.Input<inputs.NotificationServiceWebhook | undefined>;
}
