// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OrganizationPipelineSettings extends pulumi.CustomResource {
    /**
     * Get an existing OrganizationPipelineSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrganizationPipelineSettingsState, opts?: pulumi.CustomResourceOptions): OrganizationPipelineSettings {
        return new OrganizationPipelineSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'buildkite:index/organizationPipelineSettings:OrganizationPipelineSettings';

    /**
     * Returns true if the given object is an instance of OrganizationPipelineSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrganizationPipelineSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrganizationPipelineSettings.__pulumiType;
    }

    /**
     * Whether exporting build data is available on this organization's billing plan.
     */
    declare public /*out*/ readonly buildExportAvailable: pulumi.Output<boolean>;
    /**
     * The bucket to export build data to, given as a bare bucket name without a scheme. Set this and <span pulumi-lang-nodejs="`buildExportStrategyId`" pulumi-lang-dotnet="`BuildExportStrategyId`" pulumi-lang-go="`buildExportStrategyId`" pulumi-lang-python="`build_export_strategy_id`" pulumi-lang-yaml="`buildExportStrategyId`" pulumi-lang-java="`buildExportStrategyId`" pulumi-lang-hcl="`build_export_strategy_id`">`buildExportStrategyId`</span> to empty strings to stop exporting build data. If both are omitted, the current setting is left unchanged.
     *
     * > Exporting build data is a plan-gated feature. Read <span pulumi-lang-nodejs="`buildExportAvailable`" pulumi-lang-dotnet="`BuildExportAvailable`" pulumi-lang-go="`buildExportAvailable`" pulumi-lang-python="`build_export_available`" pulumi-lang-yaml="`buildExportAvailable`" pulumi-lang-java="`buildExportAvailable`" pulumi-lang-hcl="`build_export_available`">`buildExportAvailable`</span> to see whether it is available on this organization's plan.
     */
    declare public readonly buildExportLocation: pulumi.Output<string>;
    /**
     * The strategy used to export build data, which decides the scheme the bucket is addressed with. The strategies this organization accepts are listed in <span pulumi-lang-nodejs="`buildExportSupportedStrategies`" pulumi-lang-dotnet="`BuildExportSupportedStrategies`" pulumi-lang-go="`buildExportSupportedStrategies`" pulumi-lang-python="`build_export_supported_strategies`" pulumi-lang-yaml="`buildExportSupportedStrategies`" pulumi-lang-java="`buildExportSupportedStrategies`" pulumi-lang-hcl="`build_export_supported_strategies`">`buildExportSupportedStrategies`</span>, and are usually <span pulumi-lang-nodejs="`s3`" pulumi-lang-dotnet="`S3`" pulumi-lang-go="`s3`" pulumi-lang-python="`s3`" pulumi-lang-yaml="`s3`" pulumi-lang-java="`s3`" pulumi-lang-hcl="`s3`">`s3`</span> and <span pulumi-lang-nodejs="`gcs`" pulumi-lang-dotnet="`Gcs`" pulumi-lang-go="`gcs`" pulumi-lang-python="`gcs`" pulumi-lang-yaml="`gcs`" pulumi-lang-java="`gcs`" pulumi-lang-hcl="`gcs`">`gcs`</span>. Always configured alongside <span pulumi-lang-nodejs="`buildExportLocation`" pulumi-lang-dotnet="`BuildExportLocation`" pulumi-lang-go="`buildExportLocation`" pulumi-lang-python="`build_export_location`" pulumi-lang-yaml="`buildExportLocation`" pulumi-lang-java="`buildExportLocation`" pulumi-lang-hcl="`build_export_location`">`buildExportLocation`</span>.
     */
    declare public readonly buildExportStrategyId: pulumi.Output<string>;
    /**
     * The build export strategies that <span pulumi-lang-nodejs="`buildExportStrategyId`" pulumi-lang-dotnet="`BuildExportStrategyId`" pulumi-lang-go="`buildExportStrategyId`" pulumi-lang-python="`build_export_strategy_id`" pulumi-lang-yaml="`buildExportStrategyId`" pulumi-lang-java="`buildExportStrategyId`" pulumi-lang-hcl="`build_export_strategy_id`">`buildExportStrategyId`</span> accepts.
     */
    declare public /*out*/ readonly buildExportSupportedStrategies: pulumi.Output<string[]>;
    /**
     * The default branch that new pipelines in the organization are created with. If omitted, the current setting is left unchanged.
     */
    declare public readonly defaultBranch: pulumi.Output<string>;
    /**
     * The UUID of the cluster that new pipelines in the organization are created in. Set this to an empty string to leave new pipelines without a default cluster. If omitted, the current setting is left unchanged.
     */
    declare public readonly defaultClusterId: pulumi.Output<string>;
    /**
     * The default command timeout, in minutes, applied to jobs that do not set their own. If omitted, the current setting is left unchanged.
     */
    declare public readonly defaultTimeoutInMinutes: pulumi.Output<number>;
    /**
     * Whether remote access to hosted agents is enabled, which covers SSH access to all hosted agents and VNC access to supported macOS hosted jobs. If omitted, the current setting is left unchanged.
     */
    declare public readonly hostedAgentsTerminalAccessEnabled: pulumi.Output<boolean>;
    /**
     * The longest command timeout, in minutes, that any pipeline in the organization may set. If omitted, the current setting is left unchanged.
     */
    declare public readonly maximumTimeoutInMinutes: pulumi.Output<number>;
    /**
     * Whether members of the organization can create public pipelines. If omitted, the current setting is left unchanged.
     */
    declare public readonly publicPipelineCreationEnabled: pulumi.Output<boolean>;
    /**
     * How long a scheduled job waits, in minutes, before it expires without having started. Must be between 60 and 43200. If omitted, the current setting is left unchanged.
     */
    declare public readonly scheduledJobExpiryInMinutes: pulumi.Output<number>;

    /**
     * Create a OrganizationPipelineSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: OrganizationPipelineSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrganizationPipelineSettingsArgs | OrganizationPipelineSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrganizationPipelineSettingsState | undefined;
            resourceInputs["buildExportAvailable"] = state?.buildExportAvailable;
            resourceInputs["buildExportLocation"] = state?.buildExportLocation;
            resourceInputs["buildExportStrategyId"] = state?.buildExportStrategyId;
            resourceInputs["buildExportSupportedStrategies"] = state?.buildExportSupportedStrategies;
            resourceInputs["defaultBranch"] = state?.defaultBranch;
            resourceInputs["defaultClusterId"] = state?.defaultClusterId;
            resourceInputs["defaultTimeoutInMinutes"] = state?.defaultTimeoutInMinutes;
            resourceInputs["hostedAgentsTerminalAccessEnabled"] = state?.hostedAgentsTerminalAccessEnabled;
            resourceInputs["maximumTimeoutInMinutes"] = state?.maximumTimeoutInMinutes;
            resourceInputs["publicPipelineCreationEnabled"] = state?.publicPipelineCreationEnabled;
            resourceInputs["scheduledJobExpiryInMinutes"] = state?.scheduledJobExpiryInMinutes;
        } else {
            const args = argsOrState as OrganizationPipelineSettingsArgs | undefined;
            resourceInputs["buildExportLocation"] = args?.buildExportLocation;
            resourceInputs["buildExportStrategyId"] = args?.buildExportStrategyId;
            resourceInputs["defaultBranch"] = args?.defaultBranch;
            resourceInputs["defaultClusterId"] = args?.defaultClusterId;
            resourceInputs["defaultTimeoutInMinutes"] = args?.defaultTimeoutInMinutes;
            resourceInputs["hostedAgentsTerminalAccessEnabled"] = args?.hostedAgentsTerminalAccessEnabled;
            resourceInputs["maximumTimeoutInMinutes"] = args?.maximumTimeoutInMinutes;
            resourceInputs["publicPipelineCreationEnabled"] = args?.publicPipelineCreationEnabled;
            resourceInputs["scheduledJobExpiryInMinutes"] = args?.scheduledJobExpiryInMinutes;
            resourceInputs["buildExportAvailable"] = undefined /*out*/;
            resourceInputs["buildExportSupportedStrategies"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OrganizationPipelineSettings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OrganizationPipelineSettings resources.
 */
export interface OrganizationPipelineSettingsState {
    /**
     * Whether exporting build data is available on this organization's billing plan.
     */
    buildExportAvailable?: pulumi.Input<boolean | undefined>;
    /**
     * The bucket to export build data to, given as a bare bucket name without a scheme. Set this and <span pulumi-lang-nodejs="`buildExportStrategyId`" pulumi-lang-dotnet="`BuildExportStrategyId`" pulumi-lang-go="`buildExportStrategyId`" pulumi-lang-python="`build_export_strategy_id`" pulumi-lang-yaml="`buildExportStrategyId`" pulumi-lang-java="`buildExportStrategyId`" pulumi-lang-hcl="`build_export_strategy_id`">`buildExportStrategyId`</span> to empty strings to stop exporting build data. If both are omitted, the current setting is left unchanged.
     *
     * > Exporting build data is a plan-gated feature. Read <span pulumi-lang-nodejs="`buildExportAvailable`" pulumi-lang-dotnet="`BuildExportAvailable`" pulumi-lang-go="`buildExportAvailable`" pulumi-lang-python="`build_export_available`" pulumi-lang-yaml="`buildExportAvailable`" pulumi-lang-java="`buildExportAvailable`" pulumi-lang-hcl="`build_export_available`">`buildExportAvailable`</span> to see whether it is available on this organization's plan.
     */
    buildExportLocation?: pulumi.Input<string | undefined>;
    /**
     * The strategy used to export build data, which decides the scheme the bucket is addressed with. The strategies this organization accepts are listed in <span pulumi-lang-nodejs="`buildExportSupportedStrategies`" pulumi-lang-dotnet="`BuildExportSupportedStrategies`" pulumi-lang-go="`buildExportSupportedStrategies`" pulumi-lang-python="`build_export_supported_strategies`" pulumi-lang-yaml="`buildExportSupportedStrategies`" pulumi-lang-java="`buildExportSupportedStrategies`" pulumi-lang-hcl="`build_export_supported_strategies`">`buildExportSupportedStrategies`</span>, and are usually <span pulumi-lang-nodejs="`s3`" pulumi-lang-dotnet="`S3`" pulumi-lang-go="`s3`" pulumi-lang-python="`s3`" pulumi-lang-yaml="`s3`" pulumi-lang-java="`s3`" pulumi-lang-hcl="`s3`">`s3`</span> and <span pulumi-lang-nodejs="`gcs`" pulumi-lang-dotnet="`Gcs`" pulumi-lang-go="`gcs`" pulumi-lang-python="`gcs`" pulumi-lang-yaml="`gcs`" pulumi-lang-java="`gcs`" pulumi-lang-hcl="`gcs`">`gcs`</span>. Always configured alongside <span pulumi-lang-nodejs="`buildExportLocation`" pulumi-lang-dotnet="`BuildExportLocation`" pulumi-lang-go="`buildExportLocation`" pulumi-lang-python="`build_export_location`" pulumi-lang-yaml="`buildExportLocation`" pulumi-lang-java="`buildExportLocation`" pulumi-lang-hcl="`build_export_location`">`buildExportLocation`</span>.
     */
    buildExportStrategyId?: pulumi.Input<string | undefined>;
    /**
     * The build export strategies that <span pulumi-lang-nodejs="`buildExportStrategyId`" pulumi-lang-dotnet="`BuildExportStrategyId`" pulumi-lang-go="`buildExportStrategyId`" pulumi-lang-python="`build_export_strategy_id`" pulumi-lang-yaml="`buildExportStrategyId`" pulumi-lang-java="`buildExportStrategyId`" pulumi-lang-hcl="`build_export_strategy_id`">`buildExportStrategyId`</span> accepts.
     */
    buildExportSupportedStrategies?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The default branch that new pipelines in the organization are created with. If omitted, the current setting is left unchanged.
     */
    defaultBranch?: pulumi.Input<string | undefined>;
    /**
     * The UUID of the cluster that new pipelines in the organization are created in. Set this to an empty string to leave new pipelines without a default cluster. If omitted, the current setting is left unchanged.
     */
    defaultClusterId?: pulumi.Input<string | undefined>;
    /**
     * The default command timeout, in minutes, applied to jobs that do not set their own. If omitted, the current setting is left unchanged.
     */
    defaultTimeoutInMinutes?: pulumi.Input<number | undefined>;
    /**
     * Whether remote access to hosted agents is enabled, which covers SSH access to all hosted agents and VNC access to supported macOS hosted jobs. If omitted, the current setting is left unchanged.
     */
    hostedAgentsTerminalAccessEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * The longest command timeout, in minutes, that any pipeline in the organization may set. If omitted, the current setting is left unchanged.
     */
    maximumTimeoutInMinutes?: pulumi.Input<number | undefined>;
    /**
     * Whether members of the organization can create public pipelines. If omitted, the current setting is left unchanged.
     */
    publicPipelineCreationEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * How long a scheduled job waits, in minutes, before it expires without having started. Must be between 60 and 43200. If omitted, the current setting is left unchanged.
     */
    scheduledJobExpiryInMinutes?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a OrganizationPipelineSettings resource.
 */
export interface OrganizationPipelineSettingsArgs {
    /**
     * The bucket to export build data to, given as a bare bucket name without a scheme. Set this and <span pulumi-lang-nodejs="`buildExportStrategyId`" pulumi-lang-dotnet="`BuildExportStrategyId`" pulumi-lang-go="`buildExportStrategyId`" pulumi-lang-python="`build_export_strategy_id`" pulumi-lang-yaml="`buildExportStrategyId`" pulumi-lang-java="`buildExportStrategyId`" pulumi-lang-hcl="`build_export_strategy_id`">`buildExportStrategyId`</span> to empty strings to stop exporting build data. If both are omitted, the current setting is left unchanged.
     *
     * > Exporting build data is a plan-gated feature. Read <span pulumi-lang-nodejs="`buildExportAvailable`" pulumi-lang-dotnet="`BuildExportAvailable`" pulumi-lang-go="`buildExportAvailable`" pulumi-lang-python="`build_export_available`" pulumi-lang-yaml="`buildExportAvailable`" pulumi-lang-java="`buildExportAvailable`" pulumi-lang-hcl="`build_export_available`">`buildExportAvailable`</span> to see whether it is available on this organization's plan.
     */
    buildExportLocation?: pulumi.Input<string | undefined>;
    /**
     * The strategy used to export build data, which decides the scheme the bucket is addressed with. The strategies this organization accepts are listed in <span pulumi-lang-nodejs="`buildExportSupportedStrategies`" pulumi-lang-dotnet="`BuildExportSupportedStrategies`" pulumi-lang-go="`buildExportSupportedStrategies`" pulumi-lang-python="`build_export_supported_strategies`" pulumi-lang-yaml="`buildExportSupportedStrategies`" pulumi-lang-java="`buildExportSupportedStrategies`" pulumi-lang-hcl="`build_export_supported_strategies`">`buildExportSupportedStrategies`</span>, and are usually <span pulumi-lang-nodejs="`s3`" pulumi-lang-dotnet="`S3`" pulumi-lang-go="`s3`" pulumi-lang-python="`s3`" pulumi-lang-yaml="`s3`" pulumi-lang-java="`s3`" pulumi-lang-hcl="`s3`">`s3`</span> and <span pulumi-lang-nodejs="`gcs`" pulumi-lang-dotnet="`Gcs`" pulumi-lang-go="`gcs`" pulumi-lang-python="`gcs`" pulumi-lang-yaml="`gcs`" pulumi-lang-java="`gcs`" pulumi-lang-hcl="`gcs`">`gcs`</span>. Always configured alongside <span pulumi-lang-nodejs="`buildExportLocation`" pulumi-lang-dotnet="`BuildExportLocation`" pulumi-lang-go="`buildExportLocation`" pulumi-lang-python="`build_export_location`" pulumi-lang-yaml="`buildExportLocation`" pulumi-lang-java="`buildExportLocation`" pulumi-lang-hcl="`build_export_location`">`buildExportLocation`</span>.
     */
    buildExportStrategyId?: pulumi.Input<string | undefined>;
    /**
     * The default branch that new pipelines in the organization are created with. If omitted, the current setting is left unchanged.
     */
    defaultBranch?: pulumi.Input<string | undefined>;
    /**
     * The UUID of the cluster that new pipelines in the organization are created in. Set this to an empty string to leave new pipelines without a default cluster. If omitted, the current setting is left unchanged.
     */
    defaultClusterId?: pulumi.Input<string | undefined>;
    /**
     * The default command timeout, in minutes, applied to jobs that do not set their own. If omitted, the current setting is left unchanged.
     */
    defaultTimeoutInMinutes?: pulumi.Input<number | undefined>;
    /**
     * Whether remote access to hosted agents is enabled, which covers SSH access to all hosted agents and VNC access to supported macOS hosted jobs. If omitted, the current setting is left unchanged.
     */
    hostedAgentsTerminalAccessEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * The longest command timeout, in minutes, that any pipeline in the organization may set. If omitted, the current setting is left unchanged.
     */
    maximumTimeoutInMinutes?: pulumi.Input<number | undefined>;
    /**
     * Whether members of the organization can create public pipelines. If omitted, the current setting is left unchanged.
     */
    publicPipelineCreationEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * How long a scheduled job waits, in minutes, before it expires without having started. Must be between 60 and 43200. If omitted, the current setting is left unchanged.
     */
    scheduledJobExpiryInMinutes?: pulumi.Input<number | undefined>;
}
