// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Portal extends pulumi.CustomResource {
    /**
     * Get an existing Portal resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PortalState, opts?: pulumi.CustomResourceOptions): Portal {
        return new Portal(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'buildkite:index/portal:Portal';

    /**
     * Returns true if the given object is an instance of Portal.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Portal {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Portal.__pulumiType;
    }

    /**
     * Space-delimited list of IP addresses (in CIDR notation) allowed to invoke this portal. If not specified, all IP addresses are allowed.
     */
    declare public readonly allowedIpAddresses: pulumi.Output<string | undefined>;
    /**
     * The time when the portal was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Information about the user who created the portal.
     */
    declare public /*out*/ readonly createdBy: pulumi.Output<outputs.PortalCreatedBy>;
    /**
     * A description of the portal.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The name of the portal.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The GraphQL query that the portal executes.
     */
    declare public readonly query: pulumi.Output<string>;
    /**
     * The slug of the portal. Used in the portal's URL path.
     */
    declare public readonly slug: pulumi.Output<string>;
    /**
     * The token used to invoke the portal. Only returned on creation.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * Whether users can invoke the portal. Defaults to false.
     */
    declare public readonly userInvokable: pulumi.Output<boolean>;
    /**
     * The UUID of the portal.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a Portal resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PortalArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PortalArgs | PortalState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PortalState | undefined;
            resourceInputs["allowedIpAddresses"] = state?.allowedIpAddresses;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["createdBy"] = state?.createdBy;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["query"] = state?.query;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["token"] = state?.token;
            resourceInputs["userInvokable"] = state?.userInvokable;
            resourceInputs["uuid"] = state?.uuid;
        } else {
            const args = argsOrState as PortalArgs | undefined;
            if (args?.query === undefined && !opts.urn) {
                throw new Error("Missing required property 'query'");
            }
            if (args?.slug === undefined && !opts.urn) {
                throw new Error("Missing required property 'slug'");
            }
            resourceInputs["allowedIpAddresses"] = args?.allowedIpAddresses;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["query"] = args?.query;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["userInvokable"] = args?.userInvokable;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["createdBy"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Portal.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Portal resources.
 */
export interface PortalState {
    /**
     * Space-delimited list of IP addresses (in CIDR notation) allowed to invoke this portal. If not specified, all IP addresses are allowed.
     */
    allowedIpAddresses?: pulumi.Input<string>;
    /**
     * The time when the portal was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Information about the user who created the portal.
     */
    createdBy?: pulumi.Input<inputs.PortalCreatedBy>;
    /**
     * A description of the portal.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the portal.
     */
    name?: pulumi.Input<string>;
    /**
     * The GraphQL query that the portal executes.
     */
    query?: pulumi.Input<string>;
    /**
     * The slug of the portal. Used in the portal's URL path.
     */
    slug?: pulumi.Input<string>;
    /**
     * The token used to invoke the portal. Only returned on creation.
     */
    token?: pulumi.Input<string>;
    /**
     * Whether users can invoke the portal. Defaults to false.
     */
    userInvokable?: pulumi.Input<boolean>;
    /**
     * The UUID of the portal.
     */
    uuid?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Portal resource.
 */
export interface PortalArgs {
    /**
     * Space-delimited list of IP addresses (in CIDR notation) allowed to invoke this portal. If not specified, all IP addresses are allowed.
     */
    allowedIpAddresses?: pulumi.Input<string>;
    /**
     * A description of the portal.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the portal.
     */
    name?: pulumi.Input<string>;
    /**
     * The GraphQL query that the portal executes.
     */
    query: pulumi.Input<string>;
    /**
     * The slug of the portal. Used in the portal's URL path.
     */
    slug: pulumi.Input<string>;
    /**
     * Whether users can invoke the portal. Defaults to false.
     */
    userInvokable?: pulumi.Input<boolean>;
}
