// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TeamRegistry extends pulumi.CustomResource {
    /**
     * Get an existing TeamRegistry resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TeamRegistryState, opts?: pulumi.CustomResourceOptions): TeamRegistry {
        return new TeamRegistry(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'buildkite:index/teamRegistry:TeamRegistry';

    /**
     * Returns true if the given object is an instance of TeamRegistry.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TeamRegistry {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TeamRegistry.__pulumiType;
    }

    /**
     * The access level the team has on the registry. Either `READ_ONLY`, `READ_AND_WRITE` or `READ_WRITE_AND_ADMIN`.
     */
    declare public readonly accessLevel: pulumi.Output<string>;
    /**
     * The GraphQL ID of the registry.
     */
    declare public readonly registryId: pulumi.Output<string>;
    /**
     * The GraphQL ID of the team.
     */
    declare public readonly teamId: pulumi.Output<string>;
    /**
     * The UUID of the team-registry relationship.
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;

    /**
     * Create a TeamRegistry resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeamRegistryArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TeamRegistryArgs | TeamRegistryState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TeamRegistryState | undefined;
            resourceInputs["accessLevel"] = state?.accessLevel;
            resourceInputs["registryId"] = state?.registryId;
            resourceInputs["teamId"] = state?.teamId;
            resourceInputs["uuid"] = state?.uuid;
        } else {
            const args = argsOrState as TeamRegistryArgs | undefined;
            if (args?.accessLevel === undefined && !opts.urn) {
                throw new Error("Missing required property 'accessLevel'");
            }
            if (args?.registryId === undefined && !opts.urn) {
                throw new Error("Missing required property 'registryId'");
            }
            if (args?.teamId === undefined && !opts.urn) {
                throw new Error("Missing required property 'teamId'");
            }
            resourceInputs["accessLevel"] = args?.accessLevel;
            resourceInputs["registryId"] = args?.registryId;
            resourceInputs["teamId"] = args?.teamId;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TeamRegistry.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering TeamRegistry resources.
 */
export interface TeamRegistryState {
    /**
     * The access level the team has on the registry. Either `READ_ONLY`, `READ_AND_WRITE` or `READ_WRITE_AND_ADMIN`.
     */
    accessLevel?: pulumi.Input<string | undefined>;
    /**
     * The GraphQL ID of the registry.
     */
    registryId?: pulumi.Input<string | undefined>;
    /**
     * The GraphQL ID of the team.
     */
    teamId?: pulumi.Input<string | undefined>;
    /**
     * The UUID of the team-registry relationship.
     */
    uuid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TeamRegistry resource.
 */
export interface TeamRegistryArgs {
    /**
     * The access level the team has on the registry. Either `READ_ONLY`, `READ_AND_WRITE` or `READ_WRITE_AND_ADMIN`.
     */
    accessLevel: pulumi.Input<string>;
    /**
     * The GraphQL ID of the registry.
     */
    registryId: pulumi.Input<string>;
    /**
     * The GraphQL ID of the team.
     */
    teamId: pulumi.Input<string>;
}
