// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DomainRecordsRecord {
    /**
     * Possible values are URL or IP address. The value for this parameter is based on record type
     */
    address: string;
    /**
     * Sub-domain/hostname to create the record for
     */
    hostname: string;
    /**
     * MX preference for host. Applicable for MX records only
     */
    mxPref?: number;
    /**
     * Time to live for all record types. Possible values: any value between 60 to 60000
     */
    ttl?: number;
    /**
     * Possible values: A, AAAA, ALIAS, CAA, CNAME, MX, MXE, NS, TXT, URL, URL301, FRAME
     */
    type: string;
}

