// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Determines whether a directory exists at a given path.
 *
 * Given a path string, will return true if the directory exists. This function works only with directories. If used with a file, the function will return an error.
 *
 * This function behaves similar to the built-in [`fileexists`](https://developer.hashicorp.com/terraform/language/functions/fileexists) function, however, `direxists` will not replace filesystem paths including `~` with the current user's home directory path. This functionality can be achieved by using the built-in [`pathexpand`](https://developer.hashicorp.com/terraform/language/functions/pathexpand) function with `direxists`, see example below.
 */
export function direxists(path: string, opts?: pulumi.InvokeOptions): Promise<boolean> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeSingle("local:index/direxists:direxists", {
        "path": path,
    }, opts, utilities.getPackage());
}
/**
 * Determines whether a directory exists at a given path.
 *
 * Given a path string, will return true if the directory exists. This function works only with directories. If used with a file, the function will return an error.
 *
 * This function behaves similar to the built-in [`fileexists`](https://developer.hashicorp.com/terraform/language/functions/fileexists) function, however, `direxists` will not replace filesystem paths including `~` with the current user's home directory path. This functionality can be achieved by using the built-in [`pathexpand`](https://developer.hashicorp.com/terraform/language/functions/pathexpand) function with `direxists`, see example below.
 */
export function direxistsOutput(path: pulumi.Input<string>, opts?: pulumi.InvokeOutputOptions): pulumi.Output<boolean> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeSingleOutput("local:index/direxists:direxists", {
        "path": path,
    }, opts, utilities.getPackage());
}
