// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ConnectionDataSource {
    dataSources: string[];
    sourceId: number;
    sourceName: string;
    teamName: string;
}

export interface ErrorsApplicationCustomBucket {
    /**
     * Access key ID
     */
    accessKeyId: string;
    /**
     * Bucket endpoint
     */
    endpoint: string;
    /**
     * Whether we should keep data in the bucket after the retention period.
     */
    keepDataAfterRetention?: boolean;
    /**
     * Bucket name
     */
    name: string;
    /**
     * Secret access key
     */
    secretAccessKey: string;
}

export interface GetConnectionDataSource {
    dataSources: string[];
    sourceId: number;
    sourceName: string;
    teamName: string;
}

export interface GetErrorsApplicationCustomBucket {
    accessKeyId: string;
    endpoint: string;
    keepDataAfterRetention: boolean;
    name: string;
    secretAccessKey: string;
}

export interface GetSourceCustomBucket {
    accessKeyId: string;
    endpoint: string;
    keepDataAfterRetention: boolean;
    name: string;
    secretAccessKey: string;
}

export interface GetWarehouseSourceCustomBucket {
    accessKeyId: string;
    endpoint: string;
    keepDataAfterRetention: boolean;
    name: string;
    secretAccessKey: string;
}

export interface SourceCustomBucket {
    /**
     * Access key ID
     */
    accessKeyId: string;
    /**
     * Bucket endpoint
     */
    endpoint: string;
    /**
     * Whether we should keep data in the bucket after the retention period.
     */
    keepDataAfterRetention?: boolean;
    /**
     * Bucket name
     */
    name: string;
    /**
     * Secret access key
     */
    secretAccessKey: string;
}

export interface WarehouseSourceCustomBucket {
    /**
     * Access key ID
     */
    accessKeyId: string;
    /**
     * Bucket endpoint
     */
    endpoint: string;
    /**
     * Whether we should keep data in the bucket after the retention period.
     */
    keepDataAfterRetention?: boolean;
    /**
     * Bucket name
     */
    name: string;
    /**
     * Secret access key
     */
    secretAccessKey: string;
}

