// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class BuildConfigurationStep extends pulumi.CustomResource {
    /**
     * Get an existing BuildConfigurationStep resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BuildConfigurationStepState, opts?: pulumi.CustomResourceOptions): BuildConfigurationStep {
        return new BuildConfigurationStep(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teamcity:index/buildConfigurationStep:BuildConfigurationStep';

    /**
     * Returns true if the given object is an instance of BuildConfigurationStep.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BuildConfigurationStep {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BuildConfigurationStep.__pulumiType;
    }

    declare public readonly buildConfigurationId: pulumi.Output<string>;
    /**
     * Name of the build step.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Properties for the build runner.
     */
    declare public readonly properties: pulumi.Output<{[key: string]: string}>;
    /**
     * The type of the build runner (e.g., simpleRunner, Maven2, Ant).
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a BuildConfigurationStep resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BuildConfigurationStepArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BuildConfigurationStepArgs | BuildConfigurationStepState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BuildConfigurationStepState | undefined;
            resourceInputs["buildConfigurationId"] = state?.buildConfigurationId;
            resourceInputs["name"] = state?.name;
            resourceInputs["properties"] = state?.properties;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as BuildConfigurationStepArgs | undefined;
            if (args?.buildConfigurationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'buildConfigurationId'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["buildConfigurationId"] = args?.buildConfigurationId;
            resourceInputs["name"] = args?.name;
            resourceInputs["properties"] = args?.properties;
            resourceInputs["type"] = args?.type;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BuildConfigurationStep.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering BuildConfigurationStep resources.
 */
export interface BuildConfigurationStepState {
    buildConfigurationId?: pulumi.Input<string | undefined>;
    /**
     * Name of the build step.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Properties for the build runner.
     */
    properties?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The type of the build runner (e.g., simpleRunner, Maven2, Ant).
     */
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a BuildConfigurationStep resource.
 */
export interface BuildConfigurationStepArgs {
    buildConfigurationId: pulumi.Input<string>;
    /**
     * Name of the build step.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Properties for the build runner.
     */
    properties?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The type of the build runner (e.g., simpleRunner, Maven2, Ant).
     */
    type: pulumi.Input<string>;
}
