// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VersionedSettings extends pulumi.CustomResource {
    /**
     * Get an existing VersionedSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VersionedSettingsState, opts?: pulumi.CustomResourceOptions): VersionedSettings {
        return new VersionedSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'teamcity:index/versionedSettings:VersionedSettings';

    /**
     * Returns true if the given object is an instance of VersionedSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VersionedSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VersionedSettings.__pulumiType;
    }

    declare public readonly allowUiEditing: pulumi.Output<boolean>;
    declare public readonly projectId: pulumi.Output<string>;
    declare public readonly settings: pulumi.Output<string>;
    declare public readonly showChanges: pulumi.Output<boolean>;
    declare public readonly vcsrootId: pulumi.Output<string>;

    /**
     * Create a VersionedSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VersionedSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VersionedSettingsArgs | VersionedSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VersionedSettingsState | undefined;
            resourceInputs["allowUiEditing"] = state?.allowUiEditing;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["settings"] = state?.settings;
            resourceInputs["showChanges"] = state?.showChanges;
            resourceInputs["vcsrootId"] = state?.vcsrootId;
        } else {
            const args = argsOrState as VersionedSettingsArgs | undefined;
            if (args?.allowUiEditing === undefined && !opts.urn) {
                throw new Error("Missing required property 'allowUiEditing'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.settings === undefined && !opts.urn) {
                throw new Error("Missing required property 'settings'");
            }
            if (args?.showChanges === undefined && !opts.urn) {
                throw new Error("Missing required property 'showChanges'");
            }
            if (args?.vcsrootId === undefined && !opts.urn) {
                throw new Error("Missing required property 'vcsrootId'");
            }
            resourceInputs["allowUiEditing"] = args?.allowUiEditing;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["settings"] = args?.settings;
            resourceInputs["showChanges"] = args?.showChanges;
            resourceInputs["vcsrootId"] = args?.vcsrootId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VersionedSettings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering VersionedSettings resources.
 */
export interface VersionedSettingsState {
    allowUiEditing?: pulumi.Input<boolean>;
    projectId?: pulumi.Input<string>;
    settings?: pulumi.Input<string>;
    showChanges?: pulumi.Input<boolean>;
    vcsrootId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a VersionedSettings resource.
 */
export interface VersionedSettingsArgs {
    allowUiEditing: pulumi.Input<boolean>;
    projectId: pulumi.Input<string>;
    settings: pulumi.Input<string>;
    showChanges: pulumi.Input<boolean>;
    vcsrootId: pulumi.Input<string>;
}
