// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getComputeContainerAppContainer(args: GetComputeContainerAppContainerArgs, opts?: pulumi.InvokeOptions): Promise<GetComputeContainerAppContainerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bunnynet:index/getComputeContainerAppContainer:getComputeContainerAppContainer", {
        "app": args.app,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getComputeContainerAppContainer.
 */
export interface GetComputeContainerAppContainerArgs {
    app: string;
    name: string;
}

/**
 * A collection of values returned by getComputeContainerAppContainer.
 */
export interface GetComputeContainerAppContainerResult {
    readonly app: string;
    readonly id: string;
    readonly name: string;
}
export function getComputeContainerAppContainerOutput(args: GetComputeContainerAppContainerOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetComputeContainerAppContainerResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bunnynet:index/getComputeContainerAppContainer:getComputeContainerAppContainer", {
        "app": args.app,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getComputeContainerAppContainer.
 */
export interface GetComputeContainerAppContainerOutputArgs {
    app: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
