// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ErrorsRelease extends pulumi.CustomResource {
    /**
     * Get an existing ErrorsRelease resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ErrorsReleaseState, opts?: pulumi.CustomResourceOptions): ErrorsRelease {
        return new ErrorsRelease(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'logtail:index/errorsRelease:ErrorsRelease';

    /**
     * Returns true if the given object is an instance of ErrorsRelease.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ErrorsRelease {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ErrorsRelease.__pulumiType;
    }

    /**
     * The ID of the Errors application this release belongs to. The API resolves the value to the canonical application ID, which may differ from the one you provide when the application has sibling sources - state always keeps the canonical ID.
     */
    declare public readonly applicationId: pulumi.Output<number>;
    /**
     * The time when this release was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Environments the release was deployed to, e.g. `["production"]`. The server keeps merging in environments the release is later seen in, so state always keeps the configured value.
     */
    declare public readonly environments: pulumi.Output<string[] | undefined>;
    /**
     * The time when this release was first seen.
     */
    declare public /*out*/ readonly firstSeenAt: pulumi.Output<string>;
    /**
     * How this release was detected, e.g. <span pulumi-lang-nodejs="`reported`" pulumi-lang-dotnet="`Reported`" pulumi-lang-go="`reported`" pulumi-lang-python="`reported`" pulumi-lang-yaml="`reported`" pulumi-lang-java="`reported`" pulumi-lang-hcl="`reported`">`reported`</span> for releases registered via the API.
     */
    declare public /*out*/ readonly origin: pulumi.Output<string>;
    /**
     * The time when this release was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * Release version or commit ref, e.g. `v1.2.3` or a commit SHA.
     */
    declare public readonly version: pulumi.Output<string>;

    /**
     * Create a ErrorsRelease resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ErrorsReleaseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ErrorsReleaseArgs | ErrorsReleaseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ErrorsReleaseState | undefined;
            resourceInputs["applicationId"] = state?.applicationId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["environments"] = state?.environments;
            resourceInputs["firstSeenAt"] = state?.firstSeenAt;
            resourceInputs["origin"] = state?.origin;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as ErrorsReleaseArgs | undefined;
            if (args?.applicationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'applicationId'");
            }
            if (args?.version === undefined && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            resourceInputs["applicationId"] = args?.applicationId;
            resourceInputs["environments"] = args?.environments;
            resourceInputs["version"] = args?.version;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["firstSeenAt"] = undefined /*out*/;
            resourceInputs["origin"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ErrorsRelease.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ErrorsRelease resources.
 */
export interface ErrorsReleaseState {
    /**
     * The ID of the Errors application this release belongs to. The API resolves the value to the canonical application ID, which may differ from the one you provide when the application has sibling sources - state always keeps the canonical ID.
     */
    applicationId?: pulumi.Input<number | undefined>;
    /**
     * The time when this release was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Environments the release was deployed to, e.g. `["production"]`. The server keeps merging in environments the release is later seen in, so state always keeps the configured value.
     */
    environments?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The time when this release was first seen.
     */
    firstSeenAt?: pulumi.Input<string | undefined>;
    /**
     * How this release was detected, e.g. <span pulumi-lang-nodejs="`reported`" pulumi-lang-dotnet="`Reported`" pulumi-lang-go="`reported`" pulumi-lang-python="`reported`" pulumi-lang-yaml="`reported`" pulumi-lang-java="`reported`" pulumi-lang-hcl="`reported`">`reported`</span> for releases registered via the API.
     */
    origin?: pulumi.Input<string | undefined>;
    /**
     * The time when this release was last updated.
     */
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * Release version or commit ref, e.g. `v1.2.3` or a commit SHA.
     */
    version?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ErrorsRelease resource.
 */
export interface ErrorsReleaseArgs {
    /**
     * The ID of the Errors application this release belongs to. The API resolves the value to the canonical application ID, which may differ from the one you provide when the application has sibling sources - state always keeps the canonical ID.
     */
    applicationId: pulumi.Input<number>;
    /**
     * Environments the release was deployed to, e.g. `["production"]`. The server keeps merging in environments the release is later seen in, so state always keeps the configured value.
     */
    environments?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Release version or commit ref, e.g. `v1.2.3` or a commit SHA.
     */
    version: pulumi.Input<string>;
}
