// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSource(args: GetSourceArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("logtail:index/getSource:getSource", {
        "tableName": args.tableName,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSource.
 */
export interface GetSourceArgs {
    tableName: string;
}

/**
 * A collection of values returned by getSource.
 */
export interface GetSourceResult {
    readonly createdAt: string;
    readonly customBuckets: outputs.GetSourceCustomBucket[];
    readonly dataRegion: string;
    readonly id: string;
    readonly ingestingHost: string;
    readonly ingestingPaused: boolean;
    readonly liveTailPattern: string;
    readonly logsRetention: number;
    readonly metricsRetention: number;
    readonly name: string;
    readonly platform: string;
    readonly scrapeFrequencySecs: number;
    readonly scrapeRequestBasicAuthPassword: string;
    readonly scrapeRequestBasicAuthUser: string;
    readonly scrapeRequestHeaders: {[key: string]: string}[];
    readonly scrapeUrls: string[];
    readonly sourceGroupId: number;
    readonly tableName: string;
    readonly teamId: string;
    readonly teamName: string;
    readonly token: string;
    readonly updatedAt: string;
    readonly vrlTransformation: string;
}
export function getSourceOutput(args: GetSourceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("logtail:index/getSource:getSource", {
        "tableName": args.tableName,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSource.
 */
export interface GetSourceOutputArgs {
    tableName: pulumi.Input<string>;
}
