// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getWarehouseSource(args: GetWarehouseSourceArgs, opts?: pulumi.InvokeOptions): Promise<GetWarehouseSourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("logtail:index/getWarehouseSource:getWarehouseSource", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getWarehouseSource.
 */
export interface GetWarehouseSourceArgs {
    name: string;
}

/**
 * A collection of values returned by getWarehouseSource.
 */
export interface GetWarehouseSourceResult {
    readonly createdAt: string;
    readonly customBuckets: outputs.GetWarehouseSourceCustomBucket[];
    readonly dataRegion: string;
    readonly eventsRetention: number;
    readonly id: string;
    readonly ingestingHost: string;
    readonly ingestingPaused: boolean;
    readonly liveTailPattern: string;
    readonly name: string;
    readonly tableName: string;
    readonly teamName: string;
    readonly timeSeriesRetention: number;
    readonly token: string;
    readonly updatedAt: string;
    readonly vrlTransformation: string;
    readonly warehouseSourceGroupId: number;
}
export function getWarehouseSourceOutput(args: GetWarehouseSourceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetWarehouseSourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("logtail:index/getWarehouseSource:getWarehouseSource", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getWarehouseSource.
 */
export interface GetWarehouseSourceOutputArgs {
    name: pulumi.Input<string>;
}
