// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class WarehouseSource extends pulumi.CustomResource {
    /**
     * Get an existing WarehouseSource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WarehouseSourceState, opts?: pulumi.CustomResourceOptions): WarehouseSource {
        return new WarehouseSource(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'logtail:index/warehouseSource:WarehouseSource';

    /**
     * Returns true if the given object is an instance of WarehouseSource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WarehouseSource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WarehouseSource.__pulumiType;
    }

    /**
     * The time when this warehouse source was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Optional custom bucket configuration for the source. When provided, all fields (name, endpoint, access_key_id, secret_access_key) are required.
     */
    declare public readonly customBucket: pulumi.Output<outputs.WarehouseSourceCustomBucket | undefined>;
    /**
     * The data region or cluster name where the source's data will be stored.
     * Possible values include <span pulumi-lang-nodejs="`usEast`" pulumi-lang-dotnet="`UsEast`" pulumi-lang-go="`usEast`" pulumi-lang-python="`us_east`" pulumi-lang-yaml="`usEast`" pulumi-lang-java="`usEast`">`us_east`</span>, <span pulumi-lang-nodejs="`germany`" pulumi-lang-dotnet="`Germany`" pulumi-lang-go="`germany`" pulumi-lang-python="`germany`" pulumi-lang-yaml="`germany`" pulumi-lang-java="`germany`">`germany`</span>, <span pulumi-lang-nodejs="`singapore`" pulumi-lang-dotnet="`Singapore`" pulumi-lang-go="`singapore`" pulumi-lang-python="`singapore`" pulumi-lang-yaml="`singapore`" pulumi-lang-java="`singapore`">`singapore`</span>, or a specific cluster name like `us-east-9`.
     * The actual region created may differ slightly due to dynamic load balancing.
     */
    declare public readonly dataRegion: pulumi.Output<string>;
    /**
     * The retention period for event data in days. Default is 9999999 days (effectively infinite).
     */
    declare public readonly eventsRetention: pulumi.Output<number>;
    /**
     * The host where the data should be sent. See documentation for details.
     */
    declare public /*out*/ readonly ingestingHost: pulumi.Output<string>;
    /**
     * This property allows you to temporarily pause data ingesting for this source.
     */
    declare public readonly ingestingPaused: pulumi.Output<boolean>;
    /**
     * A display template for live tail messages. Default is `"{status} {message}"`.
     */
    declare public readonly liveTailPattern: pulumi.Output<string>;
    /**
     * The name of the new Warehouse source. Can contain letters, numbers, spaces, and special characters. Source names do not need to be unique.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The table name generated for this warehouse source.
     */
    declare public /*out*/ readonly tableName: pulumi.Output<string>;
    /**
     * Used to specify the team the resource should be created in when using global tokens.
     */
    declare public readonly teamName: pulumi.Output<string | undefined>;
    /**
     * The retention period for time series data in days. Default is 9999999 days (effectively infinite).
     */
    declare public readonly timeSeriesRetention: pulumi.Output<number>;
    /**
     * The token of this warehouse source. This token is used to identify and route the data you will send to Better Stack.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * The time when this warehouse source was updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * A VRL program for real-time data transformation. Read more about [VRL transformations](https://betterstack.com/docs/logs/using-logtail/transforming-ingested-data/logs-vrl/).
     */
    declare public readonly vrlTransformation: pulumi.Output<string | undefined>;
    /**
     * The ID of the warehouse source group this source belongs to.
     */
    declare public readonly warehouseSourceGroupId: pulumi.Output<number>;

    /**
     * Create a WarehouseSource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WarehouseSourceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WarehouseSourceArgs | WarehouseSourceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WarehouseSourceState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["customBucket"] = state?.customBucket;
            resourceInputs["dataRegion"] = state?.dataRegion;
            resourceInputs["eventsRetention"] = state?.eventsRetention;
            resourceInputs["ingestingHost"] = state?.ingestingHost;
            resourceInputs["ingestingPaused"] = state?.ingestingPaused;
            resourceInputs["liveTailPattern"] = state?.liveTailPattern;
            resourceInputs["name"] = state?.name;
            resourceInputs["tableName"] = state?.tableName;
            resourceInputs["teamName"] = state?.teamName;
            resourceInputs["timeSeriesRetention"] = state?.timeSeriesRetention;
            resourceInputs["token"] = state?.token;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["vrlTransformation"] = state?.vrlTransformation;
            resourceInputs["warehouseSourceGroupId"] = state?.warehouseSourceGroupId;
        } else {
            const args = argsOrState as WarehouseSourceArgs | undefined;
            if (args?.warehouseSourceGroupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'warehouseSourceGroupId'");
            }
            resourceInputs["customBucket"] = args?.customBucket;
            resourceInputs["dataRegion"] = args?.dataRegion;
            resourceInputs["eventsRetention"] = args?.eventsRetention;
            resourceInputs["ingestingPaused"] = args?.ingestingPaused;
            resourceInputs["liveTailPattern"] = args?.liveTailPattern;
            resourceInputs["name"] = args?.name;
            resourceInputs["teamName"] = args?.teamName;
            resourceInputs["timeSeriesRetention"] = args?.timeSeriesRetention;
            resourceInputs["vrlTransformation"] = args?.vrlTransformation;
            resourceInputs["warehouseSourceGroupId"] = args?.warehouseSourceGroupId;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["ingestingHost"] = undefined /*out*/;
            resourceInputs["tableName"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WarehouseSource.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering WarehouseSource resources.
 */
export interface WarehouseSourceState {
    /**
     * The time when this warehouse source was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Optional custom bucket configuration for the source. When provided, all fields (name, endpoint, access_key_id, secret_access_key) are required.
     */
    customBucket?: pulumi.Input<inputs.WarehouseSourceCustomBucket>;
    /**
     * The data region or cluster name where the source's data will be stored.
     * Possible values include <span pulumi-lang-nodejs="`usEast`" pulumi-lang-dotnet="`UsEast`" pulumi-lang-go="`usEast`" pulumi-lang-python="`us_east`" pulumi-lang-yaml="`usEast`" pulumi-lang-java="`usEast`">`us_east`</span>, <span pulumi-lang-nodejs="`germany`" pulumi-lang-dotnet="`Germany`" pulumi-lang-go="`germany`" pulumi-lang-python="`germany`" pulumi-lang-yaml="`germany`" pulumi-lang-java="`germany`">`germany`</span>, <span pulumi-lang-nodejs="`singapore`" pulumi-lang-dotnet="`Singapore`" pulumi-lang-go="`singapore`" pulumi-lang-python="`singapore`" pulumi-lang-yaml="`singapore`" pulumi-lang-java="`singapore`">`singapore`</span>, or a specific cluster name like `us-east-9`.
     * The actual region created may differ slightly due to dynamic load balancing.
     */
    dataRegion?: pulumi.Input<string>;
    /**
     * The retention period for event data in days. Default is 9999999 days (effectively infinite).
     */
    eventsRetention?: pulumi.Input<number>;
    /**
     * The host where the data should be sent. See documentation for details.
     */
    ingestingHost?: pulumi.Input<string>;
    /**
     * This property allows you to temporarily pause data ingesting for this source.
     */
    ingestingPaused?: pulumi.Input<boolean>;
    /**
     * A display template for live tail messages. Default is `"{status} {message}"`.
     */
    liveTailPattern?: pulumi.Input<string>;
    /**
     * The name of the new Warehouse source. Can contain letters, numbers, spaces, and special characters. Source names do not need to be unique.
     */
    name?: pulumi.Input<string>;
    /**
     * The table name generated for this warehouse source.
     */
    tableName?: pulumi.Input<string>;
    /**
     * Used to specify the team the resource should be created in when using global tokens.
     */
    teamName?: pulumi.Input<string>;
    /**
     * The retention period for time series data in days. Default is 9999999 days (effectively infinite).
     */
    timeSeriesRetention?: pulumi.Input<number>;
    /**
     * The token of this warehouse source. This token is used to identify and route the data you will send to Better Stack.
     */
    token?: pulumi.Input<string>;
    /**
     * The time when this warehouse source was updated.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * A VRL program for real-time data transformation. Read more about [VRL transformations](https://betterstack.com/docs/logs/using-logtail/transforming-ingested-data/logs-vrl/).
     */
    vrlTransformation?: pulumi.Input<string>;
    /**
     * The ID of the warehouse source group this source belongs to.
     */
    warehouseSourceGroupId?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a WarehouseSource resource.
 */
export interface WarehouseSourceArgs {
    /**
     * Optional custom bucket configuration for the source. When provided, all fields (name, endpoint, access_key_id, secret_access_key) are required.
     */
    customBucket?: pulumi.Input<inputs.WarehouseSourceCustomBucket>;
    /**
     * The data region or cluster name where the source's data will be stored.
     * Possible values include <span pulumi-lang-nodejs="`usEast`" pulumi-lang-dotnet="`UsEast`" pulumi-lang-go="`usEast`" pulumi-lang-python="`us_east`" pulumi-lang-yaml="`usEast`" pulumi-lang-java="`usEast`">`us_east`</span>, <span pulumi-lang-nodejs="`germany`" pulumi-lang-dotnet="`Germany`" pulumi-lang-go="`germany`" pulumi-lang-python="`germany`" pulumi-lang-yaml="`germany`" pulumi-lang-java="`germany`">`germany`</span>, <span pulumi-lang-nodejs="`singapore`" pulumi-lang-dotnet="`Singapore`" pulumi-lang-go="`singapore`" pulumi-lang-python="`singapore`" pulumi-lang-yaml="`singapore`" pulumi-lang-java="`singapore`">`singapore`</span>, or a specific cluster name like `us-east-9`.
     * The actual region created may differ slightly due to dynamic load balancing.
     */
    dataRegion?: pulumi.Input<string>;
    /**
     * The retention period for event data in days. Default is 9999999 days (effectively infinite).
     */
    eventsRetention?: pulumi.Input<number>;
    /**
     * This property allows you to temporarily pause data ingesting for this source.
     */
    ingestingPaused?: pulumi.Input<boolean>;
    /**
     * A display template for live tail messages. Default is `"{status} {message}"`.
     */
    liveTailPattern?: pulumi.Input<string>;
    /**
     * The name of the new Warehouse source. Can contain letters, numbers, spaces, and special characters. Source names do not need to be unique.
     */
    name?: pulumi.Input<string>;
    /**
     * Used to specify the team the resource should be created in when using global tokens.
     */
    teamName?: pulumi.Input<string>;
    /**
     * The retention period for time series data in days. Default is 9999999 days (effectively infinite).
     */
    timeSeriesRetention?: pulumi.Input<number>;
    /**
     * A VRL program for real-time data transformation. Read more about [VRL transformations](https://betterstack.com/docs/logs/using-logtail/transforming-ingested-data/logs-vrl/).
     */
    vrlTransformation?: pulumi.Input<string>;
    /**
     * The ID of the warehouse source group this source belongs to.
     */
    warehouseSourceGroupId: pulumi.Input<number>;
}
